const v = {
  name: ["nom accessible", "accessible name", "Texte calculé qui identifie un contrôle dans l'arbre d'accessibilité.", "Computed text that identifies a control in the accessibility tree."],
  tree: ["arbre d'accessibilité", "accessibility tree", "Représentation exposée aux technologies d'assistance.", "Representation exposed to assistive technologies."],
  modal: ["modale accessible", "accessible modal", "Dialogue qui gère rôle, nom, focus, fermeture et contexte.", "Dialog that manages role, name, focus, closing, and context."],
  live: ["région live", "live region", "Zone dont les changements sont annoncés sans déplacement de focus.", "Region whose changes are announced without moving focus."],
  motion: ["mouvement réduit", "reduced motion", "Préférence utilisateur limitant animations et transitions non essentielles.", "User preference limiting non-essential animations and transitions."],
  target: ["cible tactile", "touch target", "Zone activable assez grande et espacée pour l'usage tactile.", "Activatable area large and spaced enough for touch use."],
  wcag: ["WCAG", "WCAG", "Référentiel international de critères d'accessibilité web.", "International reference of web accessibility criteria."],
  assistive: ["technologie d'assistance", "assistive technology", "Outil comme lecteur d'écran, loupe ou commande vocale.", "Tool such as screen reader, magnifier, or voice control."]
};

const track = {
  id: "accessibility",
  label: "A11Y",
  title: ["Accessibilité web", "Web accessibility"],
  summary: ["Auditer et corriger des parcours réels avec preuves clavier, lecteur d'écran, mobile et WCAG.", "Audit and fix real journeys with keyboard, screen reader, mobile, and WCAG evidence."],
  profession: ["L'accessibilité se prouve par l'usage : nom, rôle, état, focus, annonce, contraste et capacité à terminer la tâche.", "Accessibility is proven through use: name, role, state, focus, announcement, contrast, and ability to finish the task."],
  prerequisites: [["Connaître HTML/CSS", "Know HTML/CSS"], ["Savoir lancer des tests E2E et axe", "Know how to run E2E and axe tests"]],
  outcomes: [["Auditer un parcours critique", "Audit a critical journey"], ["Tester avec clavier et lecteur d'écran", "Test with keyboard and screen reader"], ["Corriger composants complexes", "Fix complex components"], ["Documenter preuves WCAG", "Document WCAG evidence"]],
  capstone: ["Audit complet d'une expérience d'apprentissage PulsaTeach avec corrections et matrice preuve → critère.", "Complete audit of a PulsaTeach learning experience with fixes and evidence → criterion matrix."],
  certification: [["Livrer les labs v9", "Ship v9 labs"], ["Réussir l'examen accessibilité", "Pass the accessibility exam"]],
  modules: [
    mod("a11y-accessibility-tree", ["Arbre d'accessibilité et lecteur d'écran", "Accessibility tree and screen reader"], [v.name, v.tree, v.assistive], [
      html("a11y-name-button", ["Nommer une action iconique", "Name an icon action"], ["Corrige un bouton icône pour qu'il ait un nom stable sans texte visible imposé.", "Fix an icon button so it has a stable name without requiring visible text."], "<button type=\"button\" aria-label=\"Sauvegarder la leçon\"><svg aria-hidden=\"true\" focusable=\"false\"></svg></button>", ["<button", "aria-label=\"Sauvegarder la leçon\"", "aria-hidden=\"true\"", "focusable=\"false\"", "type=\"button\"", "Sauvegarder"], ["accessible-name", "icon-button"]),
      html("a11y-current-page", ["Annoncer la page active", "Announce the current page"], ["Ajoute une navigation nommée et aria-current sur l'élément actif.", "Add named navigation and aria-current on the active item."], "<nav aria-label=\"Parcours\"><a href=\"/catalog\">Catalogue</a><a href=\"/learn/html\" aria-current=\"page\">HTML</a></nav>", ["<nav", "aria-label=\"Parcours\"", "aria-current=\"page\"", "href=\"/learn/html\"", "Catalogue", "HTML"], ["navigation", "current-page"]),
      text("a11y-screen-reader-script", ["Écrire un script de test lecteur d'écran", "Write a screen reader test script"], ["Décris les étapes pour vérifier nom, rôle, état et ordre d'annonce.", "Describe steps to verify name, role, state, and announcement order."], ["NVDA ou VoiceOver", "parcourir par titres", "liste des repères", "nom rôle état", "ordre d'annonce", "écart attendu/observé"], ["screen-reader-testing", "manual-audit"]),
      project("a11y-tree-lab", ["Lab : matrice arbre accessible", "Lab: accessibility tree matrix"], ["Audite une page et relie chaque contrôle à son nom, rôle, état et preuve.", "Audit a page and connect each control to name, role, state, and evidence."], "# Matrice arbre accessible\n\n| Élément | Nom | Rôle | État | Preuve |\n| --- | --- | --- | --- | --- |\n| Bouton sauvegarder | Sauvegarder la leçon | button | enabled | lecteur d'écran annonce le nom |\n| Onglet Coder | Coder | tab | selected=false | navigation clavier |\n| Menu langue | Passer en anglais | button | expanded=false | aria-expanded vérifié |\n\n## Corrections\n- noms accessibles stables\n- SVG décoratifs aria-hidden\n- aria-current sur navigation\n- titres parcourables dans l'ordre", ["Matrice arbre accessible", "Nom", "Rôle", "État", "Preuve", "button", "tab", "aria-expanded", "aria-hidden", "aria-current", "titres parcourables", "lecteur d'écran", "Sauvegarder la leçon", "Passer en anglais", "navigation clavier", "selected=false"], ["accessibility-tree", "manual-audit"]),
      quiz("a11y-tree-quiz", ["Quiz : arbre accessible", "Quiz: accessibility tree"], [["Un bouton icône sans texte doit surtout avoir…", "An icon-only button should mainly have…", "un nom accessible stable", "une couleur vive", "un title CSS", "un nom accessible stable"], ["Que vérifie un test lecteur d'écran ?", "What does a screen reader test verify?", "nom, rôle, état et ordre", "uniquement le contraste", "la taille du bundle", "nom, rôle, état et ordre"], ["aria-current sert à…", "aria-current is used to…", "indiquer l'élément courant", "ouvrir une modale", "désactiver Tab", "indiquer l'élément courant"]])
    ]),
    mod("a11y-complex-components", ["Composants dynamiques robustes", "Robust dynamic components"], [v.modal, v.live, v.name], [
      html("a11y-modal-contract", ["Contrat d'une modale", "Modal contract"], ["Déclare un dialogue nommé qui bloque le contexte et expose un bouton de fermeture.", "Declare a named dialog that blocks context and exposes a close button."], "<section role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"quiz-title\"><h2 id=\"quiz-title\">Quiz accessibilité</h2><button type=\"button\" aria-label=\"Fermer le quiz\">×</button></section>", ["role=\"dialog\"", "aria-modal=\"true\"", "aria-labelledby=\"quiz-title\"", "id=\"quiz-title\"", "aria-label=\"Fermer le quiz\"", "<button"], ["modal-dialog", "accessible-name"]),
      html("a11y-live-feedback", ["Annoncer un résultat de quiz", "Announce quiz feedback"], ["Utilise une région live polie pour un succès et une alerte pour une erreur bloquante.", "Use a polite live region for success and an alert for a blocking error."], "<p role=\"status\" aria-live=\"polite\">Réponse enregistrée.</p><p role=\"alert\">Choisis au moins une option.</p>", ["role=\"status\"", "aria-live=\"polite\"", "Réponse enregistrée", "role=\"alert\"", "Choisis", "option"], ["live-regions", "quiz-feedback"]),
      html("a11y-tabs-contract", ["Structurer des onglets", "Structure tabs"], ["Relie tablist, tab, aria-selected et tabpanel avec des ids cohérents.", "Connect tablist, tab, aria-selected, and tabpanel with coherent ids."], "<div role=\"tablist\" aria-label=\"Mode focus\"><button role=\"tab\" id=\"tab-code\" aria-selected=\"true\" aria-controls=\"panel-code\">Coder</button></div><section role=\"tabpanel\" id=\"panel-code\" aria-labelledby=\"tab-code\">Éditeur</section>", ["role=\"tablist\"", "role=\"tab\"", "aria-selected=\"true\"", "aria-controls=\"panel-code\"", "role=\"tabpanel\"", "aria-labelledby=\"tab-code\""], ["tabs", "focus-mode"]),
      project("a11y-component-lab", ["Lab : composant interactif auditable", "Lab: auditable interactive component"], ["Documente clavier, focus, annonces et états d'une modale quiz ou d'onglets.", "Document keyboard, focus, announcements, and states of a quiz modal or tabs."], "# Contrat composant\n\n## Clavier\n- Tab reste dans la modale\n- Escape ferme et restitue le focus\n- flèches changent d'onglet si tablist\n\n## Arbre accessible\n- role dialog ou tablist\n- nom via aria-labelledby\n- état aria-selected ou aria-expanded\n\n## Annonces\n- status pour sauvegarde\n- alert pour erreur bloquante\n\n## Tests\n- axe sans violation critique\n- Playwright clavier\n- vérification lecteur d'écran", ["Contrat composant", "Tab reste", "Escape ferme", "restitue le focus", "role dialog", "tablist", "aria-labelledby", "aria-selected", "aria-expanded", "status", "alert", "axe", "Playwright clavier", "lecteur d'écran", "flèches changent", "erreur bloquante", "sans violation critique", "vérification lecteur"], ["complex-components", "keyboard-testing"]),
      quiz("a11y-component-quiz", ["Quiz : composants dynamiques", "Quiz: dynamic components"], [["Une modale accessible doit…", "An accessible modal should…", "gérer rôle, nom, focus et fermeture", "seulement être centrée", "cacher le bouton fermer", "gérer rôle, nom, focus et fermeture"], ["Un message d'erreur bloquant utilise plutôt…", "A blocking error message should use…", "role alert", "aria-hidden", "un placeholder", "role alert"], ["Un onglet sélectionné expose…", "A selected tab exposes…", "aria-selected true", "alt vide", "role status", "aria-selected true"]])
    ]),
    mod("a11y-mobile-motion", ["Mobile, zoom et préférences", "Mobile, zoom, and preferences"], [v.target, v.motion, v.wcag], [
      css("a11y-touch-targets", ["Renforcer les cibles tactiles", "Strengthen touch targets"], ["Assure des zones de 44px minimum avec espacement utilisable.", "Ensure at least 44px targets with usable spacing."], ".action { min-height: 44px; min-width: 44px; padding: .75rem 1rem; touch-action: manipulation; }", ["min-height: 44px", "min-width: 44px", "padding", "touch-action", "manipulation", ".action"], ["touch-targets", "mobile-a11y"]),
      css("a11y-zoom-reflow", ["Préserver le zoom 200 %", "Preserve 200% zoom"], ["Évite les largeurs fixes et protège les textes longs.", "Avoid fixed widths and protect long text."], ".panel { width: min(100% - 2rem, 72rem); max-width: 100%; overflow-wrap: anywhere; }", ["width: min(", "100% - 2rem", "max-width: 100%", "overflow-wrap", "anywhere", ".panel"], ["zoom-reflow", "responsive-a11y"]),
      css("a11y-reduced-motion", ["Respecter prefers-reduced-motion", "Respect prefers-reduced-motion"], ["Désactive les animations non essentielles quand la préférence est active.", "Disable non-essential animations when the preference is active."], "@media (prefers-reduced-motion: reduce) { * { animation-duration: .01ms; animation-iteration-count: 1; scroll-behavior: auto; transition-duration: .01ms; } }", ["@media", "prefers-reduced-motion: reduce", "animation-duration", "animation-iteration-count", "scroll-behavior: auto", "transition-duration"], ["reduced-motion", "motion-safety"]),
      project("a11y-mobile-lab", ["Lab : audit iPhone Pro Max", "Lab: iPhone Pro Max audit"], ["Audite quiz, menu et catalogue à 430px avec zoom, cibles tactiles et mouvement réduit.", "Audit quiz, menu, and catalog at 430px with zoom, touch targets, and reduced motion."], "# Audit mobile 430 × 932\n\n## Pages\n- /catalog\n- quiz modal\n- dashboard\n\n## Vérifications\n- aucun overflow horizontal\n- cibles 44px minimum\n- focus visible au clavier matériel\n- zoom 200 % sans perte de contenu\n- prefers-reduced-motion réduit animations\n- modale centrée et fermable\n\n## Preuves\n- screenshots 430px\n- trace Playwright\n- note des limites restantes", ["Audit mobile", "430 × 932", "/catalog", "quiz modal", "aucun overflow", "44px", "focus visible", "zoom 200", "prefers-reduced-motion", "modale centrée", "screenshots", "trace Playwright", "dashboard", "clavier matériel", "sans perte de contenu", "note des limites"], ["mobile-a11y", "responsive-audit"]),
      quiz("a11y-mobile-quiz", ["Quiz : mobile accessible", "Quiz: accessible mobile"], [["Pourquoi tester à 430px ?", "Why test at 430px?", "pour couvrir un grand iPhone réel", "pour ignorer desktop", "pour supprimer CSS", "pour couvrir un grand iPhone réel"], ["Le zoom 200 % exige…", "200% zoom requires…", "pas de perte de contenu ni scroll horizontal fragile", "une police plus petite", "désactiver les labels", "pas de perte de contenu ni scroll horizontal fragile"], ["prefers-reduced-motion sert à…", "prefers-reduced-motion is for…", "réduire les mouvements non essentiels", "bloquer le clavier", "changer la langue", "réduire les mouvements non essentiels"]])
    ]),
    mod("a11y-wcag-remediation", ["WCAG, priorisation et preuve", "WCAG, prioritization, and evidence"], [v.wcag, v.assistive, v.tree], [
      text("a11y-wcag-map", ["Mapper un défaut à WCAG", "Map a defect to WCAG"], ["Relie chaque défaut à critère, impact, preuve et correction.", "Connect each defect to criterion, impact, evidence, and fix."], ["critère WCAG", "impact utilisateur", "étapes de reproduction", "preuve automatisée", "preuve manuelle", "correction proposée"], ["wcag-mapping", "remediation"]),
      text("a11y-prioritize", ["Prioriser les corrections", "Prioritize fixes"], ["Classe les défauts par blocage, fréquence, effort et risque de régression.", "Rank defects by blocking severity, frequency, effort, and regression risk."], ["bloquant", "fréquent", "faible effort", "risque sécurité", "régression probable", "propriétaire nommé"], ["a11y-prioritization", "risk-assessment"]),
      text("a11y-evidence-pack", ["Constituer un pack de preuve", "Build an evidence pack"], ["Regroupe axe, clavier, lecteur d'écran, contraste et captures avant/après.", "Group axe, keyboard, screen reader, contrast, and before/after screenshots."], ["axe report", "parcours clavier", "lecteur d'écran", "contraste mesuré", "captures avant/après", "URL et commit"], ["evidence-pack", "audit-documentation"]),
      project("a11y-final-audit", ["Projet : audit WCAG reproductible", "Project: reproducible WCAG audit"], ["Livre une matrice complète exigence → preuve pour une page critique.", "Ship a complete requirement → evidence matrix for a critical page."], "# Audit WCAG reproductible\n\n| Défaut | Critère | Impact | Preuve | Correction | Retest |\n| --- | --- | --- | --- | --- | --- |\n| bouton sans nom | 4.1.2 | lecteur d'écran bloqué | arbre accessible | aria-label | VoiceOver OK |\n| focus invisible | 2.4.7 | clavier bloqué | parcours Tab | :focus-visible | Playwright OK |\n| contraste faible | 1.4.3 | lecture difficile | ratio mesuré | couleur corrigée | ratio 4.5:1 |\n\n## Pack\n- axe report\n- captures mobile/desktop\n- script lecteur d'écran\n- commit et URL de retest", ["Audit WCAG reproductible", "Critère", "Impact", "Preuve", "Correction", "Retest", "4.1.2", "2.4.7", "1.4.3", "aria-label", "focus-visible", "4.5:1", "axe report", "script lecteur d'écran", "URL de retest", "VoiceOver OK", "Playwright OK", "captures mobile/desktop", "commit"], ["wcag-audit", "evidence-pack"]),
      quiz("a11y-final-exam", ["Examen : audit accessibilité v9", "Exam: accessibility audit v9"], [["Une preuve reproductible contient…", "Reproducible evidence contains…", "étapes, environnement, attendu et observé", "un avis rapide", "une couleur de priorité", "étapes, environnement, attendu et observé"], ["Un défaut bloquant clavier doit être…", "A keyboard-blocking defect should be…", "prioritaire", "ignoré si joli", "corrigé après SEO uniquement", "prioritaire"], ["Un audit complet combine…", "A complete audit combines…", "outils automatiques et tests humains", "axe seulement", "CSS seulement", "outils automatiques et tests humains"]], "exam", 80)
    ])
  ]
};

export const accessibilityModules = track.modules;

function mod(id, title, vocabulary, lessons) {
  return { id, title, description: [`Prouver ${title[0]} avec un scénario utilisateur, des corrections et des tests.`, `Prove ${title[1]} with a user scenario, fixes, and tests.`], vocabulary, lessons };
}

function html(id, title, brief, solution, requirements, skills) {
  return { id, type: "html", title, brief, solution, requirements, skills, vocabulary: [v.name, v.tree, v.assistive], starterCode: "<main>\n  <!-- Corrige le composant accessible ici -->\n</main>" };
}

function css(id, title, brief, solution, requirements, skills) {
  return { id, type: "css", title, brief, solution, requirements, skills, vocabulary: [v.target, v.motion, v.wcag], starterCode: "/* Corrige le comportement accessible ici */" };
}

function text(id, title, brief, requirements, skills) {
  return { id, type: "text", title, brief, solution: requirements.map((item) => `- ${item}`).join("\n"), requirements, skills, vocabulary: [v.wcag, v.assistive, v.tree] };
}

function project(id, title, brief, solution, requirements, skills) {
  return { id, project: true, exerciseType: solution.trim().startsWith("<") ? "html" : "text", title, brief, solution, requirements, skills, vocabulary: [v.wcag, v.assistive, v.tree], durationMin: 120, xp: 95 };
}

function quiz(id, title, rows, purpose = "module-review", passingScore = 75) {
  return { id, type: "quiz", title, purpose, passingScore, durationMin: 22, xp: purpose === "exam" ? 100 : 35, brief: ["Choisis la correction qui aide réellement l'utilisateur.", "Choose the fix that genuinely helps the user."], questions: rows.map(([fr, en, a, b, c, answer], index) => q(`${id}-${index + 1}`, [fr, en], [a, b, c], answer)) };
}

function q(id, prompt, options, answer) {
  return { id, type: "single", prompt: { fr: prompt[0], en: prompt[1] }, choices: options.map((option) => ({ id: option, label: { fr: option, en: option } })), answer, explanation: { fr: "La bonne réponse s'appuie sur une preuve d'usage : clavier, annonce, contraste, focus ou capacité à terminer la tâche.", en: "The correct answer relies on usage evidence: keyboard, announcement, contrast, focus, or ability to complete the task." }, skills: ["accessibility-audit"], requiresRationale: false };
}
