const t = {
  shell: ["script shell", "shell script", "Script terminal automatisant une tâche avec erreurs contrôlées.", "Terminal script automating a task with controlled failures."],
  lockfile: ["lockfile", "lockfile", "Fichier verrouillant l’arbre exact des dépendances installées.", "File locking the exact installed dependency tree."],
  sbom: ["SBOM", "SBOM", "Inventaire des composants logiciels livrés dans un artefact.", "Inventory of software components shipped in an artifact."],
  secret: ["secret", "secret", "Valeur sensible stockée hors code et injectée uniquement au bon runtime.", "Sensitive value stored outside code and injected only into the right runtime."],
  iac: ["infrastructure as code", "infrastructure as code", "Configuration d’infrastructure versionnée, revue et appliquée automatiquement.", "Versioned, reviewed, and automatically applied infrastructure configuration."],
  preview: ["preview environment", "preview environment", "Environnement éphémère isolé pour valider une branche avant production.", "Ephemeral isolated environment to validate a branch before production."],
  incident: ["incident", "incident", "Dégradation utilisateur demandant diagnostic, communication et action coordonnée.", "User-impacting degradation requiring diagnosis, communication, and coordinated action."]
};

export const devopsDeploymentModules = [
  {
    id: "ops-scripts-supply-chain",
    title: ["Scripts, npm et supply-chain", "Scripts, npm, and supply chain"],
    description: ["Automatiser sans magie : commandes idempotentes, dépendances vérifiées et artefacts traçables.", "Automate without magic: idempotent commands, verified dependencies, and traceable artifacts."],
    vocabulary: [t.shell, t.lockfile, t.sbom],
    lessons: [
      terminal("ops-script-safe", ["Écrire un script de release sûr", "Write a safe release script"], ["Arrête le script dès qu’une commande critique échoue et journalise les étapes.", "Stop the script as soon as a critical command fails and log the steps."], "$ErrorActionPreference = 'Stop'\n$release = git rev-parse --short HEAD\nWrite-Output \"release=$release\"\nnpm ci\nnpm run validate\nnpm run audit:curriculum-depth\nnpm run build\nnpm run audit:bundle\nCompress-Archive -Path dist -DestinationPath \"artifacts/pulsateach-$release.zip\" -Force\nGet-FileHash \"artifacts/pulsateach-$release.zip\" -Algorithm SHA256", ["$ErrorActionPreference = 'Stop'", "git rev-parse --short HEAD", "npm ci", "npm run validate", "audit:curriculum-depth", "Compress-Archive", "Get-FileHash", "SHA256"], ["release-scripting", "artifact-provenance"], [t.shell, t.sbom]),
      terminal("ops-npm-audit", ["Auditer les dépendances", "Audit dependencies"], ["Combine audit, outdated contrôlé et justification des exceptions.", "Combine audit, controlled outdated review, and exception justification."], "npm ci\nnpm audit --audit-level=high\nnpm outdated --long\nnpm ls --omit=dev\nnode scripts/audit-bundle.mjs\n\n# Politique\n# - fail sur vulnérabilité high/critical exploitable\n# - issue documentée si upgrade breaking\n# - exception datée, propriétaire, mitigation et date d’expiration", ["npm ci", "npm audit --audit-level=high", "npm outdated --long", "npm ls --omit=dev", "audit-bundle", "exception datée", "date d’expiration"], ["dependency-management", "security-auditing"], [t.lockfile, t.sbom]),
      terminal("ops-sbom", ["Produire un inventaire de release", "Produce a release inventory"], ["Génère un manifeste lisible pour savoir exactement ce qui part en production.", "Generate a readable manifest to know exactly what goes to production."], "node -e \"const p=require('./package-lock.json'); console.log(JSON.stringify({name:p.name, lockfileVersion:p.lockfileVersion, packages:Object.keys(p.packages).length}, null, 2))\" > artifacts/sbom-summary.json\nnpm query ':prod' > artifacts/prod-dependencies.json\ngit diff --name-only HEAD~1..HEAD > artifacts/changed-files.txt\nGet-FileHash package-lock.json -Algorithm SHA256 > artifacts/package-lock.sha256", ["package-lock.json", "sbom-summary.json", "npm query ':prod'", "prod-dependencies.json", "changed-files.txt", "package-lock.sha256"], ["sbom", "release-audit"], [t.sbom, t.lockfile]),
      project("ops-supply-chain-project", ["Lab : dossier de release vérifiable", "Lab: verifiable release dossier"], ["Livre un dossier prouvant versions, dépendances, validations et risques résiduels.", "Ship a dossier proving versions, dependencies, validations, and residual risks."], "# Dossier de release\n\n## Identité\n- commit: 7f303f8\n- branche: codex/platform-roadmap-release\n- environnement cible: production\n\n## Validation\n- npm ci depuis package-lock.json\n- lint, tests, audits, build, E2E, Lighthouse\n- bundle budget respecté\n\n## Supply-chain\n- npm audit high/critical: 0\n- package-lock SHA256 conservé\n- dépendances prod inventoriées\n- exceptions: aucune\n\n## Artefacts\n- dist hashé\n- sitemap généré\n- changelog utilisateur\n\n## Risques\n- migrations: aucune sur ce lot\n- rollback: redéployer artefact précédent\n- smoke: sitemap, catalogue, nouvelle leçon", ["commit:", "npm ci", "lint, tests, audits", "npm audit", "SHA256", "dépendances prod", "sitemap généré", "rollback", "smoke"], ["release-dossier", "supply-chain-security"], [t.sbom, t.lockfile]),
      quiz("ops-supply-chain-quiz", ["Quiz : supply-chain", "Quiz: supply chain"], [
        q("s1", ["Pourquoi conserver le lockfile ?", "Why keep the lockfile?"], [["Pour reproduire l’arbre exact des dépendances", "To reproduce the exact dependency tree"], ["Pour stocker les secrets", "To store secrets"], ["Pour remplacer les tests", "To replace tests"]], "Pour reproduire l’arbre exact des dépendances", ["Sans lockfile, deux builds peuvent installer des versions différentes.", "Without a lockfile, two builds can install different versions."], ["dependency-management"]),
        q("s2", ["Que doit expliquer une exception sécurité ?", "What must a security exception explain?"], [["Risque, mitigation, propriétaire et expiration", "Risk, mitigation, owner, and expiration"], ["Seulement “plus tard”", "Only “later”"], ["Le logo du site", "The site logo"]], "Risque, mitigation, propriétaire et expiration", ["Une exception permanente devient une dette invisible.", "A permanent exception becomes invisible debt."], ["security-auditing"]),
        q("s3", ["À quoi sert un dossier de release ?", "What is a release dossier for?"], [["Prouver ce qui a été livré et validé", "Prove what was shipped and validated"], ["Décorer le README", "Decorate the README"], ["Rendre le build aléatoire", "Make the build random"]], "Prouver ce qui a été livré et validé", ["Il accélère audit, rollback et diagnostic.", "It speeds audit, rollback, and diagnosis."], ["release-dossier"])
      ])
    ]
  },
  {
    id: "ops-secrets-infra",
    title: ["Secrets, previews et infrastructure", "Secrets, previews, and infrastructure"],
    description: ["Décrire l’infrastructure et isoler preview/production pour éviter les surprises dangereuses.", "Describe infrastructure and isolate preview/production to avoid dangerous surprises."],
    vocabulary: [t.secret, t.iac, t.preview],
    lessons: [
      code("ops-env-schema", ["Valider les variables au démarrage", "Validate environment variables at startup"], ["Échoue vite si un secret manque ou si un mode local fuit en production.", "Fail fast if a secret is missing or a local mode leaks into production."], "const schema = {\n  NODE_ENV: ['development', 'test', 'production'],\n  PULSATEACH_STORAGE: ['local', 'supabase-strict'],\n  SUPABASE_URL: 'url',\n  SUPABASE_SERVICE_ROLE_KEY: 'server-secret'\n};\n\nexport function validateRuntimeEnv(env) {\n  if (env.NODE_ENV === 'production' && env.PULSATEACH_STORAGE !== 'supabase-strict') {\n    throw new Error('Production must use supabase-strict storage');\n  }\n  if (env.VITE_SUPABASE_SERVICE_ROLE_KEY) throw new Error('Service role key must never be exposed to Vite');\n  return parseEnv(schema, env);\n}", ["NODE_ENV", "PULSATEACH_STORAGE", "supabase-strict", "validateRuntimeEnv", "throw new Error", "VITE_SUPABASE_SERVICE_ROLE_KEY", "parseEnv"], ["environment-validation", "secret-management"], [t.secret]),
      terminal("ops-preview", ["Créer une preview isolée", "Create an isolated preview"], ["Chaque branche a ses secrets, sa base et son domaine ; aucune donnée prod ne fuit.", "Each branch has its secrets, database, and domain; no production data leaks."], "vercel env pull .env.preview.local --environment=preview\nnpm ci\nnpm run validate\nnpm run build\nnpx vercel deploy --archive=tgz\n\n# Checklist preview\n# - base dédiée ou anonymisée\n# - clés limitées à preview\n# - CORS preview uniquement\n# - bannière environnement visible\n# - suppression automatique après merge", ["vercel env pull", "--environment=preview", "npm run validate", "vercel deploy", "base dédiée", "clés limitées", "CORS preview", "bannière environnement", "suppression automatique"], ["preview-environments", "environment-isolation"], [t.preview, t.secret]),
      code("ops-iac", ["Versionner la configuration plateforme", "Version platform configuration"], ["Déclare headers, redirects, cron et limites dans des fichiers relus en PR.", "Declare headers, redirects, cron, and limits in files reviewed in PRs."], "{\n  \"headers\": [\n    { \"source\": \"/(.*)\", \"headers\": [{ \"key\": \"X-Frame-Options\", \"value\": \"DENY\" }] },\n    { \"source\": \"/assets/(.*)\", \"headers\": [{ \"key\": \"Cache-Control\", \"value\": \"public, max-age=31536000, immutable\" }] }\n  ],\n  \"rewrites\": [{ \"source\": \"/api/(.*)\", \"destination\": \"/api/index.js\" }],\n  \"crons\": [{ \"path\": \"/api/jobs/recompute-sitemap\", \"schedule\": \"0 3 * * *\" }]\n}", ["headers", "X-Frame-Options", "Cache-Control", "immutable", "rewrites", "/api/(.*)", "crons", "schedule"], ["infrastructure-as-code", "platform-configuration"], [t.iac]),
      project("ops-infra-project", ["Lab : plan d’infrastructure PulsaTeach", "Lab: PulsaTeach infrastructure plan"], ["Documente prod, preview, secrets, domaines, headers et procédure de rotation.", "Document production, preview, secrets, domains, headers, and rotation procedure."], "# Plan infrastructure\n\n## Production\n- domaine canonique: https://pulsateach.vercel.app\n- stockage: Supabase strict\n- API: rate limiting, CORS exact, CSP\n- logs: pas de secrets, requestId obligatoire\n\n## Preview\n- domaine généré par branche\n- base dédiée ou données anonymisées\n- cookies séparés\n- suppression après merge\n\n## Secrets\n- service role serveur uniquement\n- rotation trimestrielle ou incident\n- accès limité aux mainteneurs\n- aucune variable VITE_ sensible\n\n## IaC\n- headers sécurité versionnés\n- redirects et canonical relus en PR\n- cache assets immutable\n\n## Vérification\n- health ready\n- route privée 401 sans token\n- accès croisé 403\n- sitemap 200", ["Production", "Supabase strict", "CORS exact", "Preview", "base dédiée", "service role serveur uniquement", "aucune variable VITE_", "headers sécurité", "health ready", "accès croisé 403"], ["infrastructure-planning", "secret-management", "preview-environments"], [t.iac, t.preview, t.secret]),
      quiz("ops-infra-quiz", ["Quiz : secrets et infrastructure", "Quiz: secrets and infrastructure"], [
        q("i1", ["Où placer une clé service Supabase ?", "Where should a Supabase service key live?"], [["Dans le runtime serveur seulement", "Only in the server runtime"], ["Dans import.meta.env.VITE_*", "In import.meta.env.VITE_*"], ["Dans le HTML", "In HTML"]], "Dans le runtime serveur seulement", ["Tout VITE_* est potentiellement livré au navigateur.", "Anything VITE_* can be shipped to the browser."], ["secret-management"]),
        q("i2", ["Pourquoi une preview isolée ?", "Why isolate preview?"], [["Tester sans toucher aux données et secrets production", "Test without touching production data and secrets"], ["Avoir une URL plus longue", "To have a longer URL"], ["Ignorer la CI", "To ignore CI"]], "Tester sans toucher aux données et secrets production", ["Une branche expérimentale ne doit pas modifier le vrai service.", "An experimental branch must not modify the real service."], ["preview-environments"]),
        q("i3", ["Pourquoi versionner les headers ?", "Why version headers?"], [["Pour relire et tester la sécurité comme du code", "To review and test security as code"], ["Pour réduire le HTML", "To reduce HTML"], ["Pour cacher les erreurs", "To hide errors"]], "Pour relire et tester la sécurité comme du code", ["La configuration plateforme fait partie du produit.", "Platform configuration is part of the product."], ["infrastructure-as-code"])
      ])
    ]
  },
  {
    id: "ops-incident-continuity",
    title: ["Incidents, continuité et amélioration", "Incidents, continuity, and improvement"],
    description: ["Savoir quoi faire quand une release dégrade l’expérience, puis améliorer le système.", "Know what to do when a release degrades experience, then improve the system."],
    vocabulary: [t.incident],
    lessons: [
      text("ops-incident-triage", ["Trier un incident production", "Triage a production incident"], ["Détermine impact, sévérité, owner, canal et première action dans les dix minutes.", "Determine impact, severity, owner, channel, and first action within ten minutes."], ["Impact utilisateur estimé", "Routes ou fonctionnalités touchées", "Dernier déploiement et changements", "Métriques 5xx, latence, Web Vitals", "Décision rollback, mitigation ou observation", "Message de statut si impact externe", "Chronologie ouverte dès le début"], ["incident-triage", "operations-communication"], [t.incident]),
      terminal("ops-smoke-pack", ["Écrire un pack smoke post-release", "Write a post-release smoke pack"], ["Vérifie les chemins utilisateur critiques en moins de deux minutes.", "Verify critical user paths in under two minutes."], "$base = 'https://pulsateach.vercel.app'\n$checks = @('/','/catalog','/sitemap.xml','/legal/mentions-legales','/learn/web-performance/perf-diagnostics/perf-diagnostics-map')\nforeach ($path in $checks) {\n  $response = Invoke-WebRequest -Uri \"$base$path\" -UseBasicParsing -MaximumRedirection 5\n  if ($response.StatusCode -ne 200) { throw \"Smoke failed: $path\" }\n}\nWrite-Output 'public smoke ok'\n# API/auth smoke: 401 sans token, 403 inter-utilisateur, sauvegarde progression authentifiée", ["$base", "$checks", "Invoke-WebRequest", "StatusCode -ne 200", "throw", "public smoke ok", "401 sans token", "403 inter-utilisateur"], ["smoke-testing", "release-verification"], [t.incident]),
      text("ops-postmortem", ["Faire un post-mortem utile", "Run a useful postmortem"], ["Améliore le système sans chercher un coupable.", "Improve the system without looking for a scapegoat."], ["Résumé et impact utilisateur", "Timeline factuelle", "Ce qui a détecté, ce qui a manqué", "Cause technique et facteurs organisationnels", "Actions préventives avec propriétaire/date", "Tests ou alertes ajoutés", "Communication des apprentissages"], ["postmortem", "continuous-improvement"], [t.incident]),
      project("ops-continuity-project", ["Lab : drill incident complet", "Lab: full incident drill"], ["Simule une dégradation, choisis mitigation/rollback et produis le post-mortem.", "Simulate a degradation, choose mitigation/rollback, and produce the postmortem."], "# Drill incident\n\n## Scénario\n- nouvelle release: catalogue charge en 6 s sur mobile\n- alerte: p75 LCP > 2500 ms, samples 180\n- impact: nouveaux visiteurs et SEO\n\n## Triage\n- comparer déploiement précédent\n- vérifier chunk initial et image LCP\n- confirmer API catalogue 200 mais payload augmenté\n\n## Action\n- désactiver expérimentation visuelle via feature flag\n- si LCP reste mauvais: rollback artefact précédent\n- smoke public + SEO + parcours leçon\n\n## Communication\n- note interne: impact, mitigation, ETA\n- pas de détail technique inutile côté public\n\n## Post-mortem\n- budget image absent du gate\n- ajouter audit image et alerte LCP par route\n- propriétaire: ops/content\n- échéance: prochaine release", ["Scénario", "p75 LCP", "Triage", "chunk initial", "feature flag", "rollback artefact précédent", "smoke public", "Communication", "Post-mortem", "budget image absent"], ["incident-drill", "rollback-strategy", "postmortem"], [t.incident]),
      quiz("ops-incident-quiz", ["Quiz : incidents", "Quiz: incidents"], [
        q("p1", ["Quelle première information manque rarement ?", "Which first information is rarely optional?"], [["Impact utilisateur réel ou estimé", "Real or estimated user impact"], ["La couleur du bouton", "Button color"], ["Le nombre de fichiers CSS", "Number of CSS files"]], "Impact utilisateur réel ou estimé", ["La sévérité dépend de l’utilisateur touché, pas seulement du log.", "Severity depends on affected users, not only logs."], ["incident-triage"]),
        q("p2", ["Pourquoi ouvrir une timeline tôt ?", "Why open a timeline early?"], [["Pour conserver les faits pendant l’action", "To preserve facts during action"], ["Pour ralentir l’équipe", "To slow the team"], ["Pour remplacer les alertes", "To replace alerts"]], "Pour conserver les faits pendant l’action", ["La mémoire est mauvaise quand la pression monte.", "Memory is poor when pressure rises."], ["incident-triage"]),
        q("p3", ["Un bon post-mortem produit quoi ?", "What does a good postmortem produce?"], [["Des actions préventives vérifiables", "Verifiable preventive actions"], ["Un coupable", "A culprit"], ["Une suppression de logs", "Log deletion"]], "Des actions préventives vérifiables", ["Le but est de rendre la prochaine panne moins probable ou moins longue.", "The goal is making the next failure less likely or shorter."], ["continuous-improvement"])
      ])
    ]
  }
];

function terminal(id, title, brief, solution, requirements, skills, vocabulary) {
  return practice({ id, type: "terminal", title, brief, solution, requirements, skills, vocabulary });
}

function code(id, title, brief, solution, requirements, skills, vocabulary) {
  return practice({ id, type: "node", title, brief, solution, requirements, skills, vocabulary });
}

function text(id, title, brief, requirements, skills, vocabulary) {
  return practice({ id, type: "text", title, brief, solution: requirements.map((item) => `- ${item}`).join("\n"), requirements, skills, vocabulary });
}

function project(id, title, brief, solution, requirements, skills, vocabulary) {
  return { ...practice({ id, title, brief, solution, requirements, skills, vocabulary }), project: true, exerciseType: "text", durationMin: 130, xp: 100 };
}

function practice(spec) {
  const enRequirements = spec.requirements.map((item, index) => frenchOnly(item) ? `evidence: ${spec.skills[index % spec.skills.length]}` : item);
  return { ...spec, starterCode: { fr: "# Documente les commandes et les preuves", en: "# Document commands and evidence" }, solution: { fr: spec.solution, en: frenchOnly(spec.solution) ? `# ${spec.title[1]}\n\n${spec.brief[1]}\n\n## Evidence\n${enRequirements.map((item) => `- ${item}`).join("\n")}` : spec.solution }, requirements: spec.requirements.map((item, index) => ({ type: "contains", label: { fr: `La preuve « ${item} » est présente`, en: `Evidence “${enRequirements[index]}” is present` }, value: frenchOnly(item) ? { fr: item, en: enRequirements[index] } : item })) };
}

function frenchOnly(value) {
  return /[àâçéèêëîïôùûüœ]|\b(?:politique|exception datée|dossier|branche|environnement|dépendances|scénario|déploiement|propriétaire)\b/i.test(String(value));
}

function quiz(id, title, questions, purpose = "module-review", passingScore = 75) {
  return { id, type: "quiz", title, questions, purpose, passingScore, brief: ["Choisis la décision qui rend la livraison sûre, traçable et récupérable.", "Choose the decision that makes delivery safe, traceable, and recoverable."] };
}

function q(id, prompt, options, answer, explanation, skills) {
  return { id, type: "single", prompt, choices: options.map((option) => ({ id: option[0], label: option })), answer, explanation, points: 1, skills, glossaryTerms: [] };
}
