import { createProfessionalTrack } from "../builders/createProfessionalTrack.js";

const v = {
  reflog: ["reflog", "reflog", "Journal local des déplacements de HEAD et des références.", "Local log of HEAD and reference movements."],
  stash: ["stash", "stash", "Pile locale de changements mis temporairement de côté.", "Local stack of changes temporarily set aside."],
  rebase: ["rebase", "rebase", "Réécriture contrôlée d'une branche au-dessus d'une nouvelle base.", "Controlled replay of a branch on a new base."],
  bisect: ["bisect", "bisect", "Recherche dichotomique du commit qui a introduit une régression.", "Binary search for the commit that introduced a regression."],
  tag: ["tag", "tag", "Nom stable attaché à un commit important, souvent une version.", "Stable name attached to an important commit, often a release."],
  pr: ["pull request", "pull request", "Discussion vérifiable autour d'une proposition de changement.", "Verifiable discussion around a proposed change."],
  hook: ["hook Git", "Git hook", "Script déclenché par Git à un moment précis du workflow.", "Script triggered by Git at a precise workflow moment."],
  provenance: ["provenance", "provenance", "Preuves reliant une version à son code, ses tests et ses artefacts.", "Evidence connecting a version to code, tests, and artifacts."]
};

const track = createProfessionalTrack({
  id: "git",
  label: "GIT",
  title: ["Git et GitHub", "Git and GitHub"],
  summary: ["Versionner, relire, restaurer, collaborer et livrer un projet sans perdre de travail.", "Version, review, restore, collaborate, and ship a project without losing work."],
  profession: ["Git est la boîte noire d'un produit : il explique ce qui a changé, pourquoi, par qui et avec quelles preuves.", "Git is a product's black box: it explains what changed, why, by whom, and with which evidence."],
  prerequisites: [["Savoir utiliser le terminal", "Know the terminal"], ["Avoir créé quelques commits", "Have created a few commits"]],
  outcomes: [["Construire un historique lisible", "Build readable history"], ["Restaurer un état sûr", "Restore a safe state"], ["Préparer des PR vérifiables", "Prepare verifiable PRs"], ["Livrer avec tags et CI", "Ship with tags and CI"]],
  capstone: ["Dépôt portfolio traçable avec PR, tag, changelog, CI et runbook de récupération.", "Traceable portfolio repository with PR, tag, changelog, CI, and recovery runbook."],
  certification: [["Valider les labs Git v9", "Pass Git v9 labs"], ["Réussir l'examen Git", "Pass the Git exam"]],
  modules: [
    mod("git-safe-history", ["Historique sûr et restaurable", "Safe and restorable history"], [v.reflog, v.stash, v.provenance], [
      term("git-status-matrix", ["Construire une matrice d'état", "Build a status matrix"], ["Lis branche, index, working tree et commits récents avant d'agir.", "Read branch, staging area, working tree, and recent commits before acting."], "git status --short\ngit branch --show-current\ngit diff --stat\ngit diff --staged --stat\ngit log --oneline -5\ngit remote -v", ["git status --short", "git branch --show-current", "git diff --stat", "git diff --staged", "git log --oneline -5", "git remote -v", "working tree", "index", "branche", "preuve"], ["git-safety", "status-reading"]),
      term("git-stash-safely", ["Mettre de côté sans perdre", "Set work aside without losing it"], ["Range un travail incomplet avec message, vérifie la pile puis restaure-le proprement.", "Store incomplete work with a message, inspect the stack, then restore it cleanly."], "git status --short\ngit stash push -m \"wip: mobile quiz layout\"\ngit stash list\ngit stash show --stat stash@{0}\ngit switch main\ngit stash pop\ngit status --short", ["git stash push -m", "wip: mobile quiz layout", "git stash list", "git stash show --stat", "stash@{0}", "git switch main", "git stash pop", "git status --short", "message", "restaure"], ["stash", "work-in-progress"]),
      term("git-reflog-recover", ["Récupérer un commit perdu", "Recover a lost commit"], ["Utilise reflog pour retrouver un commit après un déplacement de branche.", "Use reflog to find a commit after a branch move."], "git reflog --date=iso\ngit show --stat HEAD@{1}\ngit switch -c recovery/lost-work HEAD@{1}\ngit log --oneline --decorate -3\ngit status --short", ["git reflog", "--date=iso", "git show --stat", "HEAD@{1}", "git switch -c recovery/lost-work", "git log --oneline --decorate", "git status --short", "recovery", "lost-work", "HEAD"], ["reflog", "recovery"]),
      project("git-recovery-lab", ["Lab : runbook anti-panique", "Lab: anti-panic runbook"], ["Écris un runbook pour sauver un travail après reset, mauvais checkout ou stash oublié.", "Write a runbook to save work after reset, wrong checkout, or forgotten stash."], "# Runbook récupération Git\n\n## Diagnostic\n- git status --short\n- git branch --show-current\n- git reflog --date=iso\n- git stash list\n\n## Scénarios\n1. reset accidentel : retrouver HEAD@{n}, créer recovery/lost-work\n2. checkout mauvais : vérifier diff et revenir sur la bonne branche\n3. stash oublié : git stash show puis git stash branch recovery/stash\n4. commit à conserver : tag temporaire rescue/<date>\n\n## Preuves\n- aucune commande destructive sans branche de secours\n- log --oneline --decorate avant/après\n- résumé des fichiers récupérés\n- prochaine action validée par status propre", ["Runbook récupération", "git status --short", "git branch --show-current", "git reflog --date=iso", "git stash list", "reset accidentel", "recovery/lost-work", "git stash branch", "tag temporaire", "aucune commande destructive", "log --oneline --decorate", "status propre"], ["git-recovery", "runbook"]),
      quiz("git-safe-history-quiz", ["Quiz : récupérer sans casser", "Quiz: recover without breaking"], [["Quel réflexe vient avant reset --hard ?", "What comes before reset --hard?", "Créer une branche ou tag de secours", "Forcer directement", "Supprimer .git", "Créer une branche ou tag de secours"], ["À quoi sert reflog ?", "What is reflog for?", "Retrouver les déplacements locaux de HEAD", "Publier une PR", "Installer Node", "Retrouver les déplacements locaux de HEAD"], ["Pourquoi nommer un stash ?", "Why name a stash?", "Comprendre ce qui est mis de côté", "Augmenter le bundle", "Remplacer un commit", "Comprendre ce qui est mis de côté"]])
    ]),
    mod("git-branch-surgery", ["Branches, rebase et diagnostic", "Branches, rebase, and diagnosis"], [v.rebase, v.bisect, v.stash], [
      term("git-rebase-linear", ["Rejouer une branche proprement", "Replay a branch cleanly"], ["Mets une branche à jour sur main avec un rebase explicite et vérifiable.", "Update a branch on main with explicit, verifiable rebase."], "git fetch origin\ngit switch feature/catalog-search\ngit rebase origin/main\ngit status --short\ngit log --oneline --graph --decorate -8\ngit push --force-with-lease", ["git fetch origin", "git switch feature/catalog-search", "git rebase origin/main", "git status --short", "git log --oneline --graph", "--decorate", "git push --force-with-lease", "origin/main", "feature/catalog-search", "lease"], ["rebase", "branch-maintenance"]),
      term("git-cherry-pick", ["Isoler un correctif", "Isolate a fix"], ["Récupère un commit ciblé sans embarquer toute la branche expérimentale.", "Bring a targeted commit without taking the whole experimental branch."], "git switch main\ngit log --oneline experiment/ui\ngit cherry-pick abc1234\ngit show --stat --oneline HEAD\ngit status --short\ngit branch --contains HEAD", ["git switch main", "git log --oneline", "experiment/ui", "git cherry-pick", "abc1234", "git show --stat", "git status --short", "git branch --contains", "correctif", "isolé"], ["cherry-pick", "hotfix"]),
      term("git-bisect", ["Trouver le commit fautif", "Find the faulty commit"], ["Lance bisect avec un test reproductible pour localiser une régression.", "Run bisect with a reproducible test to locate a regression."], "git bisect start\ngit bisect bad HEAD\ngit bisect good v1.2.0\ngit bisect run npm test -- quizEngine.test.js\ngit show --stat\ngit bisect reset", ["git bisect start", "git bisect bad", "git bisect good", "v1.2.0", "git bisect run", "npm test", "quizEngine.test.js", "git show --stat", "git bisect reset", "régression"], ["bisect", "regression-debugging"]),
      project("git-branch-lab", ["Lab : chirurgie de branche", "Lab: branch surgery"], ["Documente quand choisir merge, rebase, cherry-pick ou revert sur un incident réel.", "Document when to choose merge, rebase, cherry-pick, or revert on a real incident."], "# Chirurgie de branche\n\n## Situation\nUne branche feature casse le quiz mobile, mais un commit corrige aussi un bug critique.\n\n## Décision\n- rebase pour mettre à jour une branche privée\n- cherry-pick pour extraire le correctif critique\n- revert pour annuler une livraison déjà partagée\n- merge pour conserver l'historique d'une PR publique\n\n## Commandes prouvées\n- git fetch origin\n- git rebase origin/main\n- git cherry-pick <sha>\n- git revert <sha>\n- git log --graph --decorate\n- git push --force-with-lease uniquement branche privée\n\n## Critères\n- aucune réécriture de branche partagée sans accord\n- test reproductible avant/après\n- plan de rollback écrit", ["Chirurgie de branche", "rebase", "cherry-pick", "revert", "merge", "git fetch origin", "git rebase origin/main", "git cherry-pick", "git revert", "git log --graph --decorate", "force-with-lease", "branche privée", "test reproductible", "rollback"], ["branch-surgery", "incident-response"]),
      quiz("git-branch-surgery-quiz", ["Quiz : choisir l'opération", "Quiz: choose the operation"], [["Quelle commande annule un commit partagé sans réécrire l'histoire ?", "Which command cancels a shared commit without rewriting history?", "git revert", "git rebase -i", "git init", "git revert"], ["Pourquoi force-with-lease plutôt que force ?", "Why force-with-lease instead of force?", "Il refuse d'écraser un travail distant inattendu", "Il ignore les tests", "Il supprime les tags", "Il refuse d'écraser un travail distant inattendu"], ["Quand utiliser cherry-pick ?", "When use cherry-pick?", "Pour extraire un commit précis", "Pour cloner un dépôt", "Pour afficher les remotes", "Pour extraire un commit précis"]])
    ]),
    mod("git-review-collaboration", ["Review, PR et qualité collaborative", "Review, PR, and collaboration quality"], [v.pr, v.hook, v.provenance], [
      term("git-commit-series", ["Découper une série de commits", "Split a commit series"], ["Prépare trois commits relisibles : structure, comportement, tests.", "Prepare three reviewable commits: structure, behavior, tests."], "git add src/catalog/SearchBox.jsx\ngit commit -m \"feat: add catalog search box\"\ngit add src/catalog/filterCourses.js\ngit commit -m \"feat: filter catalog by query\"\ngit add tests/e2e/catalog-search.spec.js\ngit commit -m \"test: cover catalog search\"\ngit log --oneline -3", ["git add src/catalog/SearchBox.jsx", "feat: add catalog search box", "filterCourses.js", "feat: filter catalog by query", "tests/e2e/catalog-search.spec.js", "test: cover catalog search", "git log --oneline -3", "structure", "comportement", "tests"], ["commit-series", "reviewability"]),
      term("git-pr-template", ["Préparer une PR vérifiable", "Prepare a verifiable PR"], ["Rédige titre, contexte, captures, tests et risques restants avant review.", "Write title, context, screenshots, tests, and remaining risks before review."], "gh pr create --title \"feat: add catalog search\" --body \"## Pourquoi\nRecherche rapide catalogue\n\n## Tests\n- npm run validate\n- npm run test:e2e -- catalog-search\n\n## Risques\n- accents et synonymes à améliorer\n\n## Captures\n- mobile 430px\n- desktop 1440px\"", ["gh pr create", "--title", "## Pourquoi", "Recherche rapide catalogue", "## Tests", "npm run validate", "test:e2e", "## Risques", "mobile 430px", "desktop 1440px"], ["pull-request", "review-evidence"]),
      term("git-hooks", ["Installer un hook local utile", "Install a useful local hook"], ["Ajoute un pre-commit léger qui bloque secrets évidents et fichiers générés.", "Add a lightweight pre-commit that blocks obvious secrets and generated files."], "mkdir -p .git/hooks\ncat > .git/hooks/pre-commit <<'SH'\n#!/bin/sh\ngit diff --cached --name-only | grep -E '(^dist/|\\.env$)' && exit 1\ngit diff --cached | grep -E 'service_role|SECRET|PRIVATE_KEY' && exit 1\nexit 0\nSH\nchmod +x .git/hooks/pre-commit", ["mkdir -p .git/hooks", "pre-commit", "#!/bin/sh", "git diff --cached --name-only", "dist/", ".env", "service_role", "PRIVATE_KEY", "chmod +x", "exit 0"], ["git-hooks", "secret-prevention"]),
      project("git-review-lab", ["Lab : PR de niveau équipe", "Lab: team-grade PR"], ["Assemble une PR que quelqu'un peut relire vite et tester sans te demander du contexte.", "Assemble a PR someone can review quickly and test without asking you for context."], "# Pull request PulsaTeach\n\n## Contexte\n- problème utilisateur observé\n- issue liée\n- décision retenue\n\n## Série de commits\n1. feat: add catalog search box\n2. feat: filter catalog by query\n3. test: cover catalog search\n4. docs: explain search behavior\n\n## Preuves\n- npm run validate\n- npm run test:e2e -- catalog-search\n- capture mobile 430px\n- capture desktop 1440px\n- aucun secret dans le diff\n\n## Limites\n- recherche exacte uniquement\n- synonymes prévus dans un lot séparé", ["Pull request PulsaTeach", "problème utilisateur", "issue liée", "Série de commits", "feat:", "test:", "docs:", "npm run validate", "test:e2e", "mobile 430px", "desktop 1440px", "aucun secret", "Limites", "lot séparé"], ["pull-request", "team-review"]),
      quiz("git-review-quiz", ["Quiz : PR relisible", "Quiz: reviewable PR"], [["Quel est le meilleur commit ?", "Which is the best commit?", "test: cover catalog search", "update stuff", "final final", "test: cover catalog search"], ["Que doit contenir une PR ?", "What should a PR contain?", "Contexte, tests, risques et captures utiles", "Seulement un emoji", "Aucun test", "Contexte, tests, risques et captures utiles"], ["Pourquoi un hook secret ?", "Why a secret hook?", "Réduire le risque avant push", "Remplacer l'auth", "Publier plus vite sans review", "Réduire le risque avant push"]])
    ]),
    mod("git-release-provenance", ["Tags, releases et provenance", "Tags, releases, and provenance"], [v.tag, v.provenance, v.pr], [
      term("git-annotated-tag", ["Créer un tag annoté", "Create an annotated tag"], ["Marque une version stable avec message, commit vérifié et log décoré.", "Mark a stable version with message, verified commit, and decorated log."], "git status --short\ngit log --oneline -1\ngit tag -a v1.4.0 -m \"PulsaTeach v1.4.0: CSS curriculum depth\"\ngit show v1.4.0 --stat\ngit log --oneline --decorate -3", ["git status --short", "git log --oneline -1", "git tag -a v1.4.0", "PulsaTeach v1.4.0", "git show v1.4.0 --stat", "git log --oneline --decorate", "version stable", "message", "commit vérifié", "tag annoté"], ["release-tags", "versioning"]),
      term("git-changelog", ["Écrire un changelog utile", "Write a useful changelog"], ["Relie changements, preuves, migrations, risques et rollback dans une note de release.", "Connect changes, evidence, migrations, risks, and rollback in a release note."], "## v1.4.0\n\n### Ajouté\n- Parcours CSS renforcé à 525 tests\n\n### Validé\n- npm run validate\n- E2E chromium\n- smoke production\n\n### Risques\n- contenu CSS plus volumineux\n\n### Rollback\n- redéployer le tag v1.3.0\n- vérifier /catalog et /learn/css", ["## v1.4.0", "### Ajouté", "525 tests", "### Validé", "npm run validate", "E2E chromium", "smoke production", "### Risques", "### Rollback", "v1.3.0"], ["changelog", "release-notes"]),
      term("git-signed-evidence", ["Attacher les preuves de livraison", "Attach delivery evidence"], ["Prépare un inventaire reliant commit, tag, build, smoke et URL de production.", "Prepare an inventory connecting commit, tag, build, smoke, and production URL."], "git rev-parse HEAD\ngit describe --tags --always\nnpm run validate\nnpm run smoke:production\nvercel inspect https://pulsateach.vercel.app\nprintf \"commit=%s\\ntag=%s\\nurl=%s\\n\" \"$(git rev-parse HEAD)\" \"$(git describe --tags --always)\" \"https://pulsateach.vercel.app\" > release-evidence.txt", ["git rev-parse HEAD", "git describe --tags --always", "npm run validate", "npm run smoke:production", "vercel inspect", "commit=", "tag=", "url=", "release-evidence.txt", "pulsateach.vercel.app"], ["release-provenance", "deployment-evidence"]),
      project("git-release-lab", ["Projet : release vérifiable", "Project: verifiable release"], ["Livre une release Git complète : tag, changelog, preuves, smoke et rollback.", "Ship a complete Git release: tag, changelog, evidence, smoke, and rollback."], "# Release vérifiable\n\n## Version\n- tag annoté v1.4.0\n- commit source : git rev-parse HEAD\n- changelog lisible par utilisateur et mainteneur\n\n## Preuves\n- npm ci\n- npm run validate\n- audit:curriculum-depth\n- test:e2e chromium\n- audit:lighthouse\n- smoke:production\n\n## Publication\n- URL production\n- inspect Vercel\n- sitemap disponible\n\n## Rollback\n- tag précédent\n- commande de redéploiement\n- smoke minimal après retour arrière", ["Release vérifiable", "tag annoté", "v1.4.0", "git rev-parse HEAD", "changelog", "npm ci", "npm run validate", "audit:curriculum-depth", "test:e2e chromium", "audit:lighthouse", "smoke:production", "URL production", "inspect Vercel", "sitemap", "Rollback", "tag précédent"], ["release-management", "provenance"]),
      quiz("git-release-quiz", ["Quiz : release Git", "Quiz: Git release"], [["Pourquoi un tag annoté ?", "Why an annotated tag?", "Pour documenter une version stable", "Pour effacer les commits", "Pour remplacer les tests", "Pour documenter une version stable"], ["Quelle preuve relie code et prod ?", "Which evidence links code and prod?", "Commit, tag, build, smoke et URL", "Couleur du bouton", "Nom du PC", "Commit, tag, build, smoke et URL"], ["Un bon rollback contient quoi ?", "What does a good rollback contain?", "Version précédente et smoke après retour", "Uniquement une excuse", "Un reset local", "Version précédente et smoke après retour"]], "exam", 80)
    ])
  ]
});

export const gitModules = track.modules;

function mod(id, title, vocabulary, lessons) {
  return { id, title, description: [`Appliquer ${title[0]} avec commandes vérifiables et preuves de collaboration.`, `Apply ${title[1]} with verifiable commands and collaboration evidence.`], vocabulary, lessons };
}

function term(id, title, brief, solution, requirements, skills) {
  return { id, type: "text", runtime: "terminal", title, brief, solution, requirements, skills, vocabulary: [v.reflog, v.stash, v.provenance], durationMin: 35, xp: 40, starterCode: "# Écris les commandes Git et leurs preuves\n" };
}

function project(id, title, brief, solution, requirements, skills) {
  return { id, project: true, exerciseType: "terminal", title, brief, solution, requirements, skills, vocabulary: [v.pr, v.provenance, v.tag], durationMin: 120, xp: 95 };
}

function quiz(id, title, rows, purpose = "module-review", passingScore = 75) {
  return { id, type: "quiz", title, purpose, passingScore, durationMin: 22, xp: purpose === "exam" ? 100 : 35, brief: ["Choisis l'action Git la plus sûre pour le scénario.", "Choose the safest Git action for the scenario."], questions: rows.map(([fr, en, a, b, c, answer], index) => q(`${id}-${index + 1}`, [fr, en], [a, b, c], answer)) };
}

function q(id, prompt, options, answer) {
  return { id, type: "single", prompt: { fr: prompt[0], en: prompt[1] }, choices: options.map((option) => ({ id: option, label: { fr: option, en: option } })), answer, explanation: { fr: "La meilleure réponse protège l'historique, garde une preuve et réduit le risque de perte.", en: "The best answer protects history, keeps evidence, and reduces risk of losing work." }, skills: ["git-safety"], requiresRationale: false };
}
