import { createProfessionalTrack } from "../builders/createProfessionalTrack.js";
import { nodeApiModules } from "./nodeApiModules.js";

const v = {
  runtime: ["runtime", "runtime", "Environnement qui exécute JavaScript hors du navigateur.", "An environment executing JavaScript outside the browser."],
  module: ["module", "module", "Fichier exposant une interface et encapsulant une responsabilité.", "A file exposing an interface and encapsulating a responsibility."],
  middleware: ["middleware", "middleware", "Fonction traitant une requête avant ou après le gestionnaire final.", "A function processing a request before or after the final handler."],
  route: ["route API", "API route", "Contrat associant méthode, chemin, entrée et réponse.", "A contract associating method, path, input, and response."],
  validation: ["validation", "validation", "Vérification explicite de données non fiables à une frontière.", "Explicit checking of untrusted data at a boundary."],
  service: ["service", "service", "Couche portant une règle métier indépendante du transport.", "A layer holding a business rule independent of transport."],
  repository: ["repository", "repository", "Abstraction d’accès et de persistance des données.", "An abstraction for data access and persistence."],
  authentication: ["authentification", "authentication", "Preuve de l’identité d’un acteur.", "Proof of an actor's identity."],
  authorization: ["autorisation", "authorization", "Décision indiquant si une identité peut réaliser une action.", "A decision about whether an identity may perform an action."],
  observability: ["observabilité", "observability", "Capacité à comprendre le système par logs, métriques et traces.", "The ability to understand a system through logs, metrics, and traces."]
};

export const nodeApiTrack = createProfessionalTrack({
  id: "node-api",
  label: "NODE",
  title: ["Node.js et API sécurisées", "Node.js and secure APIs"],
  summary: ["Construis une API Express validée, testée et organisée en contrôleurs, services et repositories.", "Build a validated, tested Express API organized into controllers, services, and repositories."],
  profession: ["Une API fiable ne se résume pas à des routes qui répondent. Elle protège ses frontières, sépare transport et métier, applique l’autorisation côté serveur et fournit les preuves nécessaires pour diagnostiquer un incident.", "A reliable API is more than responding routes. It protects boundaries, separates transport from business logic, enforces authorization server-side, and provides evidence needed to diagnose incidents."],
  prerequisites: [["Maîtriser JavaScript asynchrone", "Know asynchronous JavaScript"], ["Comprendre HTTP et JSON", "Understand HTTP and JSON"], ["Savoir écrire des tests unitaires", "Know how to write unit tests"]],
  outcomes: [["Créer un serveur Node modulaire", "Create a modular Node server"], ["Valider routes et erreurs HTTP", "Validate routes and HTTP errors"], ["Appliquer authentification et autorisation", "Enforce authentication and authorization"], ["Tester et observer une API", "Test and observe an API"]],
  capstone: ["Livrer une API de gestion de projets avec validation, architecture en couches, contrôle d’accès, logs structurés, tests et documentation d’exploitation.", "Ship a project-management API with validation, layered architecture, access control, structured logs, tests, and operations documentation."],
  certification: [["Valider chaque module", "Pass every module"], ["Livrer quatre projets backend", "Ship four backend projects"], ["Réussir l’examen final", "Pass the final exam"], ["Faire approuver les tests de sécurité inter-utilisateurs", "Get cross-user security tests approved"]],
  modules: [
    {
      id: "node-runtime",
      title: ["Runtime, modules et asynchronisme", "Runtime, modules, and async"],
      description: ["Comprendre le processus Node, isoler les modules et gérer les opérations asynchrones sans fuite.", "Understand the Node process, isolate modules, and handle asynchronous operations without leaks."],
      vocabulary: [v.runtime, v.module, ["promesse", "promise", "Objet représentant une opération asynchrone future.", "An object representing a future asynchronous operation."]],
      lessons: [
        nodeLesson("node-01-runtime", ["Comprendre processus et environnement", "Understand process and environment"], ["Lis une configuration sans exposer de secret et refuse les valeurs requises absentes.", "Read configuration without exposing secrets and reject missing required values."], "export function loadConfig(env = process.env) {\n  const port = Number(env.PORT || 4174);\n  const databaseUrl = env.DATABASE_URL;\n  if (!databaseUrl) throw new Error('DATABASE_URL is required');\n  return { port, databaseUrl, environment: env.NODE_ENV || 'development' };\n}", ["process.env", "Number(env.PORT", "DATABASE_URL", "throw new Error", "environment:"], ["node-runtime", "configuration"], [v.runtime, ["variable d’environnement", "environment variable", "Valeur de configuration fournie au processus.", "A configuration value supplied to the process."]]),
        nodeLesson("node-01-modules", ["Définir une frontière de module", "Define a module boundary"], ["Expose une fonction publique et garde le détail de calcul privé.", "Expose a public function and keep calculation details private."], "function normalizeAmount(value) {\n  const amount = Number(value);\n  if (!Number.isFinite(amount) || amount < 0) throw new TypeError('Invalid amount');\n  return Math.round(amount * 100) / 100;\n}\n\nexport function createInvoice(input) {\n  return { id: crypto.randomUUID(), amount: normalizeAmount(input.amount), status: 'draft' };\n}", ["function normalizeAmount", "Number.isFinite", "throw new TypeError", "export function createInvoice", "crypto.randomUUID"], ["module-design", "input-validation"], [v.module, v.validation]),
        nodeLesson("node-01-async", ["Orchestrer plusieurs opérations", "Orchestrate multiple operations"], ["Exécute les lectures indépendantes en parallèle et propage une erreur contextualisée.", "Run independent reads in parallel and propagate a contextual error."], "export async function buildDashboard({ projectRepository, memberRepository }, userId) {\n  try {\n    const [projects, members] = await Promise.all([\n      projectRepository.listForUser(userId),\n      memberRepository.listForUser(userId)\n    ]);\n    return { projects, members };\n  } catch (error) {\n    throw new Error('Unable to build dashboard', { cause: error });\n  }\n}", ["async function buildDashboard", "Promise.all", "listForUser", "catch (error)", "cause: error"], ["async-node", "error-causality"], [v.runtime, v.repository]),
        project("node-01-cli-project", ["Mini-projet : importeur robuste", "Mini-project: robust importer"], ["Construis un module qui lit, valide, importe et résume un fichier sans arrêter silencieusement le processus.", "Build a module that reads, validates, imports, and summarizes a file without silently stopping the process."], "import { readFile } from 'node:fs/promises';\n\nexport async function importProjects(filePath, repository) {\n  const raw = await readFile(filePath, 'utf8');\n  const payload = JSON.parse(raw);\n  if (!Array.isArray(payload)) throw new TypeError('Expected an array');\n  const accepted = [];\n  const rejected = [];\n  for (const [index, item] of payload.entries()) {\n    if (!item || typeof item.name !== 'string') { rejected.push({ index, reason: 'invalid_name' }); continue; }\n    accepted.push(await repository.create({ name: item.name.trim() }));\n  }\n  return { accepted, rejected, total: payload.length };\n}", ["node:fs/promises", "JSON.parse", "Array.isArray", "throw new TypeError", "for (const [index, item]", "repository.create", "accepted", "rejected"], ["file-import", "validation", "repositories"], [v.module, v.validation, v.repository]),
        quiz("node-01-review", ["Quiz : Node et asynchronisme", "Quiz: Node and async"], [
          q("r1", ["Où conserver un secret serveur ?", "Where should a server secret be kept?"], [["Dans une variable d’environnement côté serveur", "In a server-side environment variable"], ["Dans le bundle frontend", "In the frontend bundle"], ["Dans une URL publique", "In a public URL"]], "Dans une variable d’environnement côté serveur", ["Le secret ne doit jamais être livré au navigateur.", "The secret must never be shipped to the browser."], ["configuration"]),
          q("r2", ["Quand utiliser Promise.all ?", "When should Promise.all be used?"], [["Pour des opérations indépendantes pouvant être parallélisées", "For independent operations that can run in parallel"], ["Pour forcer un ordre séquentiel", "To force sequential order"], ["Pour masquer les erreurs", "To hide errors"]], "Pour des opérations indépendantes pouvant être parallélisées", ["Les dépendances séquentielles doivent rester explicites.", "Sequential dependencies should remain explicit."], ["async-node"]),
          q("r3", ["Pourquoi encapsuler normalizeAmount ?", "Why encapsulate normalizeAmount?"], [["Garder une règle interne derrière l’interface publique", "Keep an internal rule behind the public interface"], ["Empêcher les tests", "Prevent tests"], ["Créer une route HTTP", "Create an HTTP route"]], "Garder une règle interne derrière l’interface publique", ["Le module expose son contrat, pas tous ses détails.", "The module exposes its contract, not every detail."], ["module-design"])
        ])
      ]
    },
    ...nodeApiModules.slice(0, 1),
    {
      id: "node-http",
      title: ["Express, routing et validation", "Express, routing, and validation"],
      description: ["Définir des contrats HTTP cohérents et rejeter les entrées invalides avant le métier.", "Define coherent HTTP contracts and reject invalid input before business logic."],
      vocabulary: [v.middleware, v.route, v.validation],
      lessons: [
        nodeLesson("node-02-routes", ["Concevoir une route REST", "Design a REST route"], ["Crée une ressource, retourne 201 et une URL de consultation.", "Create a resource, return 201, and provide a retrieval URL."], "router.post('/projects', async (request, response, next) => {\n  try {\n    const project = await projectService.create(request.body, request.auth.userId);\n    response.location(`/api/projects/${project.id}`).status(201).json({ project });\n  } catch (error) { next(error); }\n});", ["router.post('/projects'", "projectService.create", "request.auth.userId", "response.location", "status(201)", "next(error)"], ["rest-routing", "controllers"], [v.route, v.service]),
        nodeLesson("node-02-validation", ["Valider paramètres et body", "Validate parameters and body"], ["Parse les entrées avec un schéma strict et remplace request.body par la valeur validée.", "Parse input with a strict schema and replace request.body with the validated value."], "const projectCreateSchema = z.object({\n  name: z.string().trim().min(2).max(120),\n  visibility: z.enum(['private', 'team'])\n}).strict();\n\nexport function validateBody(schema) {\n  return (request, response, next) => {\n    const result = schema.safeParse(request.body);\n    if (!result.success) return response.status(400).json({ error: { code: 'VALIDATION_ERROR', issues: result.error.issues } });\n    request.body = result.data;\n    next();\n  };\n}", ["z.object", ".strict()", "schema.safeParse", "status(400)", "VALIDATION_ERROR", "request.body = result.data"], ["request-validation", "error-contracts"], [v.validation, v.middleware]),
        nodeLesson("node-02-errors", ["Centraliser les erreurs HTTP", "Centralize HTTP errors"], ["Mappe les erreurs connues et masque les détails internes en production.", "Map known errors and hide internal details in production."], "export function errorHandler(error, request, response, _next) {\n  const status = error.status || 500;\n  const code = error.code || 'INTERNAL_ERROR';\n  request.log?.error({ error, requestId: request.id });\n  response.status(status).json({\n    error: { code, message: status === 500 ? 'Internal server error.' : error.message },\n    requestId: request.id\n  });\n}", ["function errorHandler", "status || 500", "INTERNAL_ERROR", "request.log", "status === 500", "requestId"], ["error-handling", "safe-errors"], [v.middleware, v.observability]),
        project("node-02-api-project", ["Mini-projet : CRUD de projets", "Mini-project: project CRUD"], ["Crée list, détail, création, patch et suppression avec validation et codes HTTP cohérents.", "Create list, detail, creation, patch, and deletion with validation and coherent HTTP codes."], "router.get('/projects', asyncHandler(async (request, response) => {\n  response.json({ projects: await service.list(request.auth.userId) });\n}));\nrouter.get('/projects/:projectId', asyncHandler(async (request, response) => {\n  const project = await service.get(request.params.projectId, request.auth.userId);\n  if (!project) throw new HttpError(404, 'PROJECT_NOT_FOUND');\n  response.json({ project });\n}));\nrouter.post('/projects', validateBody(projectCreateSchema), asyncHandler(async (request, response) => {\n  const project = await service.create(request.body, request.auth.userId);\n  response.status(201).json({ project });\n}));\nrouter.patch('/projects/:projectId', validateBody(projectPatchSchema), asyncHandler(async (request, response) => {\n  response.json({ project: await service.update(request.params.projectId, request.body, request.auth.userId) });\n}));\nrouter.delete('/projects/:projectId', asyncHandler(async (request, response) => {\n  await service.remove(request.params.projectId, request.auth.userId);\n  response.status(204).end();\n}));", ["router.get('/projects'", "router.get('/projects/:projectId'", "router.post('/projects'", "router.patch('/projects/:projectId'", "router.delete('/projects/:projectId'", "validateBody", "status(201)", "status(204)"], ["rest-api", "request-validation", "error-contracts"], [v.route, v.validation, v.service]),
        quiz("node-02-review", ["Quiz : contrats HTTP", "Quiz: HTTP contracts"], [
          q("h1", ["Quel code pour une création réussie ?", "Which code indicates successful creation?"], [["201", "201"], ["204 avec body", "204 with a body"], ["404", "404"]], "201", ["201 Created exprime la création d’une nouvelle ressource.", "201 Created expresses creation of a new resource."], ["rest-routing"]),
          q("h2", ["Où valider request.body ?", "Where should request.body be validated?"], [["À l’entrée, avant le service métier", "At entry, before the business service"], ["Après l’écriture en base", "After writing to the database"], ["Uniquement dans le frontend", "Only in the frontend"]], "À l’entrée, avant le service métier", ["Le serveur ne peut faire confiance au client.", "The server cannot trust the client."], ["request-validation"]),
          q("h3", ["Que doit masquer une erreur 500 ?", "What should a 500 error hide?"], [["Stack, requête SQL et secrets", "Stack, SQL query, and secrets"], ["Le requestId", "The requestId"], ["Le code stable", "The stable code"]], "Stack, requête SQL et secrets", ["Le client reçoit un contrat sûr tandis que les logs conservent le diagnostic.", "The client receives a safe contract while logs keep diagnostics."], ["safe-errors"])
        ])
      ]
    },
    ...nodeApiModules.slice(1, 3),
    {
      id: "node-architecture-auth",
      title: ["Architecture, auth et autorisation", "Architecture, auth, and authorization"],
      description: ["Séparer contrôleurs, services et repositories puis imposer l’isolation des données côté serveur.", "Separate controllers, services, and repositories, then enforce server-side data isolation."],
      vocabulary: [v.service, v.repository, v.authentication, v.authorization],
      lessons: [
        nodeLesson("node-03-layers", ["Séparer contrôleur, service et repository", "Separate controller, service, and repository"], ["Place HTTP dans le contrôleur, règles dans le service et stockage dans le repository.", "Put HTTP in the controller, rules in the service, and storage in the repository."], "export function createProjectService(repository) {\n  return {\n    async create(input, actor) {\n      if (!actor.userId) throw new DomainError('AUTH_REQUIRED');\n      return repository.insert({ ...input, ownerId: actor.userId, createdAt: new Date().toISOString() });\n    }\n  };\n}\n\nexport function createProjectController(service) {\n  return async (request, response) => response.status(201).json({ project: await service.create(request.body, request.auth) });\n}", ["createProjectService", "repository.insert", "ownerId", "DomainError", "createProjectController", "status(201)"], ["layered-architecture", "dependency-injection"], [v.service, v.repository, v.authorization]),
        nodeLesson("node-03-authentication", ["Authentifier un bearer token", "Authenticate a bearer token"], ["Vérifie le token avec le fournisseur puis attache une identité minimale.", "Verify the token with the provider, then attach a minimal identity."], "export function authenticate(identityProvider) {\n  return async (request, response, next) => {\n    const header = request.headers.authorization || '';\n    const token = header.startsWith('Bearer ') ? header.slice(7) : '';\n    if (!token) return response.status(401).json({ error: { code: 'AUTH_REQUIRED' } });\n    const identity = await identityProvider.verify(token);\n    if (!identity) return response.status(401).json({ error: { code: 'INVALID_TOKEN' } });\n    request.auth = { userId: identity.id, roles: identity.roles || [] };\n    next();\n  };\n}", ["authorization", "startsWith('Bearer ')", "identityProvider.verify", "status(401)", "AUTH_REQUIRED", "request.auth"], ["authentication", "token-validation"], [v.authentication, v.middleware]),
        nodeLesson("node-03-authorization", ["Autoriser ressource et rôle", "Authorize resource and role"], ["Charge la ressource côté serveur et refuse tout propriétaire différent.", "Load the resource server-side and reject any different owner."], "export async function requireProjectOwner(request, response, next) {\n  const project = await request.repositories.projects.findById(request.params.projectId);\n  if (!project) return response.status(404).json({ error: { code: 'PROJECT_NOT_FOUND' } });\n  if (project.ownerId !== request.auth.userId && !request.auth.roles.includes('admin')) {\n    return response.status(403).json({ error: { code: 'PROJECT_ACCESS_DENIED' } });\n  }\n  request.project = project;\n  next();\n}", ["findById", "project.ownerId !== request.auth.userId", "roles.includes('admin')", "status(403)", "PROJECT_ACCESS_DENIED", "request.project"], ["authorization", "tenant-isolation"], [v.authorization, v.repository]),
        project("node-03-auth-project", ["Mini-projet : API multi-utilisateur", "Mini-project: multi-user API"], ["Protège lecture et écriture et ajoute des tests 401, 403 et accès croisé.", "Protect reads and writes and add 401, 403, and cross-user tests."], "router.use(authenticate(identityProvider));\nrouter.get('/projects/:projectId', requireProjectOwner, (request, response) => response.json({ project: request.project }));\nrouter.patch('/projects/:projectId', requireProjectOwner, validateBody(projectPatchSchema), asyncHandler(async (request, response) => {\n  response.json({ project: await repository.updateOwned(request.project.id, request.auth.userId, request.body) });\n}));\n\ntest('rejects unauthenticated reads', () => request(app).get('/projects/p1').expect(401));\ntest('rejects cross-user reads', () => request(app).get('/projects/p1').set('Authorization', bearer('user-b')).expect(403));\ntest('allows the owner', () => request(app).get('/projects/p1').set('Authorization', bearer('user-a')).expect(200));", ["router.use(authenticate", "requireProjectOwner", "updateOwned", "expect(401)", "cross-user", "expect(403)", "owner", "expect(200)"], ["authentication", "authorization", "tenant-isolation", "api-testing"], [v.authentication, v.authorization, v.repository]),
        quiz("node-03-review", ["Quiz : architecture et accès", "Quiz: architecture and access"], [
          q("a1", ["Où appliquer l’autorisation ?", "Where should authorization be enforced?"], [["Côté serveur sur chaque ressource sensible", "Server-side on each sensitive resource"], ["Dans un bouton masqué uniquement", "Only in a hidden button"], ["Dans le CSS", "In CSS"]], "Côté serveur sur chaque ressource sensible", ["Le client peut être modifié ou contourné.", "The client can be modified or bypassed."], ["authorization"]),
          q("a2", ["Que contient une identité minimale ?", "What does a minimal identity contain?"], [["Identifiant vérifié et rôles nécessaires", "Verified identifier and required roles"], ["Le mot de passe brut", "The raw password"], ["Toutes les données utilisateur", "All user data"]], "Identifiant vérifié et rôles nécessaires", ["Réduire les données attachées limite les fuites et dépendances.", "Minimizing attached data limits leaks and dependencies."], ["authentication"]),
          q("a3", ["Pourquoi injecter le repository ?", "Why inject the repository?"], [["Tester le métier et changer le stockage", "Test business logic and change storage"], ["Créer plus de variables globales", "Create more globals"], ["Éviter les interfaces", "Avoid interfaces"]], "Tester le métier et changer le stockage", ["Le service dépend d’un contrat, pas d’une technologie concrète.", "The service depends on a contract, not a concrete technology."], ["dependency-injection"])
        ])
      ]
    },
    ...nodeApiModules.slice(3, 5),
    {
      id: "node-production",
      title: ["Tests, sécurité HTTP et exploitation", "Testing, HTTP security, and operations"],
      description: ["Prouver les contrats API, réduire les abus et produire des logs exploitables sans secrets.", "Prove API contracts, reduce abuse, and produce useful logs without secrets."],
      vocabulary: [v.observability, ["rate limiting", "rate limiting", "Limitation du nombre de requêtes sur une période.", "Limiting request count over a time window."], ["test API", "API test", "Test du contrat HTTP à travers l’application Express.", "A test of the HTTP contract through the Express application."]],
      lessons: [
        nodeLesson("node-04-tests", ["Tester une API sans écouter un port", "Test an API without listening on a port"], ["Exporte app séparément et teste validation, succès et erreur avec Supertest.", "Export app separately and test validation, success, and error with Supertest."], "export const app = createApp({ projectService });\n\nit('creates a project', async () => {\n  const response = await request(app)\n    .post('/api/projects')\n    .set('Authorization', bearer('user-a'))\n    .send({ name: 'Atlas', visibility: 'private' })\n    .expect(201);\n  expect(response.body.project).toMatchObject({ name: 'Atlas', ownerId: 'user-a' });\n});\n\nit('rejects invalid input', () => request(app).post('/api/projects').set('Authorization', bearer('user-a')).send({ name: '' }).expect(400));", ["export const app", "request(app)", ".post('/api/projects')", "Authorization", ".expect(201)", "toMatchObject", ".expect(400)"], ["api-testing", "testable-architecture"], [v.route, v.validation, v.service]),
        nodeLesson("node-04-hardening", ["Durcir la frontière HTTP", "Harden the HTTP boundary"], ["Ajoute en-têtes, CORS explicite, limites de body, rate limiting et requestId.", "Add headers, explicit CORS, body limits, rate limiting, and request IDs."], "app.use(helmet());\napp.use(cors({ origin: allowedOrigins, credentials: true }));\napp.use(express.json({ limit: '256kb' }));\napp.use(rateLimit({ windowMs: 60_000, limit: 100, standardHeaders: true }));\napp.use((request, response, next) => {\n  request.id = request.headers['x-request-id'] || crypto.randomUUID();\n  response.setHeader('X-Request-Id', request.id);\n  next();\n});", ["helmet()", "cors({ origin: allowedOrigins", "express.json({ limit:", "rateLimit", "windowMs", "X-Request-Id", "crypto.randomUUID"], ["http-security", "rate-limiting", "request-tracing"], [v.middleware, v.observability]),
        project("node-04-capstone", ["Projet final : API de projets sécurisée", "Final project: secure project API"], ["Assemble architecture, validation, auth, autorisation, logs, tests et procédure d’exploitation.", "Assemble architecture, validation, auth, authorization, logs, tests, and an operations procedure."], "export function createApp({ services, identityProvider, logger }) {\n  const app = express();\n  app.disable('x-powered-by');\n  app.use(helmet());\n  app.use(cors({ origin: allowedOrigins, credentials: true }));\n  app.use(express.json({ limit: '256kb' }));\n  app.use(requestContext(logger));\n  app.use(rateLimit({ windowMs: 60_000, limit: 100 }));\n  app.use('/api/projects', authenticate(identityProvider), createProjectRouter(services.projects));\n  app.use(notFoundHandler);\n  app.use(errorHandler);\n  return app;\n}\n\nexport const projectService = createProjectService(projectRepository);\nexport const app = createApp({ services: { projects: projectService }, identityProvider, logger });\n\nit('isolates users', async () => {\n  await request(app).get('/api/projects/private-a').set('Authorization', bearer('user-b')).expect(403);\n});\nit('emits safe errors', async () => {\n  const response = await request(app).post('/api/projects').set('Authorization', bearer('user-a')).send({}).expect(400);\n  expect(response.body.error.code).toBe('VALIDATION_ERROR');\n  expect(response.body.stack).toBeUndefined();\n});", ["createApp", "helmet()", "cors(", "express.json", "requestContext", "rateLimit", "authenticate", "createProjectRouter", "notFoundHandler", "errorHandler", "isolates users", "expect(403)", "VALIDATION_ERROR", "toBeUndefined"], ["node-architecture", "http-security", "authorization", "api-testing", "observability"], [v.service, v.authorization, v.observability], true),
        quiz("node-04-review", ["Quiz : API de production", "Quiz: production API"], [
          q("p1", ["Pourquoi exporter app sans listen ?", "Why export app without listen?"], [["Pour tester et composer l’application sans port", "To test and compose the app without a port"], ["Pour désactiver HTTP", "To disable HTTP"], ["Pour exposer les secrets", "To expose secrets"]], "Pour tester et composer l’application sans port", ["Le démarrage du processus devient une responsabilité séparée.", "Process startup becomes a separate responsibility."], ["testable-architecture"]),
          q("p2", ["Que doit contenir un log de requête ?", "What should a request log contain?"], [["requestId, méthode, chemin, statut et durée", "requestId, method, path, status, and duration"], ["Token et mot de passe", "Token and password"], ["Body complet systématiquement", "Always the complete body"]], "requestId, méthode, chemin, statut et durée", ["Les identifiants et mesures aident au diagnostic sans collecter de secrets.", "Identifiers and measurements aid diagnosis without collecting secrets."], ["request-tracing"]),
          q("p3", ["Que protège le rate limiting ?", "What does rate limiting protect against?"], [["Abus et saturation élémentaire", "Basic abuse and saturation"], ["Toutes les failles métier", "Every business flaw"], ["Les erreurs de typage", "Type errors"]], "Abus et saturation élémentaire", ["Il complète validation, auth et limites de ressources.", "It complements validation, auth, and resource limits."], ["rate-limiting"])
        ]),
        quiz("node-final-exam", ["Examen Node.js et API", "Node.js and API exam"], [
          q("x1", ["Où placer une règle métier ?", "Where should a business rule live?"], [["Dans un service indépendant d’Express", "In a service independent of Express"], ["Dans chaque route copiée", "In every copied route"], ["Dans le frontend uniquement", "Only in the frontend"]], "Dans un service indépendant d’Express", ["Le transport ne doit pas définir le métier.", "Transport should not define business logic."], ["layered-architecture"]),
          q("x2", ["Comment traiter une entrée externe ?", "How should external input be handled?"], [["Valider et utiliser la valeur parsée", "Validate and use the parsed value"], ["Faire confiance au client", "Trust the client"], ["La stocker avant contrôle", "Store it before checking"]], "Valider et utiliser la valeur parsée", ["La donnée validée devient le contrat interne.", "Validated data becomes the internal contract."], ["request-validation"]),
          q("x3", ["Que prouve un 401 ?", "What does a 401 mean?"], [["Identité absente ou invalide", "Missing or invalid identity"], ["Identité connue mais interdite", "Known identity but forbidden"], ["Ressource absente", "Missing resource"]], "Identité absente ou invalide", ["403 correspond à une identité authentifiée sans permission.", "403 corresponds to an authenticated identity without permission."], ["authentication"]),
          q("x4", ["Comment prouver l’isolation utilisateur ?", "How do you prove user isolation?"], [["Avec des tests d’accès croisé 403", "With cross-user 403 tests"], ["Avec un bouton caché", "With a hidden button"], ["Avec un commentaire", "With a comment"]], "Avec des tests d’accès croisé 403", ["La frontière serveur doit refuser explicitement l’autre utilisateur.", "The server boundary must explicitly reject the other user."], ["tenant-isolation"]),
          q("x5", ["Quel ensemble décrit une API exploitable ?", "Which set describes an operable API?"], [["Validation, erreurs sûres, logs, tests et limites", "Validation, safe errors, logs, tests, and limits"], ["Routes uniquement", "Routes only"], ["Console.log du body", "Console.log of the body"]], "Validation, erreurs sûres, logs, tests et limites", ["La production exige prévention, preuve et diagnostic.", "Production requires prevention, proof, and diagnosis."], ["observability"])
        ], "exam", 80)
      ]
    },
    ...nodeApiModules.slice(5)
  ]
});

function nodeLesson(id, title, brief, solution, requirements, skills, vocabulary) {
  return { id, type: "node", title, brief, solution, requirements, skills, vocabulary };
}

function project(id, title, brief, solution, requirements, skills, vocabulary, finalProject = false) {
  return {
    id,
    project: true,
    exerciseType: "node",
    title,
    brief,
    solution,
    requirements,
    skills,
    vocabulary,
    durationMin: finalProject ? 240 : 120,
    xp: finalProject ? 160 : 95
  };
}

function quiz(id, title, questions, purpose = "module-review", passingScore = 70) {
  return { id, type: "quiz", title, questions, purpose, passingScore, brief: ["Raisonne sur la frontière serveur et le risque.", "Reason about the server boundary and risk."] };
}

function q(id, prompt, options, answer, explanation, skills) {
  return {
    id,
    type: "single",
    prompt,
    choices: options.map((option) => ({ id: option[0], label: option })),
    answer,
    explanation,
    points: 1,
    skills,
    glossaryTerms: []
  };
}
