import { createProfessionalTrack } from "../builders/createProfessionalTrack.js";
import { reactV9Modules } from "./reactV9Modules.js";

const v = {
  component: ["composant", "component", "Unité d’interface avec responsabilités et contrat explicites.", "A UI unit with explicit responsibilities and contract."],
  jsx: ["JSX", "JSX", "Syntaxe déclarative décrivant l’arbre d’interface.", "Declarative syntax describing the UI tree."],
  prop: ["prop", "prop", "Donnée reçue par un composant depuis son parent.", "Data received by a component from its parent."],
  state: ["état", "state", "Donnée locale qui influence le rendu et évolue avec les interactions.", "Local data that affects rendering and changes through interactions."],
  hook: ["hook", "hook", "Fonction React composant des capacités d’état, effet ou contexte.", "A React function composing state, effect, or context capabilities."],
  effect: ["effet", "effect", "Synchronisation avec un système extérieur au rendu React.", "Synchronization with a system outside React rendering."],
  context: ["contexte", "context", "Canal distribuant une dépendance à un sous-arbre.", "A channel distributing a dependency to a subtree."],
  route: ["route", "route", "Correspondance entre une URL et un écran ou état d’application.", "A mapping between a URL and an application screen or state."],
  suspense: ["Suspense", "Suspense", "Frontière affichant un fallback pendant l’attente d’une ressource ou d’un module.", "A boundary showing fallback while waiting for a resource or module."],
  memo: ["mémoïsation", "memoization", "Réutilisation d’un calcul ou rendu lorsque ses dépendances sont stables.", "Reuse of a calculation or render while dependencies remain stable."]
};

export const reactTrack = createProfessionalTrack({
  id: "react",
  label: "REACT",
  title: ["React pour applications métier", "React for business applications"],
  summary: ["Construis une application React accessible, testable et performante avec composants, hooks, routing et données asynchrones.", "Build an accessible, testable, performant React application with components, hooks, routing, and asynchronous data."],
  profession: ["React est utile quand une interface doit rester cohérente malgré de nombreux états et interactions. Le parcours privilégie la modélisation, la composition et l’accessibilité plutôt que l’empilement de hooks ou l’optimisation prématurée.", "React is useful when an interface must remain coherent across many states and interactions. This track prioritizes modeling, composition, and accessibility over hook accumulation or premature optimization."],
  prerequisites: [["Maîtriser JavaScript moderne", "Know modern JavaScript"], ["Comprendre HTML sémantique et accessibilité", "Understand semantic HTML and accessibility"], ["Connaître les bases TypeScript", "Know TypeScript basics"]],
  outcomes: [["Concevoir des composants composables", "Design composable components"], ["Gérer état, formulaires et effets", "Manage state, forms, and effects"], ["Intégrer routing et données asynchrones", "Integrate routing and asynchronous data"], ["Tester et mesurer une application React", "Test and measure a React application"]],
  capstone: ["Livrer un tableau de gestion de projets avec routing, authentification simulée, formulaires accessibles, API, tests et budget de performance.", "Ship a project-management dashboard with routing, simulated authentication, accessible forms, API, tests, and a performance budget."],
  certification: [["Valider les quiz de module", "Pass module quizzes"], ["Livrer quatre projets progressifs", "Ship four progressive projects"], ["Réussir l’examen final", "Pass the final exam"], ["Faire approuver le tableau métier final", "Get the final business dashboard approved"]],
  modules: [
    ...reactV9Modules,
    {
      id: "react-components",
      title: ["Composants et composition", "Components and composition"],
      description: ["Découper une interface selon ses responsabilités, ses données et ses variations.", "Split an interface according to responsibilities, data, and variations."],
      vocabulary: [v.component, v.jsx, v.prop],
      lessons: [
        reactLesson("react-01-component", ["Créer un composant sémantique", "Create a semantic component"], ["Écris une carte de cours avec article, titre et lien explicite.", "Write a course card with an article, heading, and explicit link."], "export function CourseCard({ title, summary, href }) {\n  return (\n    <article>\n      <h2>{title}</h2>\n      <p>{summary}</p>\n      <a href={href}>Ouvrir la formation {title}</a>\n    </article>\n  );\n}", ["function CourseCard", "<article>", "<h2>", "href={href}", "{title}"], ["react-components", "semantic-html"], [v.component, v.jsx, v.prop]),
        reactLesson("react-01-props", ["Concevoir un contrat de props", "Design a props contract"], ["Rends les variations explicites avec un type fermé et une valeur par défaut.", "Make variations explicit with a closed type and a default value."], "type BadgeProps = {\n  label: string;\n  tone?: 'info' | 'success' | 'warning';\n};\n\nexport function Badge({ label, tone = 'info' }: BadgeProps) {\n  return <span data-tone={tone}>{label}</span>;\n}", ["type BadgeProps", "tone?:", "'info' | 'success' | 'warning'", "tone = 'info'", "data-tone"], ["component-contracts", "typescript-react"], [v.prop, ["valeur par défaut", "default value", "Valeur utilisée lorsqu’une prop optionnelle est absente.", "A value used when an optional prop is absent."]]),
        reactLesson("react-01-composition", ["Composer plutôt que multiplier les options", "Compose instead of multiplying options"], ["Utilise children et des sous-composants pour structurer une fenêtre modale.", "Use children and subcomponents to structure a modal."], "export function Dialog({ title, children, onClose }) {\n  return (\n    <section role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"dialog-title\">\n      <header><h2 id=\"dialog-title\">{title}</h2><button onClick={onClose}>Fermer</button></header>\n      <div>{children}</div>\n    </section>\n  );\n}", ["children", "role=\"dialog\"", "aria-modal=\"true\"", "aria-labelledby", "onClick={onClose}"], ["component-composition", "accessible-dialogs"], [v.component, v.prop, ["children", "children", "Contenu fourni entre les balises d’un composant.", "Content supplied between a component's tags."]]),
        project("react-01-library-project", ["Mini-projet : bibliothèque de cartes", "Mini-project: card library"], ["Construis Card, CardHeader, CardBody et CardActions avec contrats accessibles.", "Build Card, CardHeader, CardBody, and CardActions with accessible contracts."], "export function Card({ children }) { return <article className=\"card\">{children}</article>; }\nexport function CardHeader({ title, eyebrow }) { return <header><p>{eyebrow}</p><h2>{title}</h2></header>; }\nexport function CardBody({ children }) { return <div>{children}</div>; }\nexport function CardActions({ children, label = 'Actions' }) { return <footer aria-label={label}>{children}</footer>; }\n\nexport function CourseCardExample() {\n  return <Card><CardHeader eyebrow=\"Parcours\" title=\"React\" /><CardBody><p>20 leçons pratiques.</p></CardBody><CardActions><a href=\"/learn/react\">Commencer</a></CardActions></Card>;\n}", ["function Card", "function CardHeader", "function CardBody", "function CardActions", "aria-label", "CourseCardExample"], ["component-composition", "design-system", "accessibility"], [v.component, v.jsx, v.prop]),
        quiz("react-01-review", ["Quiz : composants", "Quiz: components"], [
          q("c1", ["Où placer une responsabilité réutilisée ?", "Where should a reused responsibility live?"], [["Dans un composant au contrat clair", "In a component with a clear contract"], ["Dans chaque écran copié", "In every copied screen"], ["Dans une variable globale mutable", "In mutable global state"]], "Dans un composant au contrat clair", ["La réutilisation doit conserver sens et variations explicites.", "Reuse should preserve meaning and explicit variations."], ["react-components"]),
          q("c2", ["Pourquoi éviter vingt props booléennes ?", "Why avoid twenty boolean props?"], [["Elles créent des combinaisons incohérentes", "They create inconsistent combinations"], ["React refuse les booléens", "React rejects booleans"], ["Elles empêchent le CSS", "They prevent CSS"]], "Elles créent des combinaisons incohérentes", ["Composition et unions rendent les variantes réellement permises.", "Composition and unions express actually allowed variants."], ["component-contracts"]),
          q("c3", ["Quel élément convient à une carte autonome ?", "Which element suits a self-contained card?"], [["article", "article"], ["div sans rôle", "roleless div"], ["br", "br"]], "article", ["La sémantique HTML reste la première couche d’accessibilité React.", "HTML semantics remain React's first accessibility layer."], ["semantic-html"])
        ])
      ]
    },
    {
      id: "react-state",
      title: ["État, événements et formulaires", "State, events, and forms"],
      description: ["Faire évoluer l’interface avec des transitions prévisibles et des formulaires accessibles.", "Evolve the interface through predictable transitions and accessible forms."],
      vocabulary: [v.state, ["événement", "event", "Objet décrivant une interaction utilisateur ou navigateur.", "An object describing a user or browser interaction."], ["contrôlé", "controlled", "Champ dont la valeur est pilotée par l’état React.", "A field whose value is driven by React state."]],
      lessons: [
        reactLesson("react-02-state", ["Modéliser un état minimal", "Model minimal state"], ["Stocke la source de vérité et dérive le nombre de tâches visibles.", "Store the source of truth and derive the visible task count."], "function TaskSummary({ initialTasks }) {\n  const [tasks, setTasks] = useState(initialTasks);\n  const openTasks = tasks.filter((task) => !task.done);\n  return <p>{openTasks.length} tâches ouvertes</p>;\n}", ["useState", "setTasks", "tasks.filter", "openTasks.length"], ["react-state", "derived-state"], [v.state, ["état dérivé", "derived state", "Valeur calculée depuis une source de vérité existante.", "A value calculated from an existing source of truth."]]),
        reactLesson("react-02-events", ["Traiter les événements explicitement", "Handle events explicitly"], ["Ajoute une tâche sans mutation et donne un type précis au submit.", "Add a task without mutation and type the submit event precisely."], "function TaskForm({ onCreate }) {\n  const [title, setTitle] = useState('');\n  function handleSubmit(event) {\n    event.preventDefault();\n    if (!title.trim()) return;\n    onCreate({ id: crypto.randomUUID(), title: title.trim(), done: false });\n    setTitle('');\n  }\n  return <form onSubmit={handleSubmit}><label>Titre<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><button>Ajouter</button></form>;\n}", ["handleSubmit", "preventDefault", "onCreate", "onSubmit={handleSubmit}", "value={title}", "onChange"], ["react-events", "immutable-updates"], [v.state, v.prop]),
        reactLesson("react-02-lists", ["Rendre listes et états vides", "Render lists and empty states"], ["Utilise une clé stable et annonce clairement l’absence de résultat.", "Use a stable key and clearly announce no results."], "function TaskList({ tasks }) {\n  if (tasks.length === 0) return <p role=\"status\">Aucune tâche ne correspond aux filtres.</p>;\n  return <ul>{tasks.map((task) => <li key={task.id}>{task.title}</li>)}</ul>;\n}", ["tasks.length === 0", "role=\"status\"", "tasks.map", "key={task.id}", "<ul>"], ["list-rendering", "empty-states"], [v.jsx, ["clé", "key", "Identifiant stable aidant React à associer les éléments entre deux rendus.", "A stable identifier helping React match elements between renders."]]),
        project("react-02-form-project", ["Mini-projet : formulaire multi-états", "Mini-project: multi-state form"], ["Construis validation, erreur, soumission et confirmation avec focus cohérent.", "Build validation, error, submission, and confirmation with coherent focus."], "function ProfileForm({ saveProfile }) {\n  const [name, setName] = useState('');\n  const [status, setStatus] = useState('idle');\n  const error = name.trim() ? '' : 'Le nom est requis.';\n  async function handleSubmit(event) {\n    event.preventDefault();\n    if (error) return;\n    setStatus('saving');\n    try { await saveProfile({ name: name.trim() }); setStatus('success'); }\n    catch { setStatus('error'); }\n  }\n  return <form onSubmit={handleSubmit} aria-busy={status === 'saving'}><label htmlFor=\"name\">Nom</label><input id=\"name\" value={name} onChange={(event) => setName(event.target.value)} aria-describedby=\"name-error\" />{error && <p id=\"name-error\" role=\"alert\">{error}</p>}<button disabled={status === 'saving'}>Enregistrer</button><p role=\"status\">{status === 'success' ? 'Profil enregistré.' : ''}</p></form>;\n}", ["useState", "onSubmit", "aria-busy", "htmlFor=\"name\"", "aria-describedby", "role=\"alert\"", "role=\"status\"", "disabled="], ["accessible-forms", "async-state", "react-state"], [v.state, v.jsx, ["aria-busy", "aria-busy", "État indiquant qu’une région attend la fin d’une opération.", "A state indicating a region is waiting for an operation to finish."]]),
        quiz("react-02-review", ["Quiz : état et formulaires", "Quiz: state and forms"], [
          q("s1", ["Que faut-il stocker dans state ?", "What should be stored in state?"], [["La source de vérité minimale", "The minimal source of truth"], ["Chaque valeur calculable", "Every computable value"], ["Toutes les props recopiées", "Every copied prop"]], "La source de vérité minimale", ["Les valeurs dérivées restent cohérentes lorsqu’elles sont recalculées.", "Derived values remain coherent when recalculated."], ["derived-state"]),
          q("s2", ["Pourquoi une clé index est-elle fragile ?", "Why is an index key fragile?"], [["L’ordre peut changer et associer le mauvais état", "Order can change and associate the wrong state"], ["Elle est trop longue", "It is too long"], ["Elle bloque map", "It blocks map"]], "L’ordre peut changer et associer le mauvais état", ["Une identité métier stable préserve la relation élément-état.", "Stable business identity preserves the element-state relationship."], ["list-rendering"]),
          q("s3", ["Comment annoncer une erreur de formulaire ?", "How should a form error be announced?"], [["Texte relié au champ et rôle adapté", "Text connected to the field and an appropriate role"], ["Couleur rouge uniquement", "Red color only"], ["Placeholder uniquement", "Placeholder only"]], "Texte relié au champ et rôle adapté", ["La relation et l’annonce ne doivent pas dépendre de la vision.", "The relationship and announcement must not depend on sight."], ["accessible-forms"])
        ])
      ]
    },
    {
      id: "react-hooks-data",
      title: ["Hooks, effets et données", "Hooks, effects, and data"],
      description: ["Synchroniser uniquement les systèmes externes et isoler la logique réutilisable.", "Synchronize only external systems and isolate reusable logic."],
      vocabulary: [v.hook, v.effect, v.context],
      lessons: [
        reactLesson("react-03-effect", ["Utiliser un effet pour synchroniser", "Use an effect for synchronization"], ["Synchronise le titre du document et restaure sa valeur au démontage.", "Synchronize the document title and restore it on unmount."], "function PageTitle({ title }) {\n  useEffect(() => {\n    const previous = document.title;\n    document.title = `${title} | PulsaTeach`;\n    return () => { document.title = previous; };\n  }, [title]);\n  return null;\n}", ["useEffect", "document.title", "return () =>", "[title]"], ["react-effects", "effect-cleanup"], [v.effect, v.hook]),
        reactLesson("react-03-fetch", ["Charger des données sans course", "Load data without races"], ["Annule la requête lors du changement d’identifiant et distingue les états.", "Cancel the request when the identifier changes and distinguish states."], "function Project({ projectId }) {\n  const [state, setState] = useState({ status: 'loading' });\n  useEffect(() => {\n    const controller = new AbortController();\n    setState({ status: 'loading' });\n    fetch(`/api/projects/${projectId}`, { signal: controller.signal })\n      .then((response) => response.ok ? response.json() : Promise.reject(new Error('HTTP')))\n      .then((data) => setState({ status: 'success', data }))\n      .catch((error) => { if (error.name !== 'AbortError') setState({ status: 'error', error }); });\n    return () => controller.abort();\n  }, [projectId]);\n  return <ProjectState state={state} />;\n}", ["AbortController", "signal: controller.signal", "controller.abort", "status: 'loading'", "status: 'success'", "status: 'error'", "[projectId]"], ["async-react", "effect-cleanup", "request-states"], [v.effect, v.state, ["AbortController", "AbortController", "API permettant d’annuler une opération asynchrone compatible.", "An API used to cancel a compatible asynchronous operation."]]),
        reactLesson("react-03-custom-hook", ["Extraire un hook orienté capacité", "Extract a capability-oriented hook"], ["Crée un hook de stockage local avec initialisation paresseuse et sérialisation.", "Create a local-storage hook with lazy initialization and serialization."], "function useLocalStorage(key, initialValue) {\n  const [value, setValue] = useState(() => {\n    const stored = localStorage.getItem(key);\n    return stored ? JSON.parse(stored) : initialValue;\n  });\n  useEffect(() => { localStorage.setItem(key, JSON.stringify(value)); }, [key, value]);\n  return [value, setValue];\n}", ["function useLocalStorage", "useState(() =>", "localStorage.getItem", "localStorage.setItem", "[key, value]", "return [value, setValue]"], ["custom-hooks", "local-persistence"], [v.hook, v.effect]),
        project("react-03-data-project", ["Mini-projet : catalogue asynchrone", "Mini-project: asynchronous catalog"], ["Assemble recherche, annulation, chargement, erreur, retry et cache local.", "Assemble search, cancellation, loading, error, retry, and local cache."], "function useCatalog(query) {\n  const [state, setState] = useState({ status: 'loading' });\n  const [retryKey, retry] = useReducer((value) => value + 1, 0);\n  useEffect(() => {\n    const controller = new AbortController();\n    setState({ status: 'loading' });\n    fetch(`/api/catalog?q=${encodeURIComponent(query)}`, { signal: controller.signal })\n      .then((response) => response.ok ? response.json() : Promise.reject(new Error('HTTP')))\n      .then((data) => { localStorage.setItem(`catalog:${query}`, JSON.stringify(data)); setState({ status: 'success', data }); })\n      .catch((error) => { if (error.name !== 'AbortError') setState({ status: 'error', error }); });\n    return () => controller.abort();\n  }, [query, retryKey]);\n  return { state, retry };\n}\n\nfunction Catalog({ query }) {\n  const { state, retry } = useCatalog(query);\n  if (state.status === 'loading') return <p role=\"status\">Chargement…</p>;\n  if (state.status === 'error') return <div role=\"alert\">Échec.<button onClick={retry}>Réessayer</button></div>;\n  return <ul>{state.data.tracks.map((track) => <li key={track.id}>{track.title}</li>)}</ul>;\n}", ["function useCatalog", "AbortController", "useReducer", "localStorage.setItem", "role=\"status\"", "role=\"alert\"", "onClick={retry}", "key={track.id}"], ["async-react", "custom-hooks", "resilient-ui"], [v.hook, v.effect, v.state]),
        quiz("react-03-review", ["Quiz : hooks et données", "Quiz: hooks and data"], [
          q("h1", ["Quand utiliser useEffect ?", "When should useEffect be used?"], [["Pour synchroniser un système externe", "To synchronize an external system"], ["Pour chaque calcul local", "For every local calculation"], ["Pour remplacer les événements", "To replace events"]], "Pour synchroniser un système externe", ["Le rendu et les calculs dérivés ne nécessitent généralement pas d’effet.", "Rendering and derived calculations usually do not need an effect."], ["react-effects"]),
          q("h2", ["À quoi sert le cleanup ?", "What is cleanup for?"], [["Arrêter abonnement, timer ou requête précédente", "Stop a previous subscription, timer, or request"], ["Effacer toutes les props", "Delete every prop"], ["Relancer le navigateur", "Restart the browser"]], "Arrêter abonnement, timer ou requête précédente", ["Le cleanup empêche les effets obsolètes et fuites.", "Cleanup prevents stale effects and leaks."], ["effect-cleanup"]),
          q("h3", ["Que doit exprimer un custom hook ?", "What should a custom hook express?"], [["Une capacité cohérente", "A coherent capability"], ["Une ligne extraite au hasard", "A randomly extracted line"], ["Un composant visuel complet", "A complete visual component"]], "Une capacité cohérente", ["Le nom et le contrat doivent raconter l’intention réutilisable.", "The name and contract should convey reusable intent."], ["custom-hooks"])
        ])
      ]
    },
    {
      id: "react-production",
      title: ["Routing, qualité et performance", "Routing, quality, and performance"],
      description: ["Assembler des écrans navigables, accessibles, testés et mesurés avant optimisation.", "Assemble navigable, accessible, tested screens measured before optimization."],
      vocabulary: [v.route, v.suspense, v.memo],
      lessons: [
        reactLesson("react-04-routing-a11y", ["Routing et focus accessible", "Routing and accessible focus"], ["Déclare des routes et déplace le focus vers le titre après navigation.", "Declare routes and move focus to the heading after navigation."], "function RouteHeading({ children }) {\n  const headingRef = useRef(null);\n  const location = useLocation();\n  useEffect(() => { headingRef.current?.focus(); }, [location.pathname]);\n  return <h1 ref={headingRef} tabIndex={-1}>{children}</h1>;\n}\n\nconst routes = createBrowserRouter([\n  { path: '/', element: <CatalogPage /> },\n  { path: '/projects/:projectId', element: <ProjectPage /> },\n  { path: '*', element: <NotFoundPage /> }\n]);", ["useRef", "useLocation", "focus()", "tabIndex={-1}", "createBrowserRouter", "path: '*'", "projects/:projectId"], ["react-routing", "focus-management"], [v.route, v.effect, ["paramètre de route", "route parameter", "Segment dynamique extrait de l’URL.", "A dynamic segment extracted from the URL."]]),
        reactLesson("react-04-quality", ["Tester puis mesurer la performance", "Test then measure performance"], ["Teste l’usage réel et réserve memo aux rendus mesurés coûteux.", "Test real usage and reserve memo for measured expensive renders."], "const ProjectList = memo(function ProjectList({ projects, onSelect }) {\n  return <ul>{projects.map((project) => <li key={project.id}><button onClick={() => onSelect(project.id)}>{project.name}</button></li>)}</ul>;\n});\n\ntest('ouvre un projet au clavier', async () => {\n  const user = userEvent.setup();\n  render(<ProjectList projects={[{ id: 'p1', name: 'Atlas' }]} onSelect={onSelect} />);\n  await user.click(screen.getByRole('button', { name: 'Atlas' }));\n  expect(onSelect).toHaveBeenCalledWith('p1');\n});", ["memo(", "projects.map", "userEvent.setup", "getByRole", "toHaveBeenCalledWith"], ["react-testing", "react-performance"], [v.memo, ["React Testing Library", "React Testing Library", "Bibliothèque testant l’interface via son comportement observable.", "A library testing UI through observable behavior."]]),
        project("react-04-capstone", ["Projet final : tableau de projets", "Final project: project dashboard"], ["Livre routing, filtres, formulaire, API, états accessibles, tests et chargement paresseux.", "Ship routing, filters, form, API, accessible states, tests, and lazy loading."], "const ProjectPage = lazy(() => import('./ProjectPage.jsx'));\n\nfunction App() {\n  return <RouterProvider router={router} />;\n}\n\nconst router = createBrowserRouter([\n  { path: '/', element: <AppLayout />, children: [\n    { index: true, element: <CatalogPage /> },\n    { path: 'projects/:projectId', element: <Suspense fallback={<p role=\"status\">Chargement…</p>}><ProjectPage /></Suspense> },\n    { path: 'projects/new', element: <ProjectForm /> }\n  ] }\n]);\n\nfunction ProjectForm() {\n  const [name, setName] = useState('');\n  return <form aria-label=\"Créer un projet\"><label htmlFor=\"project-name\">Nom</label><input id=\"project-name\" value={name} onChange={(event) => setName(event.target.value)} /><button>Créer</button></form>;\n}\n\ntest('crée un projet', async () => {\n  const user = userEvent.setup();\n  render(<ProjectForm />);\n  await user.type(screen.getByLabelText('Nom'), 'Atlas');\n  await user.click(screen.getByRole('button', { name: 'Créer' }));\n});", ["lazy(", "Suspense", "role=\"status\"", "createBrowserRouter", "projects/:projectId", "ProjectForm", "htmlFor", "userEvent.setup", "getByRole"], ["react-architecture", "react-routing", "accessible-forms", "react-testing", "code-splitting"], [v.route, v.suspense, v.memo], true),
        quiz("react-04-review", ["Quiz : React en production", "Quiz: React in production"], [
          q("p1", ["Que doit faire le focus après une navigation SPA ?", "What should focus do after SPA navigation?"], [["Atteindre le nouveau titre ou contenu principal", "Reach the new heading or main content"], ["Rester toujours dans le menu", "Always remain in the menu"], ["Disparaître", "Disappear"]], "Atteindre le nouveau titre ou contenu principal", ["Le changement visuel doit aussi être perceptible au clavier et lecteur d’écran.", "The visual change must also be perceivable by keyboard and screen reader."], ["focus-management"]),
          q("p2", ["Quand utiliser memo ?", "When should memo be used?"], [["Après mesure d’un rendu coûteux avec props stables", "After measuring an expensive render with stable props"], ["Sur chaque composant", "On every component"], ["Pour corriger un effet", "To fix an effect"]], "Après mesure d’un rendu coûteux avec props stables", ["La mémoïsation a aussi un coût et complexifie le contrat.", "Memoization also has a cost and complicates the contract."], ["react-performance"]),
          q("p3", ["Que protège un test React robuste ?", "What does a robust React test protect?"], [["Le parcours observable de l’utilisateur", "The user's observable journey"], ["Le nom d’un hook privé", "A private hook name"], ["Le nombre exact de div", "The exact number of divs"]], "Le parcours observable de l’utilisateur", ["Le test reste utile après un refactoring interne.", "The test remains useful after internal refactoring."], ["react-testing"])
        ]),
        quiz("react-final-exam", ["Examen React", "React exam"], [
          q("x1", ["Quelle est la meilleure frontière de composant ?", "What is the best component boundary?"], [["Une responsabilité cohérente avec contrat clair", "A coherent responsibility with a clear contract"], ["Chaque balise dans son fichier", "Every tag in its own file"], ["Tout l’écran dans une fonction", "The whole screen in one function"]], "Une responsabilité cohérente avec contrat clair", ["Le découpage sert compréhension, test et composition.", "Boundaries serve understanding, testing, and composition."], ["react-components"]),
          q("x2", ["Comment éviter un état incohérent ?", "How do you avoid inconsistent state?"], [["Stocker le minimum et dériver le reste", "Store the minimum and derive the rest"], ["Dupliquer chaque valeur", "Duplicate every value"], ["Ajouter davantage d’effets", "Add more effects"]], "Stocker le minimum et dériver le reste", ["Une seule source de vérité réduit les synchronisations.", "A single source of truth reduces synchronization."], ["derived-state"]),
          q("x3", ["Que doit nettoyer un effet réseau ?", "What should a network effect clean up?"], [["La requête devenue obsolète", "The stale request"], ["Le DOM entier", "The entire DOM"], ["Toutes les données du cache", "All cached data"]], "La requête devenue obsolète", ["L’annulation empêche une ancienne réponse de remplacer l’état courant.", "Cancellation prevents an old response from replacing current state."], ["effect-cleanup"]),
          q("x4", ["Quelle base rend un formulaire accessible ?", "What foundation makes a form accessible?"], [["Labels, erreurs reliées, focus et statuts", "Labels, connected errors, focus, and statuses"], ["Placeholder et couleur seulement", "Placeholder and color only"], ["Un div cliquable", "A clickable div"]], "Labels, erreurs reliées, focus et statuts", ["L’information et l’action doivent rester disponibles sans vision ni souris.", "Information and action must remain available without sight or mouse."], ["accessible-forms"]),
          q("x5", ["Comment optimiser React ?", "How should React be optimized?"], [["Mesurer, cibler puis vérifier", "Measure, target, then verify"], ["Ajouter memo partout", "Add memo everywhere"], ["Supprimer les tests", "Remove tests"]], "Mesurer, cibler puis vérifier", ["La performance est une propriété observée, pas une intuition.", "Performance is an observed property, not an intuition."], ["react-performance"])
        ], "exam", 80)
      ]
    }
  ]
});

function reactLesson(id, title, brief, solution, requirements, skills, vocabulary) {
  return { id, type: "react", title, brief, solution, requirements, skills, vocabulary };
}

function project(id, title, brief, solution, requirements, skills, vocabulary, finalProject = false) {
  return {
    id,
    project: true,
    exerciseType: "react",
    title,
    brief,
    solution,
    requirements,
    skills,
    vocabulary,
    durationMin: finalProject ? 210 : 120,
    xp: finalProject ? 150 : 95
  };
}

function quiz(id, title, questions, purpose = "module-review", passingScore = 70) {
  return { id, type: "quiz", title, questions, purpose, passingScore, brief: ["Choisis la décision qui protège le contrat utilisateur.", "Choose the decision that protects the user contract."] };
}

function q(id, prompt, options, answer, explanation, skills) {
  return {
    id,
    type: "single",
    prompt,
    choices: options.map((option) => ({ id: option[0], label: option })),
    answer,
    explanation,
    points: 1,
    skills,
    glossaryTerms: []
  };
}
