const terms = {
  contract: ["test de contrat", "contract test", "Vérification qu’un producteur et un consommateur partagent le même contrat.", "Check that a producer and consumer share the same contract."],
  msw: ["MSW", "MSW", "Mock Service Worker intercepte les requêtes réseau dans les tests frontend.", "Mock Service Worker intercepts network requests in frontend tests."],
  mutation: ["mutation testing", "mutation testing", "Technique qui modifie le code pour vérifier que les tests échouent vraiment.", "Technique that changes code to verify tests truly fail."],
  regression: ["régression", "regression", "Comportement auparavant valide cassé par un changement.", "Previously valid behavior broken by a change."],
  visual: ["test visuel", "visual test", "Comparaison contrôlée du rendu pour détecter des changements d’interface.", "Controlled rendering comparison to detect UI changes."],
  flake: ["test instable", "flaky test", "Test dont le résultat varie sans changement fonctionnel.", "Test whose result varies without functional change."],
  risk: ["matrice de risque", "risk matrix", "Classement impact/probabilité guidant l’effort de test.", "Impact/probability ranking guiding test effort."]
};

export const testingModules = [
  {
    id: "testing-api-contracts",
    title: ["API, contrats et mocks réalistes", "API, contracts, and realistic mocks"],
    description: ["Tester les frontières réseau sans mentir sur les erreurs, délais et formats.", "Test network boundaries without lying about errors, delays, and formats."],
    vocabulary: [terms.contract, terms.msw],
    lessons: [
      code("testing-contract-schema", ["Valider un contrat de réponse", "Validate a response contract"], ["Vérifie qu’un endpoint renvoie les champs attendus avant que l’UI les consomme.", "Verify an endpoint returns expected fields before the UI consumes them."], "const CourseSummary = z.object({\n  id: z.string().min(1),\n  slug: z.string().min(1),\n  title: z.string().min(1),\n  lessonCount: z.number().int().positive(),\n  updatedAt: z.string().datetime()\n});\n\nconst response = await request.get('/api/catalog');\nexpect(response.status()).toBe(200);\nexpect(() => CourseSummary.array().parse(response.body.items)).not.toThrow();", ["z.object", "id:", "lessonCount", "datetime", "request.get", "status()).toBe(200)", "parse(response.body.items)"], ["api-testing", "contract-testing"], [terms.contract]),
      code("testing-msw", ["Mocker l’API avec MSW", "Mock the API with MSW"], ["Intercepte le réseau au niveau HTTP pour garder un test proche du comportement utilisateur.", "Intercept the network at HTTP level to keep the test close to user behavior."], "const server = setupServer(\n  http.get('/api/catalog', () => HttpResponse.json({ items: [{ id: 'html', title: 'HTML interactif' }] })),\n  http.post('/api/progress', async ({ request }) => {\n    const body = await request.json();\n    return HttpResponse.json({ saved: true, lessonId: body.lessonId });\n  })\n);\n\nbeforeAll(() => server.listen());\nafterEach(() => server.resetHandlers());\nafterAll(() => server.close());", ["setupServer", "http.get", "HttpResponse.json", "http.post", "request.json", "beforeAll", "resetHandlers", "server.close"], ["mock-service-worker", "component-integration"], [terms.msw]),
      code("testing-error-states", ["Tester les états d’erreur réseau", "Test network error states"], ["Force timeout, 500 et payload invalide pour vérifier les messages et le retry.", "Force timeout, 500, and invalid payload to verify messages and retry."], "server.use(http.get('/api/catalog', () => HttpResponse.json({ error: 'unavailable' }, { status: 503 })));\nrender(<CatalogPage />);\nexpect(await screen.findByRole('alert')).toHaveTextContent(/catalogue indisponible/i);\nawait user.click(screen.getByRole('button', { name: /réessayer/i }));\nexpect(screen.getByRole('status')).toHaveTextContent(/chargement/i);", ["server.use", "status: 503", "render(<CatalogPage", "findByRole('alert')", "réessayer", "role('status')"], ["error-state-testing", "resilience-testing"], [terms.msw, terms.regression]),
      project("testing-api-project", ["Lab : suite API robuste", "Lab: robust API suite"], ["Couvre contrat, succès, erreur, retry et sauvegarde de progression.", "Cover contract, success, error, retry, and progress saving."], "# Suite API\n\n## Contrats\n- /api/catalog: id, slug, title, lessonCount, updatedAt\n- /api/progress: saved, lessonId, updatedAt\n\n## Scénarios\n1. catalogue chargé avec contrat valide\n2. payload invalide rejeté proprement\n3. erreur 503 affiche une alerte et un bouton retry\n4. sauvegarde progression renvoie un état confirmé\n5. route privée renvoie 401 sans token\n\n## Preuves\n- tests unitaires du parseur\n- tests composant avec MSW\n- test API direct\n- trace CI conservée en cas d’échec", ["Contrats", "/api/catalog", "/api/progress", "payload invalide", "erreur 503", "401 sans token", "MSW", "trace CI", "schéma Zod", "retry utilisateur", "sauvegarde progression", "route privée", "assertion message erreur", "resetHandlers", "test API direct", "artefact trace"], ["api-testing", "contract-testing", "resilience-testing"], [terms.contract, terms.msw]),
      quiz("testing-api-quiz", ["Quiz : contrats API", "Quiz: API contracts"], [
        q("a1", ["Pourquoi tester le contrat ?", "Why test the contract?"], [["Pour détecter une rupture avant l’UI", "To detect a break before the UI"], ["Pour remplacer HTTPS", "To replace HTTPS"], ["Pour ignorer les erreurs", "To ignore errors"]], "Pour détecter une rupture avant l’UI", ["Le consommateur dépend de champs précis.", "The consumer depends on specific fields."], ["contract-testing"]),
        q("a2", ["Quel mock est le plus proche du comportement réseau ?", "Which mock is closest to network behavior?"], [["Un mock HTTP type MSW", "An HTTP mock like MSW"], ["Un remplacement de chaque fonction interne", "Replacing every internal function"], ["Un snapshot JSON figé sans scénario", "A frozen JSON snapshot without scenario"]], "Un mock HTTP type MSW", ["L’UI continue d’appeler fetch comme en vrai.", "The UI still calls fetch as in reality."], ["mock-service-worker"]),
        q("a3", ["Quel état doit être testé explicitement ?", "Which state must be tested explicitly?"], [["Erreur et retry utilisateur", "User-facing error and retry"], ["Uniquement le succès", "Only success"], ["Le nom de la variable", "Variable name"]], "Erreur et retry utilisateur", ["Les incidents réseau sont normaux en production.", "Network incidents are normal in production."], ["resilience-testing"])
      ])
    ]
  },
  {
    id: "testing-regression-quality",
    title: ["Régression, mutation et qualité des assertions", "Regression, mutation, and assertion quality"],
    description: ["Prouver que les tests échouent quand le comportement protégé casse.", "Prove tests fail when protected behavior breaks."],
    vocabulary: [terms.mutation, terms.regression, terms.risk],
    lessons: [
      text("testing-risk-matrix", ["Prioriser par risque", "Prioritize by risk"], ["Classe les parcours par impact utilisateur et probabilité de casse.", "Rank journeys by user impact and break probability."], ["Impact business ou apprentissage", "Historique de bugs", "Complexité technique", "Surface sécurité", "Coût de test", "Niveau de preuve choisi"], ["risk-based-testing", "test-strategy"], [terms.risk]),
      code("testing-mutation", ["Détecter les assertions faibles", "Detect weak assertions"], ["Une mutation simple doit faire échouer le test si la règle est vraiment protégée.", "A simple mutation must fail the test if the rule is truly protected."], "export function passQuiz(score, passingScore = 70) {\n  return score >= passingScore;\n}\n\ntest('échoue sous le seuil', () => {\n  expect(passQuiz(69, 70)).toBe(false);\n});\n\ntest('réussit au seuil exact', () => {\n  expect(passQuiz(70, 70)).toBe(true);\n});", ["score >= passingScore", "passQuiz(69, 70)", "toBe(false)", "passQuiz(70, 70)", "toBe(true)"], ["mutation-testing", "boundary-testing"], [terms.mutation]),
      code("testing-regression", ["Écrire un test de régression utile", "Write a useful regression test"], ["Transforme un bug réel en test minimal qui échoue avant correction.", "Turn a real bug into a minimal test that fails before the fix."], "test('ne partage jamais la progression entre deux utilisateurs', async () => {\n  await saveProgress({ userId: 'user-a', lessonId: 'html-01', completed: true });\n  const userBProgress = await listProgress({ userId: 'user-b' });\n  expect(userBProgress).not.toContainEqual(expect.objectContaining({ lessonId: 'html-01' }));\n});", ["ne partage jamais", "user-a", "user-b", "saveProgress", "listProgress", "not.toContainEqual", "lessonId"], ["regression-testing", "privacy-testing"], [terms.regression]),
      project("testing-regression-project", ["Lab : pack anti-régression", "Lab: anti-regression pack"], ["Crée une matrice de risques et ajoute cinq tests ciblés sur les vrais dangers.", "Create a risk matrix and add five targeted tests for real dangers."], "# Pack anti-régression\n\n## Risques prioritaires\n1. progression d’un utilisateur visible par un autre\n2. quiz validé avec mauvais seuil\n3. certificat émis sans examen réussi\n4. sitemap sans nouvelle leçon publiée\n5. route privée indexable par erreur\n\n## Tests ajoutés\n- isolation progression user A/B\n- scoring quiz limite 69/70/100\n- certificat exige examen et identité\n- sitemap contient URL canonique\n- dashboard noindex et 401 sans auth\n\n## Preuve\n- chaque test échoue sur une mutation ciblée\n- durée totale < 20 s en CI rapide", ["Risques prioritaires", "isolation progression", "scoring quiz", "certificat", "sitemap", "dashboard noindex", "mutation ciblée", "< 20 s", "user A/B", "limite 69/70", "examen réussi", "URL canonique", "route privée", "noindex", "preuve mutation", "budget durée"], ["risk-based-testing", "regression-testing"], [terms.risk, terms.regression, terms.mutation]),
      quiz("testing-regression-quiz", ["Quiz : régression", "Quiz: regression"], [
        q("r1", ["Un test de régression part de quoi ?", "What does a regression test start from?"], [["Un bug ou risque concret", "A concrete bug or risk"], ["Une ligne au hasard", "A random line"], ["Un style personnel", "A personal style"]], "Un bug ou risque concret", ["Il protège un comportement qui a déjà coûté cher ou peut coûter cher.", "It protects behavior that already cost or could cost something."], ["regression-testing"]),
        q("r2", ["Que révèle mutation testing ?", "What does mutation testing reveal?"], [["Des assertions qui n’échouent pas quand la règle casse", "Assertions that do not fail when the rule breaks"], ["La couleur du terminal", "Terminal color"], ["Le nombre de commits", "Number of commits"]], "Des assertions qui n’échouent pas quand la règle casse", ["Si le code faux passe, le test ne protège pas assez.", "If wrong code passes, the test does not protect enough."], ["mutation-testing"]),
        q("r3", ["Pourquoi tester 69/70 ?", "Why test 69/70?"], [["Pour protéger la frontière du seuil", "To protect the threshold boundary"], ["Pour augmenter la couverture au hasard", "To increase coverage randomly"], ["Pour tester le CSS", "To test CSS"]], "Pour protéger la frontière du seuil", ["Les erreurs de comparaison apparaissent souvent aux limites.", "Comparison errors often appear at boundaries."], ["boundary-testing"])
      ])
    ]
  },
  {
    id: "testing-ui-reliability",
    title: ["UI, responsive et stabilité E2E", "UI, responsive, and E2E stability"],
    description: ["Tester l’expérience mobile/desktop sans créer une usine à flakes.", "Test mobile/desktop experience without creating a flake factory."],
    vocabulary: [terms.visual, terms.flake],
    lessons: [
      code("testing-responsive", ["Tester plusieurs viewports", "Test multiple viewports"], ["Vérifie les parcours critiques sur mobile, tablette et desktop avec la même intention.", "Verify critical journeys on mobile, tablet, and desktop with the same intent."], "for (const viewport of [{ width: 430, height: 932 }, { width: 768, height: 1024 }, { width: 1440, height: 900 }]) {\n  test(`catalog responsive ${viewport.width}`, async ({ page }) => {\n    await page.setViewportSize(viewport);\n    await page.goto('/catalog');\n    await expect(page.getByRole('heading', { name: /formations/i })).toBeVisible();\n    await expect(page.getByRole('navigation')).toBeVisible();\n  });\n}", ["for (const viewport", "430", "768", "1440", "setViewportSize", "goto('/catalog')", "getByRole('heading'", "getByRole('navigation')"], ["responsive-testing", "e2e-testing"], [terms.visual]),
      code("testing-screenshot", ["Encadrer un test visuel", "Constrain a visual test"], ["Capture seulement une zone stable et masque les données variables.", "Capture only a stable region and mask variable data."], "await page.goto('/certificate/demo');\nconst certificate = page.getByRole('region', { name: /certificat/i });\nawait expect(certificate).toHaveScreenshot('certificate-premium.png', {\n  animations: 'disabled',\n  mask: [page.getByText(/émis le/i)],\n  maxDiffPixelRatio: 0.01\n});", ["toHaveScreenshot", "animations: 'disabled'", "mask:", "émis le", "maxDiffPixelRatio"], ["visual-regression-testing", "ui-quality"], [terms.visual]),
      text("testing-flake-runbook", ["Diagnostiquer un test instable", "Diagnose a flaky test"], ["Remplace l’attente temporelle par une preuve observable et garde les artefacts.", "Replace time waiting with observable evidence and keep artifacts."], ["Isoler seed, compte et données", "Conserver trace, vidéo et logs réseau", "Remplacer timeout fixe par locator/response attendu", "Désactiver animations non utiles", "Identifier dépendance partagée", "Ajouter retry seulement temporaire avec ticket"], ["flaky-test-debugging", "test-reliability"], [terms.flake]),
      project("testing-ui-project", ["Lab : suite UI mobile fiable", "Lab: reliable mobile UI suite"], ["Teste quiz, modale, navigation et certificat sur iPhone/desktop avec preuves visuelles contrôlées.", "Test quiz, modal, navigation, and certificate on iPhone/desktop with controlled visual evidence."], "# Suite UI fiable\n\n## Viewports\n- 430 x 932 iPhone Pro Max\n- 768 x 1024 tablette\n- 1440 x 900 desktop\n\n## Parcours\n1. ouvrir une leçon quiz\n2. répondre, valider, vérifier modale centrée\n3. reprendre au prochain contenu\n4. ouvrir certificat demo\n5. vérifier screenshot ciblé\n\n## Anti-flake\n- attendre roles/alertes, pas timeout fixe\n- masquer dates et données dynamiques\n- animations désactivées pour screenshots\n- trace conservée au premier échec", ["430 x 932", "modale centrée", "certificat demo", "screenshot ciblé", "pas timeout fixe", "masquer dates", "animations désactivées", "trace conservée", "768 x 1024", "1440 x 900", "répondre au quiz", "reprendre contenu", "roles/alertes", "données dynamiques", "premier échec", "preuve visuelle"], ["responsive-testing", "visual-regression-testing", "test-reliability"], [terms.visual, terms.flake]),
      quiz("testing-ui-quiz", ["Quiz : UI fiable", "Quiz: reliable UI"], [
        q("u1", ["Pourquoi masquer les dates dans un screenshot ?", "Why mask dates in a screenshot?"], [["Pour éviter un diff variable sans changement UI", "To avoid variable diffs without UI change"], ["Pour cacher une erreur", "To hide an error"], ["Pour réduire le HTML", "To reduce HTML"]], "Pour éviter un diff variable sans changement UI", ["Les données dynamiques rendent les captures bruyantes.", "Dynamic data makes screenshots noisy."], ["visual-regression-testing"]),
        q("u2", ["Quel viewport mobile garder pour PulsaTeach ?", "Which mobile viewport should PulsaTeach keep?"], [["430 × 932 pour iPhone Pro Max", "430 × 932 for iPhone Pro Max"], ["Uniquement 1920 × 1080", "Only 1920 × 1080"], ["Aucun, responsive automatique", "None, responsive is automatic"]], "430 × 932 pour iPhone Pro Max", ["Le bug utilisateur venait précisément de cette classe d’écran.", "The user bug came from that screen class."], ["responsive-testing"]),
        q("u3", ["Que faire d’un retry permanent ?", "What should you do with a permanent retry?"], [["Le remplacer par correction de cause", "Replace it with root-cause fix"], ["Le considérer comme qualité", "Treat it as quality"], ["Le multiplier par dix", "Multiply it by ten"]], "Le remplacer par correction de cause", ["Le retry masque le symptôme mais ne rend pas le test fiable.", "Retry hides the symptom but does not make the test reliable."], ["test-reliability"])
      ])
    ]
  }
];

function code(id, title, brief, solution, requirements, skills, vocabulary) {
  return { id, type: "text", title, brief, solution, requirements, skills, vocabulary };
}

function text(id, title, brief, requirements, skills, vocabulary) {
  return { id, type: "text", title, brief, solution: requirements.map((item) => `- ${item}`).join("\n"), requirements, skills, vocabulary };
}

function project(id, title, brief, solution, requirements, skills, vocabulary) {
  return { id, project: true, exerciseType: "text", title, brief, solution, requirements, skills, vocabulary, durationMin: 120, xp: 95 };
}

function quiz(id, title, questions, purpose = "module-review", passingScore = 75) {
  return { id, type: "quiz", title, questions, purpose, passingScore, brief: ["Choisis la preuve de test la plus robuste pour le risque réel.", "Choose the most robust test evidence for the real risk."] };
}

function q(id, prompt, options, answer, explanation, skills) {
  return { id, type: "single", prompt, choices: options.map((option) => ({ id: option[0], label: option })), answer, explanation, points: 1, skills, glossaryTerms: [] };
}
