const terms = {
  waterfall: ["waterfall réseau", "network waterfall", "Chronologie des requêtes montrant blocages, priorités et dépendances.", "Request timeline showing blocking, priorities, and dependencies."],
  mainThread: ["thread principal", "main thread", "Fil d’exécution qui parse, calcule les styles, layout, paint et JavaScript.", "Execution thread that parses, computes styles, lays out, paints, and runs JavaScript."],
  resourceHint: ["resource hint", "resource hint", "Indice donné au navigateur pour anticiper DNS, connexion ou téléchargement.", "Hint given to the browser to anticipate DNS, connection, or download."],
  fontDisplay: ["font-display", "font-display", "Stratégie d’affichage d’une police pendant son chargement.", "Font rendering strategy while the font is loading."],
  serviceWorker: ["service worker", "service worker", "Worker navigateur capable d’intercepter certaines requêtes et de gérer un cache applicatif.", "Browser worker able to intercept selected requests and manage an application cache."],
  rum: ["RUM", "RUM", "Mesure terrain agrégée depuis de vraies visites avec garde-fous de confidentialité.", "Field measurement aggregated from real visits with privacy guardrails."],
  trace: ["trace", "trace", "Enregistrement détaillé d’une interaction pour comprendre les tâches longues et rendus.", "Detailed recording of an interaction to understand long tasks and renders."]
};

export const webPerformanceModules = [
  {
    id: "perf-diagnostics",
    title: ["Diagnostic DevTools et priorisation", "DevTools diagnostics and prioritization"],
    description: ["Lire waterfall, trace, coverage et métriques avant de modifier le code.", "Read waterfall, traces, coverage, and metrics before changing code."],
    vocabulary: [terms.waterfall, terms.mainThread, terms.trace],
    lessons: [
      text("perf-diagnostics-map", ["Cartographier le chargement réel", "Map real loading"], ["Transforme une impression de lenteur en hypothèses vérifiables.", "Turn a slow feeling into verifiable hypotheses."], ["URL testée et profil réseau notés", "Waterfall sauvegardée", "Requêtes bloquantes entourées", "Tâches longues listées", "LCP element identifié", "Hypothèse de correction écrite"], ["performance-diagnostics", "network-waterfall"], [terms.waterfall, terms.trace]),
      code("perf-diagnostics-mark", ["Instrumenter une interaction", "Instrument an interaction"], ["Place des marques autour du scénario avant/après pour comparer sans deviner.", "Place marks around the before/after scenario to compare without guessing."], "performance.mark('catalog-filter:start');\nawait userFiltersCourses('react');\nperformance.mark('catalog-filter:end');\nperformance.measure('catalog-filter', 'catalog-filter:start', 'catalog-filter:end');\n\nconst [measure] = performance.getEntriesByName('catalog-filter');\nconsole.info({ durationMs: Math.round(measure.duration), scenario: 'catalog-filter' });", ["performance.mark", "catalog-filter:start", "performance.measure", "getEntriesByName", "durationMs", "scenario"], ["user-timing", "performance-diagnostics"], [terms.trace, terms.mainThread]),
      code("perf-diagnostics-coverage", ["Supprimer le code non utilisé", "Remove unused code"], ["Utilise Coverage et la route map pour retirer le JavaScript qui ne sert pas au premier écran.", "Use Coverage and the route map to remove JavaScript unused by the first viewport."], "const routes = {\n  home: () => import('./pages/HomePage.jsx'),\n  catalog: () => import('./pages/CatalogPage.jsx'),\n  studio: () => import('./pages/CourseStudioPage.jsx')\n};\n\nexport async function loadRoute(routeName) {\n  const loader = routes[routeName] ?? routes.home;\n  return loader();\n}", ["routes =", "() => import", "CourseStudioPage", "loadRoute", "routes.home"], ["coverage-audit", "route-code-splitting"], [terms.mainThread]),
      project("perf-diagnostics-project", ["Lab : rapport de diagnostic", "Lab: diagnostic report"], ["Livre un rapport court qui classe les problèmes par impact, effort et risque.", "Ship a short report ranking issues by impact, effort, and risk."], "# Diagnostic performance\n\n## Contexte\n- URL: /catalog\n- Appareil: mobile émulé, CPU x4, réseau fast 3G\n- Runs: 5, médiane conservée\n\n## Observations\n1. LCP = image héro 1,4 MB découverte tard\n2. 180 KB JS initial non utilisé sur /catalog\n3. API /api/catalog p95 520 ms, payload 95 KB\n\n## Priorisation\n| Problème | Impact | Effort | Risque | Action |\n| --- | --- | --- | --- | --- |\n| Image LCP | Fort | Moyen | Faible | AVIF + width/height + fetchpriority |\n| JS Studio | Moyen | Moyen | Moyen | import dynamique |\n| Payload API | Fort | Moyen | Moyen | projection + cache public court |\n\n## Preuves attendues\n- waterfall avant/après\n- trace interaction filtre\n- budget bundle en CI", ["URL:", "Runs:", "Observations", "Priorisation", "Image LCP", "import dynamique", "projection", "waterfall avant/après", "budget bundle"], ["performance-reporting", "prioritization"], [terms.waterfall, terms.trace]),
      quiz("perf-diagnostics-quiz", ["Quiz : diagnostiquer sans deviner", "Quiz: diagnose without guessing"], [
        q("d1", ["Quelle preuve vient avant une optimisation ?", "What evidence comes before an optimization?"], [["Une baseline reproductible", "A reproducible baseline"], ["Une préférence CSS", "A CSS preference"], ["Un composant renommé", "A renamed component"]], "Une baseline reproductible", ["Sans mesure, l’optimisation peut déplacer le problème ou l’aggraver.", "Without measurement, optimization can move or worsen the problem."], ["performance-diagnostics"]),
        q("d2", ["Que révèle surtout une waterfall ?", "What does a waterfall mainly reveal?"], [["Ordre, blocages et priorités des requêtes", "Request order, blocking, and priorities"], ["La qualité du wording", "Wording quality"], ["Les rôles utilisateurs", "User roles"]], "Ordre, blocages et priorités des requêtes", ["Elle montre quand une ressource est découverte et téléchargée.", "It shows when a resource is discovered and downloaded."], ["network-waterfall"]),
        q("d3", ["Pourquoi garder impact/effort/risque ?", "Why keep impact/effort/risk?"], [["Pour corriger d’abord ce qui change vraiment l’expérience", "To fix first what truly changes experience"], ["Pour éviter les tests", "To avoid tests"], ["Pour augmenter le nombre de commits", "To increase commit count"]], "Pour corriger d’abord ce qui change vraiment l’expérience", ["La performance est un arbitrage produit, pas une chasse au micro-score.", "Performance is a product tradeoff, not a micro-score hunt."], ["prioritization"])
      ])
    ]
  },
  {
    id: "perf-assets-fonts",
    title: ["Images, polices et ressources critiques", "Images, fonts, and critical resources"],
    description: ["Faire charger vite ce qui compte, sans flash brutal ni layout instable.", "Load what matters quickly without harsh flashes or unstable layout."],
    vocabulary: [terms.resourceHint, terms.fontDisplay],
    lessons: [
      code("perf-assets-picture", ["Construire une image responsive", "Build a responsive image"], ["Adapte format, largeur et priorité à la position réelle dans la page.", "Adapt format, width, and priority to the image’s real page position."], "<picture>\n  <source srcset=\"/courses-480.avif 480w, /courses-960.avif 960w\" type=\"image/avif\" sizes=\"(max-width: 640px) 92vw, 44vw\" />\n  <source srcset=\"/courses-480.webp 480w, /courses-960.webp 960w\" type=\"image/webp\" sizes=\"(max-width: 640px) 92vw, 44vw\" />\n  <img src=\"/courses-960.jpg\" width=\"960\" height=\"640\" loading=\"eager\" fetchpriority=\"high\" decoding=\"async\" alt=\"Interface de cours PulsaTeach\" />\n</picture>", ["<picture>", "srcset=", "type=\"image/avif\"", "sizes=", "width=\"960\"", "height=\"640\"", "fetchpriority=\"high\"", "decoding=\"async\""], ["image-performance", "largest-contentful-paint"], [terms.resourceHint]),
      code("perf-assets-fonts", ["Charger une police sans casser le texte", "Load a font without breaking text"], ["Précharge une seule graisse critique et garde un fallback proche.", "Preload one critical weight and keep a close fallback."], "@font-face {\n  font-family: 'PulsaDisplay';\n  src: url('/fonts/pulsa-display.woff2') format('woff2');\n  font-weight: 700;\n  font-display: swap;\n}\n\n:root { font-family: PulsaDisplay, Inter, system-ui, sans-serif; }\n.hero-title { letter-spacing: -0.04em; text-wrap: balance; }", ["@font-face", "woff2", "font-weight: 700", "font-display: swap", "system-ui", "text-wrap: balance"], ["font-loading", "visual-stability"], [terms.fontDisplay]),
      code("perf-assets-hints", ["Utiliser les resource hints avec sobriété", "Use resource hints sparingly"], ["Anticipe uniquement les domaines et ressources vraiment nécessaires au premier écran.", "Anticipate only domains and resources truly needed by the first viewport."], "<link rel=\"preconnect\" href=\"https://images.example-cdn.com\" crossorigin />\n<link rel=\"dns-prefetch\" href=\"https://api.pulsateach.app\" />\n<link rel=\"preload\" href=\"/assets/hero.avif\" as=\"image\" imagesrcset=\"/assets/hero-640.avif 640w, /assets/hero-1280.avif 1280w\" imagesizes=\"100vw\" />", ["rel=\"preconnect\"", "crossorigin", "dns-prefetch", "rel=\"preload\"", "as=\"image\"", "imagesrcset", "imagesizes"], ["resource-hints", "critical-rendering"], [terms.resourceHint]),
      project("perf-assets-project", ["Lab : page média premium", "Lab: premium media page"], ["Optimise une landing riche en visuels sans gonfler le premier chargement.", "Optimize a visual landing page without bloating the first load."], "<main class=\"landing\">\n  <section class=\"hero\">\n    <h1>Apprendre le web en construisant</h1>\n    <picture>\n      <source srcset=\"/hero-640.avif 640w, /hero-1280.avif 1280w\" type=\"image/avif\" sizes=\"100vw\" />\n      <img src=\"/hero-1280.jpg\" width=\"1280\" height=\"720\" fetchpriority=\"high\" decoding=\"async\" alt=\"Cours interactif avec éditeur\" />\n    </picture>\n  </section>\n  <img src=\"/preview.webp\" width=\"800\" height=\"600\" loading=\"lazy\" decoding=\"async\" alt=\"Aperçu d’un projet\" />\n</main>\n<style>.hero{min-height:clamp(520px,80vh,820px)}img{max-width:100%;height:auto}.landing{content-visibility:auto}</style>", ["<h1>", "srcset=", "width=\"1280\"", "height=\"720\"", "fetchpriority=\"high\"", "loading=\"lazy\"", "min-height:clamp", "content-visibility:auto"], ["landing-performance", "image-performance", "layout-stability"], [terms.resourceHint, terms.fontDisplay]),
      quiz("perf-assets-quiz", ["Quiz : ressources critiques", "Quiz: critical resources"], [
        q("a1", ["Quelle image ne doit généralement pas être lazy-loadée ?", "Which image should generally not be lazy-loaded?"], [["L’image LCP visible au premier écran", "The LCP image visible in the first viewport"], ["Une capture en bas de page", "A screenshot at page bottom"], ["Un avatar hors écran", "An offscreen avatar"]], "L’image LCP visible au premier écran", ["Elle doit être découverte tôt pour réduire le délai LCP.", "It must be discovered early to reduce LCP delay."], ["largest-contentful-paint"]),
        q("a2", ["À quoi sert font-display: swap ?", "What is font-display: swap for?"], [["Afficher rapidement un fallback lisible", "Show a readable fallback quickly"], ["Bloquer tout rendu", "Block all rendering"], ["Compresser la police", "Compress the font"]], "Afficher rapidement un fallback lisible", ["Le texte reste lisible pendant que la police arrive.", "Text remains readable while the font loads."], ["font-loading"]),
        q("a3", ["Quel risque avec trop de preloads ?", "What is the risk of too many preloads?"], [["Voler la bande passante aux ressources critiques", "Stealing bandwidth from critical resources"], ["Améliorer tous les scores automatiquement", "Automatically improving every score"], ["Supprimer le besoin de cache", "Removing the need for cache"]], "Voler la bande passante aux ressources critiques", ["Un hint est une priorité, pas une décoration.", "A hint is a priority, not decoration."], ["resource-hints"])
      ])
    ]
  },
  {
    id: "perf-pwa-observability",
    title: ["Cache applicatif, RUM et surveillance", "Application cache, RUM, and monitoring"],
    description: ["Accélérer les retours sans casser la fraîcheur ni la confidentialité.", "Speed up revisits without breaking freshness or privacy."],
    vocabulary: [terms.serviceWorker, terms.rum],
    lessons: [
      code("perf-pwa-cache", ["Stratégie service worker sûre", "Safe service worker strategy"], ["Cache les assets versionnés, revalide le contenu public et évite les données privées.", "Cache versioned assets, revalidate public content, and avoid private data."], "self.addEventListener('fetch', (event) => {\n  const url = new URL(event.request.url);\n  if (url.pathname.startsWith('/assets/')) {\n    event.respondWith(caches.open('assets-v1').then(async (cache) => cache.match(event.request) ?? cache.add(event.request).then(() => cache.match(event.request))));\n    return;\n  }\n  if (url.pathname.startsWith('/api/me')) return;\n  if (url.pathname.startsWith('/api/catalog')) event.respondWith(staleWhileRevalidate(event.request));\n});", ["fetch", "startsWith('/assets/')", "assets-v1", "cache.match", "startsWith('/api/me')", "staleWhileRevalidate"], ["service-worker-cache", "privacy-by-design"], [terms.serviceWorker]),
      code("perf-rum-web-vitals", ["Collecter les Web Vitals proprement", "Collect Web Vitals cleanly"], ["Envoie seulement des métriques agrégables, sans contenu personnel.", "Send only aggregate-friendly metrics, without personal content."], "import { onCLS, onINP, onLCP } from 'web-vitals';\n\nfunction report(metric) {\n  navigator.sendBeacon('/api/rum', JSON.stringify({\n    name: metric.name,\n    value: Math.round(metric.value),\n    rating: metric.rating,\n    page: location.pathname,\n    build: import.meta.env.VITE_BUILD_ID\n  }));\n}\n\nonLCP(report);\nonINP(report);\nonCLS(report);", ["onCLS", "onINP", "onLCP", "sendBeacon", "name:", "value:", "rating:", "page:", "VITE_BUILD_ID"], ["rum-monitoring", "web-vitals"], [terms.rum]),
      code("perf-alerts", ["Transformer les métriques en alertes", "Turn metrics into alerts"], ["Alerte sur tendance p75/p95, pas sur un run isolé.", "Alert on p75/p95 trend, not one isolated run."], "const thresholds = { LCP: 2500, INP: 200, CLS: 0.1 };\n\nfor (const metric of dailyWebVitals) {\n  const limit = thresholds[metric.name];\n  if (metric.p75 > limit && metric.samples >= 100) {\n    await notifyTeam({\n      title: `${metric.name} degraded`,\n      message: `p75=${metric.p75} exceeds ${limit} on ${metric.page}`,\n      runbook: '/docs/performance-runbook'\n    });\n  }\n}", ["thresholds", "p75", "samples >= 100", "notifyTeam", "runbook", "performance-runbook"], ["performance-alerting", "operations"], [terms.rum]),
      project("perf-pwa-observability-project", ["Projet final : performance en production", "Final project: production performance"], ["Livre cache, RUM, alertes et runbook pour un parcours critique.", "Ship cache, RUM, alerts, and a runbook for a critical journey."], "# Runbook performance production\n\n## Parcours critique\n- /catalog -> /learn/html -> quiz -> certificat\n\n## Cache\n- assets hashés: immutable 1 an\n- catalogue public: max-age 60 + stale-while-revalidate 300\n- progression utilisateur: no-store\n\n## RUM\n- LCP, INP, CLS agrégés par page et build\n- pas de texte saisi, pas d’email, pas d’identifiant brut\n- consentement respecté\n\n## Alertes\n- p75 LCP > 2500 ms avec au moins 100 échantillons\n- p75 INP > 200 ms avec au moins 100 échantillons\n- CLS > 0,10 sur deux jours\n\n## Procédure\n1. vérifier dernier déploiement\n2. comparer Lighthouse et RUM\n3. ouvrir trace DevTools\n4. corriger le goulot principal\n5. ajouter un budget anti-régression", ["Parcours critique", "immutable 1 an", "no-store", "LCP, INP, CLS", "pas d’email", "consentement", "p75 LCP", "dernier déploiement", "budget anti-régression"], ["production-readiness", "rum-monitoring", "runbook"], [terms.serviceWorker, terms.rum], true),
      quiz("perf-production-quiz", ["Quiz : performance en production", "Quiz: production performance"], [
        q("p1", ["Pourquoi ne pas cacher /api/me en cache partagé ?", "Why not cache /api/me in a shared cache?"], [["Parce que la réponse est privée par utilisateur", "Because the response is private per user"], ["Parce que JSON est lent", "Because JSON is slow"], ["Parce que HTTPS l’interdit", "Because HTTPS forbids it"]], "Parce que la réponse est privée par utilisateur", ["La performance ne doit jamais casser l’isolation des données.", "Performance must never break data isolation."], ["privacy-by-design"]),
        q("p2", ["Quel signal RUM est plus robuste ?", "Which RUM signal is more robust?"], [["p75 sur assez d’échantillons", "p75 over enough samples"], ["Un unique test local", "One local test"], ["Un screenshot", "A screenshot"]], "p75 sur assez d’échantillons", ["La tendance réduit le bruit des appareils et réseaux.", "The trend reduces device and network noise."], ["rum-monitoring"]),
        q("p3", ["Que doit contenir un runbook ?", "What should a runbook contain?"], [["Seuils, diagnostic, propriétaire et procédure", "Thresholds, diagnosis, owner, and procedure"], ["Un slogan marketing", "A marketing slogan"], ["Tous les secrets serveur", "All server secrets"]], "Seuils, diagnostic, propriétaire et procédure", ["Un incident doit pouvoir être traité vite et sans improviser.", "An incident must be handled quickly without improvising."], ["operations"])
      ])
    ]
  }
];

function code(id, title, brief, solution, requirements, skills, vocabulary) {
  const type = solution.trim().startsWith("<") ? "html" : solution.includes("select ") || solution.includes("create index") ? "sql" : solution.includes("function ") || solution.includes("import ") || solution.includes("self.addEventListener") ? "node" : "text";
  return { id, type, title, brief, solution, requirements, skills, vocabulary };
}

function text(id, title, brief, requirements, skills, vocabulary) {
  return { id, type: "text", title, brief, solution: requirements.map((item) => `- ${item}`).join("\n"), requirements, skills, vocabulary };
}

function project(id, title, brief, solution, requirements, skills, vocabulary, finalProject = false) {
  const exerciseType = solution.trim().startsWith("#") ? "text" : solution.trim().startsWith("<") ? "html" : "node";
  return { id, project: true, exerciseType, title, brief, solution, requirements, skills, vocabulary, durationMin: finalProject ? 220 : 120, xp: finalProject ? 155 : 95 };
}

function quiz(id, title, questions, purpose = "module-review", passingScore = 75) {
  return { id, type: "quiz", title, questions, purpose, passingScore, brief: ["Choisis la réponse qui protège la performance réelle et la qualité produit.", "Choose the answer that protects real performance and product quality."] };
}

function q(id, prompt, options, answer, explanation, skills) {
  return { id, type: "single", prompt, choices: options.map((option) => ({ id: option[0], label: option })), answer, explanation, points: 1, skills, glossaryTerms: [] };
}
