const pair = (fr, en) => ({ fr, en });

export const transferBriefs = {
  "html-transfer-survey": {
    title: pair("Enquête inclusive", "Inclusive survey"),
    brief: pair("Construis une enquête sur les habitudes de lecture avec des choix nommés et un consentement explicite.", "Build a reading-habits survey with named choices and explicit consent."),
    context: pair("Une bibliothèque souhaite connaître les formats préférés de ses lecteurs. La page doit expliquer quelles réponses sont demandées et permettre de choisir entre article et audio. Il s'agit d'une démonstration pédagogique : aucune inscription réelle ne doit être promise. Le destinataire de démonstration accepte les champs email, workshop et consent ; explique cette contrainte dans la page.", "A library wants to understand readers' preferred formats. Explain the requested answers and offer article and audio choices. This is an educational demonstration, not a real registration. The demo receiver accepts email, workshop and consent fields; explain that constraint on the page."),
    constraints: pair("Associe chaque contrôle à un libellé, regroupe le profil avec une légende et utilise un email requis. Le consentement ne doit jamais être précoché. Le bouton doit soumettre le formulaire ; un paragraphe statique ne constitue pas une confirmation d'envoi.", "Associate every control with a label, group the profile under a legend, and require a valid email. Never preselect consent. The button must submit the form; a static paragraph is not a submission confirmation."),
    evidence: pair("Tente un envoi vide, puis une adresse invalide. Vérifie que la validation native bloque ces deux cas. Dans l'aperçu, l'envoi est simulé localement et affiche les noms des champs sans transmettre de données. Inspecte les valeurs avec FormData. Pour tester la réponse HTTP, sers le document avec l'API locale. Distingue ces preuves d'un enregistrement durable.", "Try an empty submission, then an invalid email. Verify native validation blocks both. In the preview, submission is simulated locally and displays field names without transmitting data. Inspect values with FormData. To test the HTTP response, serve the document alongside the local API. Distinguish these checks from durable storage.")
  },
  "html-transfer-documentation": {
    title: pair("Documentation API", "API documentation"),
    brief: pair("Documente une authentification et une erreur 401 dans une page navigable au clavier.", "Document authentication and a 401 error in a keyboard-navigable page."),
    context: pair("Une équipe intègre une API et doit retrouver rapidement son mécanisme d'authentification ainsi que la signification d'une réponse 401. Écris une documentation courte mais exploitable : un exemple d'en-tête, une explication du jeton invalide et une navigation vers ces deux sujets. Le jeton montré doit rester une valeur fictive, jamais un secret réel.", "An integration team needs to locate the authentication mechanism and understand a 401 response. Provide a usable header example, explain an invalid token, and link to both topics. Show a fictional token, never an actual secret."),
    constraints: pair("Place le lien d'évitement avant la navigation. Chaque fragment doit résoudre un identifiant unique. Utilise pre et code pour conserver la forme de l'exemple, puis des titres hiérarchisés pour que les sections restent identifiables sans présentation graphique.", "Place the skip link before navigation. Every fragment must resolve to a unique identifier. Use pre and code to preserve the example, with hierarchical headings so sections remain recognizable without visual styling."),
    evidence: pair("Depuis le début de la page, active le lien d'évitement avec Entrée et vérifie le déplacement du focus au contenu. Teste ensuite chaque lien de section et consulte l'ordre des titres. Explique pourquoi une simple présence de href ne prouve pas qu'une destination existe.", "Activate the skip link with Enter and verify focus moves to the content. Test every section link and inspect heading order. Explain why merely having an href does not prove that its destination exists.")
  },
  "html-transfer-product": {
    title: pair("Fiche produit honnête", "Honest product page"),
    brief: pair("Présente une lampe fictive avec une illustration fidèle, un prix lisible et des conditions consultables.", "Present a fictional lamp with an accurate illustration, readable price and accessible delivery terms."),
    context: pair("Un catalogue de démonstration présente la lampe Atlas. Le lecteur doit comprendre ce qui est illustré, connaître le prix en euros et consulter les conditions de livraison. Annonce clairement que le produit et sa disponibilité sont fictifs. Aucune commande ne sera traitée : propose une consultation des conditions plutôt qu'un bouton d'achat inactif.", "A demonstration catalog presents the Atlas lamp. Readers must understand the illustration, the euro price and delivery terms. Clearly identify the fictional product and availability. No orders are processed; provide access to terms rather than an inactive purchase button."),
    constraints: pair("L'alternative de l'image doit décrire ce qui est réellement visible, sans inventer un objet absent. La valeur machine du prix doit correspondre au montant affiché. Utilise details et summary pour une ouverture native des conditions, sans script nécessaire.", "The image alternative must describe what is actually visible. The machine-readable price must match the displayed amount. Use details and summary to disclose terms natively without requiring a script."),
    evidence: pair("Compare l'illustration et son alternative, puis ouvre et referme les conditions au clavier. Vérifie que le prix garde son sens sans CSS. Dans ton compte rendu, distingue une illustration de démonstration d'une photographie contractuelle et explique pourquoi aucun achat n'est simulé.", "Compare the illustration with its alternative, then open and close terms using the keyboard. Check that the price makes sense without CSS. Distinguish a demo illustration from a contractual photograph and explain why no purchase is simulated.")
  },
  "html-transfer-legacy-repair": {
    title: pair("Réparation HTML legacy", "Legacy HTML repair"),
    brief: pair("Répare un rapport dont les titres, données tabulaires et liens ont perdu leur sémantique.", "Repair a report with broken heading, table and link semantics."),
    context: pair("Le rapport annuel existant présente ses données dans de simples blocs visuels. Les lecteurs ne peuvent pas identifier les colonnes ni retrouver les résultats par un lien interne. Conserve le contenu métier : trente participants au premier trimestre. Ta mission est de réparer les relations du document, pas de remplacer les données par un exemple différent.", "The existing annual report displays data in visual blocks. Readers cannot identify columns or follow an internal results link. Preserve the business data: thirty participants in the first quarter. Repair document relationships without replacing the data."),
    constraints: pair("Remplace les faux titres par une hiérarchie h1 puis h2. Donne au tableau une légende et des en-têtes de colonne avec scope. Répare la destination du lien et le nom accessible de la section en utilisant des identifiants uniques.", "Replace visual headings with h1 and h2. Give the table a caption and scoped column headers. Repair the link destination and accessible section name using unique identifiers."),
    evidence: pair("Décris trois défauts du document initial, puis associe chaque correction à un effet observable. Vérifie les données avant et après la réparation. Retire volontairement un identifiant pour confirmer que les contrôles détectent la régression, puis restaure la version correcte.", "Describe three original defects and connect each repair to an observable effect. Compare data before and after repair. Temporarily remove an identifier to confirm checks detect the regression, then restore the correct version.")
  }
};
