import { getPedagogy } from "./pedagogy.js";

const shell = (title, body) => `<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${title}</title><meta name="description" content="Projet HTML de transfert"></head><body>${body}</body></html>`;
const rubric = ["Le document répond au contexte sans réutiliser la structure PulsaConf.", "Les éléments natifs portent les relations importantes.", "Les contrôles et liens restent compréhensibles sans CSS.", "Le livrable explique une décision et une vérification effectuée."];

function project(id, title, brief, solution, tests, focus) {
  const course = { fr: { introduction: `Dans « ${title} », tu prends des décisions HTML pour ${focus}, sans reproduire un patron de conférence.`, sections: [{ title: "Contexte", paragraphs: [brief] }, { title: "Contraintes", paragraphs: ["Choisis les éléments pour leur sens, pas pour leur apparence."] }, { title: "Preuves", paragraphs: ["Vérifie le DOM, les relations et la lecture au clavier."] }] }, en: { introduction: `Build ${title} as an independent HTML artifact.`, sections: [{ title: "Context", paragraphs: [brief] }, { title: "Constraints", paragraphs: ["Use native semantics."] }, { title: "Evidence", paragraphs: ["Verify relationships and keyboard access."] }] } };
  const guide = { fr: { mistakes: [`Ne transforme pas ${focus} en une copie de PulsaConf.`] }, en: { mistakes: [`Do not turn ${focus} into a PulsaConf copy.`] } };
  const base = { course, guide, title: { fr: title, en: title }, brief: { fr: brief, en: "Build an independent HTML artifact with native semantics and observable evidence." }, type: "project" };
  return { id, type: "project", title: base.title, brief: base.brief, course, guide, pedagogy: getPedagogy(id, base), theory: { fr: { points: ["Le contexte détermine la structure.", "HTML natif fournit des contrats testables.", "Une preuve ne remplace pas une revue."], example: "" }, en: { points: ["Context determines structure.", "Native HTML provides testable contracts.", "Evidence does not replace review."], example: "" } }, skills: ["semantic-html", "accessibility", "independent-build"], difficulty: "project", durationMin: 120, starterCode: shell(title, "<main></main>"), solution, tests, rubric: { fr: rubric, en: rubric }, hint: { fr: "Écris le contenu et les landmarks avant les détails.", en: "Write content and landmarks before details." }, xp: 180 };
}

export const htmlTransferProjectModules = [{
  id: "html-transfer-projects", title: { fr: "Projets HTML de transfert", en: "HTML transfer projects" }, totalMinutes: 480,
  importance: { fr: "Prouver que les choix HTML survivent à un changement de contexte.", en: "Prove HTML decisions transfer across contexts." }, prerequisites: { fr: ["Parcours HTML principal terminé"], en: ["Complete the main HTML path"] }, outcomes: { fr: ["Structurer quatre produits distincts"], en: ["Structure four distinct products"] }, vocabulary: { fr: ["contrat", "contexte", "régression"], en: ["contract", "context", "regression"] }, mastery: { fr: "Choisir et défendre une structure native.", en: "Choose and defend native structure." },
  lessons: [
    project("html-transfer-survey", "Enquête inclusive", "un formulaire de recherche utilisateur", shell("Enquête", `<main><h1>Enquête de lecture</h1><form action="/api/pulsaconf/register" method="post"><fieldset><legend>Profil</legend><label for="email">Email</label><input id="email" name="email" type="email" required><label for="workshop">Format</label><select id="workshop" name="workshop"><option value="html">Article</option><option value="forms">Audio</option></select></fieldset><label><input type="checkbox" name="consent" required> J'accepte l'utilisation de mes réponses.</label><button type="submit">Envoyer</button><p role="status" aria-live="polite">Prêt.</p></form></main>`), [{ type: "labelsAssociated", label: "labels resolve" }, { type: "formControlsNamed", label: "controls are named" }, { type: "selector", label: "explicit consent", value: "input[name=consent][required]" }], "un formulaire de recherche"),
    project("html-transfer-documentation", "Documentation API", "une documentation technique navigable", shell("Documentation", `<a href="#main">Aller au contenu</a><header><h1>Guide API</h1><nav aria-label="Sections"><a href="#auth">Authentification</a><a href="#errors">Erreurs</a></nav></header><main id="main"><article><h2 id="auth">Authentification</h2><pre><code>Authorization: Bearer TOKEN</code></pre><h2 id="errors">Erreurs</h2><p>401 indique un jeton invalide.</p></article></main>`), [{ type: "validFragmentTargets", label: "targets resolve" }, { type: "selector", label: "skip link", value: "a[href='#main']" }, { type: "domOrder", label: "landmarks order", value: ["header", "main"] }], "une documentation technique"),
    project("html-transfer-product", "Fiche produit honnête", "une fiche produit sans fausse promesse", shell("Lampe Atlas", `<main><article><h1>Lampe Atlas</h1><figure><img src="/assets/logo_horizontale_optimized.webp" alt="Lampe Atlas dirigée vers un livre ouvert" width="640" height="360"><figcaption>Éclairage réglable.</figcaption></figure><p><data value="49.90">49,90 EUR</data></p><p><strong>En stock</strong></p><button type="button">Ajouter à ma liste</button><details><summary>Livraison</summary><p>Expédition sous trois jours.</p></details></article></main>`), [{ type: "documentSanity", label: "complete document" }, { type: "meaningfulAlt", label: "specific image alternative", value: { selector: "img" } }, { type: "selector", label: "machine price", value: "data[value]" }], "une fiche produit"),
    project("html-transfer-legacy-repair", "Réparation HTML legacy", "un rapport inaccessible à remettre en état", shell("Rapport", `<main><h1>Rapport annuel</h1><section aria-labelledby="results"><h2 id="results">Résultats</h2><table><caption>Progression trimestrielle</caption><thead><tr><th scope="col">Trimestre</th><th scope="col">Participants</th></tr></thead><tbody><tr><td>T1</td><td>30</td></tr></tbody></table><a href="#results">Relire les résultats</a></section></main>`), [{ type: "documentSanity", label: "complete document" }, { type: "validFragmentTargets", label: "link resolves" }, { type: "allMatch", label: "headers scoped", value: { selector: "thead th", matches: "[scope=col]" } }], "un HTML legacy"),
  ]
}];
