import { BookmarkCheck, CheckCircle2, Code2, Search } from "lucide-react";
import { filterLabel, isVisibleLesson } from "./learningState.js";
import LessonWorkspace from "./LessonWorkspace.jsx";

export function FocusedLearningLayout({ QuizComponent, locale, tracks, activeTrack, activeModule, activeLesson, activeTrackId, activeTrackCompleted, activeTrackTotal, progress, bookmarks, lessonQuery, statusFilter, syncState, trackLoadError, onTrackChange, onQueryChange, onFilterChange, onOpenLesson, onToggleBookmark, onComplete, onQuizResult, onNext, hasNext }) {
  return (
    <section id="learn" className="min-h-screen bg-slate-100 px-3 pb-5 pt-24 sm:px-5">
      <div className="mx-auto max-w-[1800px]">
        <header className="mb-3 flex flex-col justify-between gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm lg:flex-row lg:items-center">
          <div className="min-w-0"><div className="flex flex-wrap items-center gap-2 text-xs font-bold text-slate-500"><a href="/catalog" className="hover:text-indigoPop">{locale === "fr" ? "Formations" : "Courses"}</a><span>/</span><span>{activeTrack.title[locale]}</span><span>/</span><span>{activeModule.title[locale]}</span></div><h1 className="mt-1 truncate font-display text-xl font-bold text-ink sm:text-2xl">{activeLesson.title[locale]}</h1></div>
          <div className="flex flex-wrap items-center gap-2 text-sm"><span className="rounded-lg bg-slate-100 px-3 py-2 font-bold text-slate-600">{activeTrackCompleted}/{activeTrackTotal} {locale === "fr" ? "leçons" : "lessons"}</span><span className="rounded-lg bg-indigo-50 px-3 py-2 font-bold text-indigoPop">{progress.xp} XP</span><span className={`rounded-lg px-3 py-2 font-bold ${syncState === "synced" ? "bg-green-50 text-green-700" : "bg-amber-50 text-amber-700"}`}>{syncState}</span></div>
        </header>
        {trackLoadError && <p className="mb-3 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-800" role="alert">{trackLoadError}</p>}
        <div className="grid gap-3 xl:grid-cols-[300px_minmax(0,1fr)]">
          <aside className="min-w-0 max-h-[calc(100vh-7.5rem)] overflow-x-hidden overflow-y-auto rounded-2xl border border-slate-200 bg-white p-3 shadow-sm xl:sticky xl:top-24">
            <div className="grid grid-cols-3 gap-1">{tracks.map((track) => <button key={track.id} type="button" onClick={() => onTrackChange(track)} title={track.label} className={`min-w-0 truncate rounded-lg px-2 py-2 text-xs font-bold ${activeTrackId === track.id ? "bg-indigoPop text-white" : "bg-slate-100 text-slate-600 hover:bg-indigo-50 hover:text-indigoPop"}`}>{track.label}</button>)}</div>
            <label className="relative mt-3 block"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input type="search" value={lessonQuery} onChange={(event) => onQueryChange(event.target.value)} placeholder={locale === "fr" ? "Chercher une leçon" : "Search lessons"} className="min-h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm font-semibold outline-none focus:border-indigoPop" /></label>
            <div className="mt-2 grid grid-cols-4 gap-1">{["all", "todo", "done", "saved"].map((filter) => <button type="button" key={filter} onClick={() => onFilterChange(filter)} className={`rounded-lg px-1 py-2 text-[11px] font-bold ${statusFilter === filter ? "bg-ink text-white" : "text-slate-500 hover:bg-slate-100"}`}>{filterLabel(filter, locale)}</button>)}</div>
            <div className="mt-4 grid gap-4">{activeTrack.modules.map((module) => <div key={module.id}><div className="mb-1 flex items-center justify-between px-2"><h2 className="text-xs font-bold uppercase tracking-[.1em] text-slate-600">{module.title[locale]}</h2><span className="text-xs text-slate-600">{module.lessons.length}</span></div><div className="grid gap-1">{module.lessons.filter((lesson) => isVisibleLesson(lesson, progress, bookmarks, lessonQuery, statusFilter, locale)).map((lesson) => <button key={lesson.id} type="button" onClick={() => onOpenLesson(module.id, lesson.id)} className={`flex w-full items-start gap-2 rounded-lg px-2 py-2.5 text-left text-sm font-semibold ${lesson.id === activeLesson.id ? "bg-indigo-50 text-indigoPop" : "text-slate-600 hover:bg-slate-50 hover:text-ink"}`}>{progress.completed[lesson.id] ? <CheckCircle2 className="mt-0.5 size-4 shrink-0 text-green-600" /> : <Code2 className="mt-0.5 size-4 shrink-0 text-slate-400" />}<span>{lesson.title[locale]}</span>{bookmarks.includes(lesson.id) && <BookmarkCheck className="ml-auto size-4 shrink-0" />}</button>)}</div></div>)}</div>
          </aside>
          <LessonWorkspace QuizComponent={QuizComponent} activeTrack={activeTrack} activeModule={activeModule} lesson={activeLesson} locale={locale} isCompleted={Boolean(progress.completed[activeLesson.id])} isBookmarked={bookmarks.includes(activeLesson.id)} onToggleBookmark={onToggleBookmark} onComplete={onComplete} onQuizResult={onQuizResult} onNext={onNext} hasNext={hasNext} />
        </div>
      </div>
    </section>
  );
}

export function MissionBoard({ locale, progress, onOpenLesson }) {
  const missions = [
    { trackId: "html", moduleId: "html-a11y-final", lessonId: "html-12-final-project", title: { fr: "Publier PulsaConf", en: "Ship PulsaConf" }, text: { fr: "Assemble une page HTML complète avec navigation, programme, formulaire et footer.", en: "Assemble a complete HTML page with navigation, schedule, form, and footer." } },
    { trackId: "css", moduleId: "css-responsive-motion", lessonId: "css-06-final-project", title: { fr: "Styliser une landing", en: "Style a landing" }, text: { fr: "Crée les règles CSS qui donnent une vraie structure responsive à une landing.", en: "Create CSS rules that give a landing page a real responsive structure." } },
    { trackId: "javascript", moduleId: "js-storage-async", lessonId: "js-07-final-project", title: { fr: "Coder un dashboard", en: "Code a dashboard" }, text: { fr: "Pose le squelette logique avec state, render, addTask et sauvegarde locale.", en: "Build the logic skeleton with state, render, addTask, and local save." } }
  ];
  return <section className="mt-8 rounded-[30px] bg-white p-5 text-ink clay"><div className="mb-5 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-display text-lg font-bold text-orangePop">{locale === "fr" ? "Missions de projet" : "Project missions"}</p><h3 className="font-display text-3xl font-bold">{locale === "fr" ? "Saute directement vers un livrable." : "Jump straight into a deliverable."}</h3></div><p className="max-w-xl font-bold leading-7 text-ink/62">{locale === "fr" ? "Ces missions reprennent les projets du rapport et valident plusieurs compétences à la fois." : "These missions reuse the report projects and validate several skills at once."}</p></div><div className="grid gap-4 lg:grid-cols-3">{missions.map((mission) => <button type="button" key={mission.lessonId} onClick={() => onOpenLesson(mission)} className="cursor-pointer rounded-[24px] bg-cloud p-5 text-left transition-transform hover:-translate-y-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orangePop clay-soft"><div className="mb-4 flex items-center justify-between gap-3"><span className="rounded-2xl bg-indigoPop px-3 py-2 text-sm font-extrabold text-white">{mission.trackId.toUpperCase()}</span>{progress.completed[mission.lessonId] ? <CheckCircle2 className="size-6 text-mintPop" /> : <Code2 className="size-6 text-indigoPop" />}</div><h4 className="font-display text-2xl font-bold">{mission.title[locale]}</h4><p className="mt-2 font-bold leading-7 text-ink/68">{mission.text[locale]}</p></button>)}</div></section>;
}
