const fr = (why, objectives, prerequisites, vocabulary, good, bad, guided, autonomous, hints, correction, summary, next) => ({
  why,
  objectives,
  prerequisites,
  vocabulary,
  comparison: { good, bad },
  guided,
  autonomous,
  hints,
  correction,
  summary,
  next
});

const rule = (selector, declarations) => `${selector} {\n${declarations.map((line) => `  ${line}`).join("\n")}\n}`;

export const cssPedagogy = {
  "css-01-selectors": fr(
    "Un style fiable commence par une cible précise. Un sélecteur trop large modifie des éléments imprévus et rend les futures corrections risquées.",
    ["Lire un sélecteur simple", "Cibler une classe sans toucher aux autres cartes", "Vérifier la portée d'une règle"],
    ["Reconnaître une balise et un attribut class en HTML"],
    [["sélecteur", "Partie d'une règle qui choisit les éléments à styliser."], ["classe", "Nom réutilisable précédé d'un point en CSS."], ["déclaration", "Association entre une propriété et une valeur."]],
    { title: "Cible explicite", code: rule(".course-card", ["background: #eef2ff;", "border: 1px solid #6366f1;"]), explanation: "Seules les cartes portant la classe course-card reçoivent ces styles." },
    { title: "Cible trop large", code: rule("article", ["background: #eef2ff;"]), explanation: "Tous les articles du site changent, même ceux qui ne sont pas des cartes de cours." },
    ["Repère la classe présente sur les cartes de cours.", "Écris le sélecteur .course-card.", "Ajoute d'abord le fond, puis la bordure et observe uniquement les cartes concernées."],
    "Ajoute une classe featured-card à une seule carte dans l'aperçu, puis écris une règle qui la distingue sans modifier les autres.",
    ["Une classe CSS commence par un point.", "Le nom doit correspondre exactement à l'attribut class.", "Teste mentalement quels éléments correspondent avant d'ajouter une déclaration."],
    ["La règle commence par .course-card pour limiter sa portée.", "background rend la surface identifiable.", "border matérialise la limite du composant.", "Une cible précise réduit les effets de bord."],
    "Un sélecteur répond à la question : quels éléments cette règle a-t-elle le droit de modifier ?",
    "La prochaine leçon cible un élément selon sa relation directe avec son parent."
  ),
  "css-01-combinators": fr(
    "Deux boutons identiques peuvent avoir des rôles différents selon leur emplacement. Les combinateurs permettent de décrire cette relation sans ajouter une classe partout.",
    ["Comprendre la relation parent-enfant", "Utiliser le combinateur enfant direct >", "Éviter de cibler des descendants trop profonds"],
    ["Savoir écrire un sélecteur de classe"],
    [["descendant", "Élément situé n'importe où à l'intérieur d'un autre."], ["enfant direct", "Élément placé immédiatement dans son parent."], ["combinateur >", "Sélectionne uniquement les enfants directs."]],
    { title: "Relation maîtrisée", code: rule(".toolbar > button", ["background: #111827;", "border-radius: 0.75rem;"]), explanation: "Seuls les boutons immédiatement contenus dans toolbar sont ciblés." },
    { title: "Portée profonde", code: rule(".toolbar button", ["background: #111827;"]), explanation: "Cette règle touche aussi les boutons de composants imbriqués plus tard dans la toolbar." },
    ["Observe l'arbre HTML de la toolbar.", "Confirme que les boutons sont ses enfants directs.", "Place > entre .toolbar et button puis ajoute les déclarations."],
    "Crée une carte contenant elle-même un bouton et vérifie qu'une règle .panel > button ne touche pas ce bouton imbriqué.",
    ["Le symbole > décrit une relation immédiate.", "Un espace simple accepte tous les niveaux de profondeur.", "Choisis la relation la plus proche de l'intention du composant."],
    ["Le sélecteur part du parent .toolbar.", "> limite la recherche au niveau suivant.", "button indique le type d'enfant attendu.", "La règle résiste mieux à l'ajout de composants imbriqués."],
    "Les combinateurs ciblent une structure, pas seulement un nom.",
    "La prochaine leçon rend les boutons clairement utilisables au clavier."
  ),
  "css-01-states": fr(
    "Une interface doit montrer quel élément reçoit l'attention du clavier. Sans focus visible, une personne peut naviguer sans savoir où elle se trouve.",
    ["Différencier état normal et pseudo-classe", "Créer un focus fortement visible", "Utiliser focus-visible sans retirer l'indicateur natif sans remplacement"],
    ["Savoir cibler les boutons d'une toolbar"],
    [["pseudo-classe", "Mot-clé précédé de : qui cible un état."], ["focus", "Élément recevant actuellement les actions du clavier."], [":focus-visible", "État de focus affiché lorsque l'indicateur est utile, notamment au clavier."]],
    { title: "Focus perceptible", code: rule(".toolbar button:focus-visible", ["outline: 3px solid #f59e0b;", "outline-offset: 3px;"]), explanation: "Le contour contrasté reste séparé du bouton et facile à repérer." },
    { title: "Focus supprimé", code: rule("button:focus", ["outline: none;"]), explanation: "La navigation clavier devient invisible sans solution de remplacement." },
    ["Utilise Tab dans l'aperçu pour observer le focus actuel.", "Ajoute :focus-visible au sélecteur des boutons.", "Crée un outline contrasté puis éloigne-le avec outline-offset."],
    "Ajoute des états hover et focus-visible distincts à une carte cliquable, puis vérifie que le focus reste visible sans souris.",
    ["L'outline ne modifie pas la taille du bouton.", "outline-offset crée un espace autour du contrôle.", "Ne supprime jamais un focus sans le remplacer par un indicateur au moins aussi clair."],
    ["La pseudo-classe cible un moment précis de l'interaction.", "outline dessine l'indicateur.", "outline-offset évite qu'il se confonde avec la bordure.", "Le clavier doit rester testable visuellement."],
    "Un état interactif doit communiquer clairement ce qui est prêt à recevoir une action.",
    "Le quiz suivant vérifie comment le navigateur départage plusieurs règles."
  ),
  "css-01-specificity-quiz": fr(
    "Lorsque plusieurs règles ciblent le même élément, le navigateur doit choisir. Comprendre la spécificité évite de multiplier les !important et les sélecteurs difficiles à maintenir.",
    ["Comparer balise, classe et identifiant", "Expliquer pourquoi une règle gagne", "Préférer une architecture simple à une guerre de priorité"],
    ["Connaître les sélecteurs simples"],
    [["cascade", "Mécanisme qui détermine la déclaration finalement appliquée."], ["spécificité", "Poids d'un sélecteur dans la cascade."], ["identifiant", "Nom unique ciblé avec # et plus spécifique qu'une classe."]],
    { title: "Classes prévisibles", code: ".course-card { color: #334155; }\n.course-card.is-featured { color: #4338ca; }", explanation: "La variante est exprimée avec des classes lisibles et une spécificité modérée." },
    { title: "Escalade de priorité", code: "#catalog main .panel article.course-card { color: red !important; }", explanation: "Ce sélecteur devient coûteux à remplacer et cache l'intention réelle." },
    ["Classe les sélecteurs par catégorie : balise, classe, identifiant.", "Compare d'abord le nombre d'identifiants.", "Justifie ton choix avant de valider."],
    "Écris trois règles concurrentes pour une carte, prédis la couleur finale puis simplifie-les afin qu'une classe de variante gagne clairement.",
    ["Un identifiant pèse plus qu'une classe.", "Une classe pèse plus qu'une balise.", "À poids égal, la règle déclarée plus tard gagne."],
    ["#featured-card gagne car il contient un identifiant.", ".course-card arrive ensuite avec une classe.", "article possède seulement un sélecteur de type.", "Le meilleur code évite toutefois de dépendre d'identifiants pour styliser les composants."],
    "La spécificité explique quelle règle gagne ; une bonne architecture rend ce résultat facile à prévoir.",
    "Le module suivant construit des surfaces lisibles avec le modèle de boîte."
  ),
  "css-02-box-model": fr(
    "Chaque élément CSS est une boîte composée du contenu, de l'espace intérieur, de la bordure et de l'espace extérieur. Cette représentation explique la majorité des problèmes de dimensions.",
    ["Identifier les couches du modèle de boîte", "Créer une carte lisible", "Distinguer padding et margin"],
    ["Savoir cibler une classe"],
    [["contenu", "Zone occupée par le texte ou les médias."], ["padding", "Espace intérieur entre contenu et bordure."], ["bordure", "Limite visible de la boîte."], ["margin", "Espace extérieur séparant les boîtes."]],
    { title: "Surface structurée", code: rule(".card", ["padding: 1.5rem;", "border-radius: 1rem;", "box-shadow: 0 8px 24px rgb(15 23 42 / 12%);"]), explanation: "Le contenu respire, la forme est cohérente et l'ombre indique l'élévation." },
    { title: "Espacement confondu", code: rule(".card", ["margin: 1.5rem;"]), explanation: "La marge sépare la carte des autres, mais ne crée aucun espace entre son texte et ses bords." },
    ["Ajoute padding et observe l'espace à l'intérieur.", "Arrondis ensuite les coins.", "Ajoute une ombre légère et vérifie qu'elle ne gêne pas la lecture."],
    "Crée deux variantes de carte : une compacte pour une liste et une confortable pour une fiche détaillée.",
    ["Le padding agit à l'intérieur de la bordure.", "La marge agit entre les éléments.", "Une ombre discrète suffit à signaler une surface élevée."],
    ["padding protège le contenu des bords.", "border-radius définit la forme des coins.", "box-shadow ajoute une profondeur visuelle sans modifier la taille.", "Chaque couche remplit un rôle différent."],
    "Le modèle de boîte permet de raisonner sur l'espace au lieu d'ajuster des valeurs au hasard.",
    "La prochaine leçon rend le texte confortable à lire."
  ),
  "css-02-typography": fr(
    "Une interface peut être techniquement correcte et rester pénible à lire. La taille, l'interligne et la longueur des lignes déterminent directement le confort.",
    ["Régler une taille de texte lisible", "Utiliser un interligne adapté", "Limiter la longueur des lignes"],
    ["Comprendre le modèle de boîte"],
    [["font-size", "Taille des caractères."], ["line-height", "Hauteur de chaque ligne de texte."], ["mesure", "Longueur visuelle d'une ligne de texte."], ["ch", "Unité approximativement basée sur la largeur d'un caractère."]],
    { title: "Bloc lisible", code: rule(".demo-surface", ["font-size: 1rem;", "line-height: 1.6;", "max-width: 65ch;"]), explanation: "Le texte garde une taille normale, des lignes aérées et une longueur maîtrisée." },
    { title: "Texte tassé", code: rule(".demo-surface", ["font-size: 11px;", "line-height: 1;"]), explanation: "Les caractères sont petits et les lignes se touchent presque." },
    ["Commence avec font-size: 1rem.", "Augmente line-height jusqu'à distinguer clairement les lignes.", "Limite ensuite le bloc avec max-width: 65ch."],
    "Compose une fiche de lecture avec un titre, un paragraphe long et des métadonnées dont la hiérarchie reste claire sans couleur.",
    ["1rem respecte généralement la préférence de taille de l'utilisateur.", "Une line-height sans unité s'adapte à la taille du texte.", "65ch constitue un bon point de départ, pas une règle absolue."],
    ["font-size définit l'échelle de base.", "line-height crée le rythme vertical du texte.", "max-width empêche les lignes trop longues.", "La lisibilité se vérifie avec un vrai paragraphe."],
    "Une bonne typographie guide la lecture avant même d'ajouter des couleurs.",
    "La prochaine leçon centralise les décisions visuelles avec des variables CSS."
  ),
  "css-02-custom-properties": fr(
    "Répéter une couleur dans vingt règles rend chaque changement lent et incohérent. Une propriété personnalisée nomme une décision de design et la rend réutilisable.",
    ["Déclarer une variable dans :root", "Lire une variable avec var()", "Nommer une intention plutôt qu'une couleur brute"],
    ["Savoir écrire des déclarations CSS"],
    [["propriété personnalisée", "Variable CSS dont le nom commence par --."], [":root", "Racine du document, souvent utilisée pour les variables globales."], ["var()", "Fonction qui lit la valeur d'une propriété personnalisée."]],
    { title: "Décision nommée", code: ":root {\n  --color-accent: #facc15;\n}\n\n.card {\n  background: var(--color-accent);\n}", explanation: "La carte dépend d'un rôle visuel nommé, modifiable depuis un seul endroit." },
    { title: "Valeur répétée", code: ".card { background: #facc15; }\n.badge { background: #facc15; }\n.button { border-color: #facc15; }", explanation: "Changer l'accent exige de retrouver toutes les occurrences." },
    ["Déclare --accent dans :root.", "Remplace la couleur brute de la carte par var(--accent).", "Change la variable une fois et observe tous les usages."],
    "Crée un petit thème avec des variables pour surface, texte, accent, espace et rayon, puis applique-le à deux composants.",
    ["Le nom commence par deux tirets.", "var(--accent) lit la valeur.", "Un nom comme --color-accent décrit mieux le rôle que --yellow."],
    ["La variable est déclarée une fois dans :root.", "var() la réutilise dans le composant.", "Un changement global reste cohérent.", "Les noms sémantiques survivent mieux aux changements de palette."],
    "Les variables CSS transforment des valeurs isolées en système visuel.",
    "La prochaine leçon construit des largeurs fluides qui restent confortables."
  ),
  "css-02-sizing": fr(
    "Une largeur fixe adaptée à un écran casse souvent sur un autre. Une taille fluide utilise l'espace disponible tout en gardant une limite de confort.",
    ["Combiner width et max-width", "Centrer un bloc avec les marges automatiques", "Éviter le débordement horizontal"],
    ["Comprendre contenu, padding et marge"],
    [["taille fluide", "Dimension qui s'adapte à l'espace disponible."], ["max-width", "Limite supérieure d'une largeur."], ["margin-inline", "Marges sur l'axe horizontal selon le sens d'écriture."]],
    { title: "Conteneur fluide", code: rule(".demo-surface", ["width: min(100% - 2rem, 70rem);", "margin-inline: auto;"]), explanation: "Le bloc conserve une marge sur petit écran et ne dépasse jamais 70rem." },
    { title: "Largeur rigide", code: rule(".demo-surface", ["width: 1100px;"]), explanation: "Le bloc déborde sur tous les écrans plus étroits que 1100 pixels." },
    ["Donne d'abord width: 100% au bloc.", "Ajoute max-width pour limiter les grands écrans.", "Centre-le avec margin-inline: auto et vérifie une petite largeur."],
    "Crée un conteneur de lecture fluide et un bandeau pleine largeur contenant ce même conteneur.",
    ["100% utilise la largeur disponible.", "max-width pose une limite.", "auto partage l'espace restant des deux côtés."],
    ["La largeur fluide évite une valeur unique pour tous les écrans.", "La limite protège la lisibilité.", "Les marges automatiques centrent le conteneur.", "Le test doit inclure une fenêtre étroite."],
    "Une interface responsive commence par des dimensions flexibles, avant toute media query.",
    "La prochaine leçon protège la mise en page contre les contenus imprévus."
  ),
  "css-02-overflow": fr(
    "Les vrais contenus contiennent parfois une URL interminable, un nom inattendu ou plus de texte que prévu. Une interface robuste doit absorber ces cas sans casser.",
    ["Reconnaître un débordement", "Autoriser les mots longs à se couper", "Choisir entre afficher, couper et faire défiler"],
    ["Comprendre les dimensions d'une boîte"],
    [["overflow", "Comportement du contenu qui dépasse une boîte."], ["overflow-wrap", "Autorise la coupure d'une chaîne trop longue."], ["scroll", "Défilement permettant d'accéder au contenu dépassant."]],
    { title: "Contenu résilient", code: rule(".card", ["overflow: auto;", "overflow-wrap: anywhere;"]), explanation: "Le contenu reste accessible et les longues chaînes peuvent se couper." },
    { title: "Contenu masqué", code: rule(".card", ["overflow: hidden;", "height: 80px;"]), explanation: "Une partie du texte peut devenir inaccessible sans avertissement." },
    ["Remplace un titre par une chaîne très longue.", "Ajoute overflow-wrap et observe la différence.", "Teste overflow: auto avec un contenu réellement plus grand."],
    "Construis une carte qui reste utilisable avec un titre long, un bloc de code horizontal et cinq paragraphes.",
    ["overflow-wrap protège surtout contre les chaînes sans espaces.", "auto ajoute un défilement seulement si nécessaire.", "hidden ne doit pas masquer une information utile."],
    ["Les contenus réels sont imprévisibles.", "overflow-wrap protège la largeur.", "overflow: auto conserve l'accès au surplus.", "Une hauteur fixe demande une justification forte."],
    "Un composant robuste reste lisible même lorsque son contenu dépasse les exemples idéaux.",
    "Le module suivant aligne les composants sur un axe avec Flexbox."
  ),
  "css-03-flexbox": fr(
    "Flexbox organise une série d'éléments sur un axe principal et gère facilement leur alignement et leur espacement.",
    ["Créer un conteneur flex", "Distinguer axe principal et axe secondaire", "Espacer les éléments avec gap"],
    ["Comprendre les dimensions et les sélecteurs"],
    [["conteneur flex", "Parent dont les enfants directs deviennent des éléments flex."], ["axe principal", "Direction définie par flex-direction."], ["axe secondaire", "Axe perpendiculaire à l'axe principal."], ["gap", "Espace constant entre les éléments."]],
    { title: "Groupe aligné", code: rule(".toolbar", ["display: flex;", "align-items: center;", "gap: 1rem;"]), explanation: "Les boutons deviennent des éléments flex, alignés et espacés par le parent." },
    { title: "Marges répétées", code: ".toolbar button { margin-right: 1rem; }\n.toolbar button:last-child { margin-right: 0; }", explanation: "L'espacement dépend de chaque enfant et exige une exception." },
    ["Active display: flex sur la toolbar.", "Ajoute gap pour séparer les boutons.", "Utilise align-items pour les aligner sur l'axe secondaire."],
    "Crée une ligne d'auteur avec avatar, texte et bouton d'action, puis explique quel axe contrôle chaque alignement.",
    ["Flexbox agit sur les enfants directs.", "La direction par défaut est row.", "gap appartient au parent et ne crée pas d'espace aux extrémités."],
    ["display: flex crée le contexte.", "gap gère l'espacement entre enfants.", "align-items centre sur l'axe secondaire.", "Le parent porte la logique de disposition."],
    "Flexbox est idéal quand la question principale est : comment répartir ces éléments sur une ligne ou une colonne ?",
    "La prochaine leçon permet aux éléments de revenir proprement à la ligne."
  ),
  "css-03-flex-wrap": fr(
    "Une ligne d'actions peut tenir sur un grand écran et déborder sur mobile. flex-wrap autorise une nouvelle ligne sans cacher ni comprimer excessivement les éléments.",
    ["Activer le retour à la ligne", "Conserver un espacement cohérent entre lignes", "Tester avec une largeur réduite"],
    ["Savoir créer un conteneur flex"],
    [["flex-wrap", "Autorise les éléments flex à passer sur plusieurs lignes."], ["nowrap", "Valeur par défaut qui conserve une seule ligne."], ["ligne flex", "Une rangée d'éléments dans un conteneur flex replié."]],
    { title: "Groupe adaptable", code: rule(".panel", ["display: flex;", "flex-wrap: wrap;", "gap: 1rem;"]), explanation: "Les cartes utilisent une nouvelle ligne lorsque l'espace manque." },
    { title: "Ligne forcée", code: rule(".panel", ["display: flex;", "flex-wrap: nowrap;"]), explanation: "Les cartes risquent de rétrécir excessivement ou de déborder." },
    ["Réduis la largeur de l'aperçu avant de modifier le code.", "Ajoute flex-wrap: wrap.", "Ajoute gap puis vérifie l'espace horizontal et vertical."],
    "Crée une liste de tags qui revient sur plusieurs lignes sans couper le texte des tags.",
    ["wrap n'agit que dans un contexte flex.", "gap espace aussi les différentes lignes.", "Teste avec davantage d'éléments que dans l'exemple initial."],
    ["display: flex crée la ligne.", "flex-wrap autorise plusieurs lignes.", "gap maintient le rythme dans les deux directions.", "Le contenu reste visible sur petit écran."],
    "Un layout flexible prévoit ce qui arrive lorsque l'espace devient insuffisant.",
    "La prochaine leçon répartit deux groupes aux extrémités d'une navbar."
  ),
  "css-03-space-between": fr(
    "Une navbar contient souvent une identité à gauche et des actions à droite. justify-content distribue l'espace disponible sur l'axe principal.",
    ["Utiliser justify-content", "Différencier distribution et espacement constant", "Construire une navbar stable"],
    ["Comprendre les axes de Flexbox"],
    [["justify-content", "Distribue les éléments sur l'axe principal."], ["space-between", "Place le premier et le dernier élément aux extrémités."], ["distribution", "Répartition de l'espace libre dans un conteneur."]],
    { title: "Deux pôles", code: rule(".toolbar", ["display: flex;", "align-items: center;", "justify-content: space-between;", "gap: 1rem;"]), explanation: "Les groupes occupent les extrémités tout en gardant un espace minimal." },
    { title: "Positionnement fragile", code: ".actions { margin-left: 600px; }", explanation: "La valeur ne s'adapte ni au texte ni à la largeur de l'écran." },
    ["Active Flexbox sur la toolbar.", "Ajoute justify-content: space-between.", "Ajoute align-items et gap puis réduis la largeur."],
    "Construis un en-tête avec logo, navigation et profil ; groupe correctement les éléments avant de les distribuer.",
    ["space-between agit entre les enfants directs.", "Regroupe les actions qui doivent rester ensemble.", "gap protège l'espacement minimal lorsque la largeur diminue."],
    ["Le parent définit l'axe.", "space-between distribue l'espace restant.", "align-items harmonise l'axe secondaire.", "Les groupes HTML doivent refléter les groupes visuels."],
    "La distribution fonctionne bien lorsque la structure HTML exprime déjà les bons groupes.",
    "Le mini-projet suivant assemble toutes les notions Flexbox dans une navbar responsive."
  ),
  "css-03-mini-project-navbar": fr(
    "Une navbar est un composant réel qui combine alignement, distribution, repli et zones cliquables confortables.",
    ["Transformer un brief en règles Flexbox", "Gérer les petits écrans sans masquer d'action", "Vérifier l'état clavier des boutons"],
    ["Avoir terminé les leçons Flexbox du module"],
    [["barre de navigation", "Zone regroupant identité, destinations et actions."], ["zone cliquable", "Surface qui déclenche l'action d'un contrôle."], ["critère d'acceptation", "Condition vérifiable nécessaire pour valider le composant."]],
    { title: "Navbar résiliente", code: rule(".toolbar", ["display: flex;", "align-items: center;", "justify-content: space-between;", "flex-wrap: wrap;", "gap: 1rem;"]), explanation: "La disposition fonctionne sur une ligne et peut se replier lorsque l'espace manque." },
    { title: "Navbar figée", code: rule(".toolbar", ["display: flex;", "width: 1200px;"]), explanation: "La largeur imposée ignore les petits écrans et le contenu variable." },
    ["Liste les cinq propriétés attendues avant de coder.", "Construis d'abord le layout du parent.", "Agrandis les boutons puis teste le repli et le clavier."],
    "Personnalise la navbar avec deux groupes d'actions et ajoute un état focus-visible cohérent avec son identité visuelle.",
    ["Commence par display, alignement et distribution.", "Ajoute wrap avant de tester une petite largeur.", "Le padding du bouton agrandit sa zone cliquable."],
    ["Le parent porte display, align-items, justify-content, wrap et gap.", "Les boutons reçoivent leur propre padding et leur forme.", "Le test à largeur réduite confirme la robustesse.", "Le clavier confirme l'utilisabilité."],
    "Le mini-projet est maîtrisé lorsque la navbar reste claire, utilisable et sans débordement à toutes les largeurs.",
    "Le module suivant compose des mises en page sur deux dimensions avec Grid."
  ),
  "css-04-grid": fr(
    "Grid permet de définir simultanément des colonnes et des lignes. Il convient aux galeries et pages où les éléments doivent former une structure bidimensionnelle.",
    ["Créer un conteneur grid", "Générer des colonnes avec repeat", "Construire une grille fluide avec minmax"],
    ["Comprendre les tailles fluides"],
    [["grille", "Système de lignes et colonnes."], ["piste", "Ligne ou colonne d'une grille."], ["repeat()", "Fonction répétant une définition de piste."], ["minmax()", "Définit une taille minimale et maximale."]],
    { title: "Colonnes adaptatives", code: rule(".gallery", ["display: grid;", "grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr));", "gap: 1rem;"]), explanation: "Le nombre de colonnes s'adapte, chaque carte garde une largeur minimale puis partage l'espace." },
    { title: "Colonnes rigides", code: rule(".gallery", ["display: grid;", "grid-template-columns: 300px 300px 300px;"]), explanation: "La grille exige toujours 900 pixels, même lorsque l'écran est plus étroit." },
    ["Active display: grid.", "Définis d'abord trois colonnes égales avec repeat.", "Remplace ensuite le nombre fixe par auto-fit et minmax."],
    "Crée une galerie qui accepte entre deux et dix cartes sans media query et sans colonne trop étroite.",
    ["1fr représente une part de l'espace disponible.", "minmax protège la largeur minimale.", "auto-fit adapte le nombre de pistes à l'espace."],
    ["display: grid crée le contexte.", "grid-template-columns décrit les colonnes.", "repeat évite les répétitions.", "minmax combine contrainte et flexibilité."],
    "Grid décrit la structure disponible ; les éléments s'y placent ensuite automatiquement.",
    "La prochaine leçon règle précisément les colonnes et leur espacement."
  ),
  "css-04-grid-gap": fr(
    "L'espacement fait partie de la grille. Le gérer sur le conteneur garantit un rythme constant sans ajouter de marges particulières à chaque carte.",
    ["Définir un nombre fixe de colonnes", "Créer des colonnes de même largeur avec fr", "Utiliser gap pour le rythme"],
    ["Savoir activer Grid"],
    [["grid-template-columns", "Décrit la largeur et le nombre des colonnes."], ["fr", "Fraction de l'espace disponible."], ["gap", "Gouttière entre lignes et colonnes."]],
    { title: "Rythme centralisé", code: rule(".gallery", ["display: grid;", "grid-template-columns: repeat(3, 1fr);", "gap: 1.5rem;"]), explanation: "Trois colonnes partagent l'espace et toutes les gouttières sont identiques." },
    { title: "Marges par carte", code: ".gallery { display: grid; }\n.gallery > * { margin: 12px; }", explanation: "Les bords extérieurs reçoivent aussi des marges et le rythme devient plus difficile à contrôler." },
    ["Déclare trois colonnes égales.", "Ajoute gap sur la galerie.", "Inspecte les espaces internes et compare-les aux bords du conteneur."],
    "Compose une grille éditoriale avec une grande gouttière entre colonnes et une gouttière plus petite entre lignes.",
    ["repeat(3, 1fr) signifie trois parts égales.", "gap appartient au conteneur.", "row-gap et column-gap permettent des valeurs différentes."],
    ["Les fractions partagent l'espace disponible.", "gap sépare uniquement les pistes.", "Le parent centralise la disposition.", "Les enfants restent indépendants du layout."],
    "Une grille cohérente sépare clairement la structure du conteneur et le style de ses cartes.",
    "La prochaine leçon aligne le contenu à l'intérieur des cellules."
  ),
  "css-04-place-items": fr(
    "Une cellule de grille peut être plus grande que son contenu. place-items contrôle en une déclaration l'alignement horizontal et vertical des éléments dans leurs cellules.",
    ["Comprendre l'espace d'une cellule", "Centrer les éléments avec place-items", "Éviter le positionnement absolu pour un centrage simple"],
    ["Savoir créer une grille"],
    [["align-items", "Aligne sur l'axe de bloc."], ["justify-items", "Aligne sur l'axe en ligne."], ["place-items", "Raccourci combinant align-items et justify-items."]],
    { title: "Centrage par la grille", code: rule(".gallery", ["display: grid;", "place-items: center;", "min-height: 20rem;"]), explanation: "Les éléments sont centrés dans des cellules disposant d'une hauteur visible." },
    { title: "Coordonnées manuelles", code: ".item { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); }", explanation: "Cette technique retire l'élément du flux alors que Grid sait déjà le centrer." },
    ["Donne une hauteur minimale visible à la galerie.", "Ajoute place-items: center.", "Remplace center par start puis end pour comprendre les axes."],
    "Crée un état vide centré dans une zone de dashboard, puis aligne son bouton différemment sans déplacer le texte.",
    ["Le centrage n'est visible que si la cellule possède de l'espace libre.", "place-items agit sur les éléments, pas sur toute la grille.", "place-self peut modifier un seul élément."],
    ["La grille conserve les éléments dans le flux.", "place-items combine deux axes.", "min-height révèle l'espace disponible.", "Les exceptions peuvent utiliser place-self."],
    "Grid permet d'aligner sans calculer manuellement des coordonnées.",
    "Le module suivant adapte les interfaces aux écrans et aux préférences utilisateur."
  ),
  "css-05-responsive": fr(
    "Une interface responsive adapte son organisation lorsque le contenu n'a plus assez d'espace. Une media query applique des règles seulement lorsque sa condition est vraie.",
    ["Lire une media query", "Choisir un breakpoint à partir du contenu", "Modifier le layout sans dupliquer tous les styles"],
    ["Comprendre les tailles fluides et Grid"],
    [["media query", "Bloc CSS conditionnel lié aux caractéristiques du média."], ["breakpoint", "Seuil où le layout doit changer."], ["min-width", "Condition vraie à partir d'une largeur minimale."]],
    { title: "Amélioration progressive", code: ".panel { display: block; }\n\n@media (min-width: 700px) {\n  .panel { display: grid; gap: 1rem; }\n}", explanation: "La version simple fonctionne partout puis devient une grille lorsque l'espace le permet." },
    { title: "Breakpoint arbitraire", code: "@media (min-width: 1920px) { .panel { display: grid; } }", explanation: "La majorité des écrans ne profite jamais de la disposition alors que le contenu pourrait tenir plus tôt." },
    ["Observe la version étroite.", "Ajoute la media query à 700px.", "Place uniquement les déclarations qui changent dans le bloc conditionnel."],
    "Trouve expérimentalement le breakpoint d'une grille de cartes : élargis jusqu'à ce que deux cartes puissent tenir confortablement, puis code ce seuil.",
    ["La syntaxe commence par @media.", "La condition est placée entre parenthèses.", "Ne répète pas les styles identiques avant et après le breakpoint."],
    ["Le style de base reste actif partout.", "La media query ajoute ou remplace quelques déclarations.", "Le seuil vient du besoin du contenu.", "Le test doit couvrir juste avant et juste après le breakpoint."],
    "Un breakpoint répond à un problème de contenu observé, pas au nom d'un appareil.",
    "La prochaine leçon organise toute la feuille de style selon l'approche mobile-first."
  ),
  "css-05-mobile-first": fr(
    "L'approche mobile-first commence par la version la plus contrainte et ajoute des améliorations lorsque l'espace augmente. Elle réduit les surcharges et force à prioriser l'essentiel.",
    ["Écrire la disposition mobile par défaut", "Ajouter une amélioration avec min-width", "Éviter de corriger une version desktop trop complexe"],
    ["Savoir écrire une media query"],
    [["mobile-first", "Stratégie où les styles de base servent aux petits espaces."], ["amélioration progressive", "Ajout de capacités sans casser la base."], ["surcharge", "Déclaration qui remplace une valeur précédente."]],
    { title: "Base simple", code: ".panel { display: grid; grid-template-columns: 1fr; }\n\n@media (min-width: 700px) {\n  .panel { grid-template-columns: repeat(3, 1fr); }\n}", explanation: "Une seule propriété change lorsque l'espace permet trois colonnes." },
    { title: "Corrections descendantes", code: ".panel { width: 1200px; grid-template-columns: repeat(4, 1fr); }\n@media (max-width: 700px) { .panel { width: auto; display: block; } }", explanation: "La version mobile doit annuler plusieurs décisions prises pour le grand écran." },
    ["Écris une colonne sans media query.", "Vérifie que tout reste utilisable sur une largeur étroite.", "Ajoute uniquement grid-template-columns dans la condition min-width."],
    "Construis une page qui passe successivement d'une colonne à deux puis quatre colonnes, avec le minimum de surcharges.",
    ["Les styles hors media query forment la base.", "min-width ajoute des capacités.", "Une bonne base mobile n'a pas besoin de connaître la largeur exacte de l'appareil."],
    ["La version étroite reçoit une structure simple.", "Les grands espaces enrichissent la disposition.", "Les surcharges restent limitées.", "Le contenu reste prioritaire à toutes les tailles."],
    "Mobile-first est une méthode de conception et d'organisation du CSS, pas seulement une syntaxe.",
    "La prochaine leçon ajoute une micro-interaction qui clarifie une action."
  ),
  "css-05-motion": fr(
    "Une animation utile explique un changement d'état ou confirme une action. Une transition courte peut rendre un bouton plus compréhensible sans ralentir l'utilisateur.",
    ["Créer une transition ciblée", "Définir un état hover", "Choisir un mouvement discret et performant"],
    ["Connaître les pseudo-classes"],
    [["transition", "Interpolation entre une valeur initiale et une valeur finale."], ["durée", "Temps nécessaire à la transition."], ["transform", "Transformation visuelle qui ne réorganise pas le layout."], ["hover", "État lorsque le pointeur survole un élément."]],
    { title: "Retour discret", code: ".toolbar button { transition: transform 180ms ease; }\n.toolbar button:hover { transform: translateY(-3px); }", explanation: "Seule la transformation nécessaire est animée pendant une durée courte." },
    { title: "Tout animer", code: ".toolbar button { transition: all 2s; }\n.toolbar button:hover { transform: translateY(-30px) rotate(20deg); }", explanation: "La transition lente et excessive distrait et peut animer des propriétés imprévues." },
    ["Définis la transition sur l'état de base.", "Ajoute ensuite :hover.", "Utilise une petite translation et compare plusieurs durées courtes."],
    "Ajoute une micro-interaction à une carte cliquable avec des états hover et focus-visible cohérents.",
    ["La transition vit sur l'état de base afin de fonctionner à l'aller et au retour.", "Nomme explicitement la propriété animée.", "transform est généralement plus fluide que top ou margin."],
    ["L'état de base annonce la transition.", "L'état hover fournit la valeur finale.", "Une durée courte garde l'interface réactive.", "Le mouvement doit soutenir le sens de l'action."],
    "Une bonne micro-interaction améliore la compréhension sans devenir le centre de l'attention.",
    "La prochaine leçon respecte les personnes qui préfèrent réduire les mouvements."
  ),
  "css-05-reduced-motion": fr(
    "Certaines animations provoquent gêne, nausée ou perte de concentration. La préférence reduced-motion permet d'offrir une expérience stable sans supprimer les informations.",
    ["Détecter la préférence utilisateur", "Désactiver ou réduire les mouvements non essentiels", "Conserver un retour d'état perceptible"],
    ["Savoir créer une transition"],
    [["prefers-reduced-motion", "Préférence système demandant moins de mouvements."], ["reduce", "Valeur indiquant que l'utilisateur souhaite réduire le mouvement."], ["mouvement essentiel", "Animation indispensable à la compréhension, à simplifier plutôt qu'à masquer."]],
    { title: "Préférence respectée", code: "@media (prefers-reduced-motion: reduce) {\n  * { transition-duration: 0.01ms; animation-duration: 0.01ms; }\n}", explanation: "Les mouvements deviennent imperceptibles tout en conservant les changements d'état." },
    { title: "Animation imposée", code: ".page { animation: spin 4s infinite; }", explanation: "L'animation continue ignore les préférences et ne peut pas être arrêtée." },
    ["Ajoute la media query reduced-motion.", "Désactive la transition du bouton.", "Vérifie que la couleur ou le contour continue d'indiquer l'état."],
    "Audite trois animations d'une interface et classe-les : supprimer, réduire ou conserver avec justification.",
    ["La condition exacte contient prefers-reduced-motion: reduce.", "Supprime le mouvement, pas le message.", "Un changement de couleur ou de contour peut conserver le retour utile."],
    ["La préférence vient du système de l'utilisateur.", "La media query adapte l'expérience.", "Les états restent perceptibles autrement.", "L'accessibilité fait partie du comportement normal du composant."],
    "Le mouvement est une amélioration optionnelle, jamais une obligation imposée à l'utilisateur.",
    "Le projet final assemble système visuel, layout responsive et interactions responsables."
  ),
  "css-06-final-project": fr(
    "La landing page finale transforme une structure HTML en interface cohérente et responsive. Elle valide la capacité à prendre des décisions visuelles reliées plutôt qu'à empiler des propriétés.",
    ["Planifier un système visuel minimal", "Assembler Grid, cartes et responsive", "Auditer lisibilité, focus et mouvement"],
    ["Avoir terminé tous les modules CSS", "Disposer d'une structure HTML sémantique"],
    [["système visuel", "Ensemble cohérent de couleurs, espacements, typographies et formes."], ["composant", "Élément réutilisable avec une responsabilité claire."], ["revue responsive", "Vérification du rendu à plusieurs largeurs et avec du contenu variable."]],
    { title: "Décisions reliées", code: ":root { --space: 1rem; --radius: 1rem; }\n.panel { display: grid; grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr)); gap: var(--space); }\n.card { padding: calc(var(--space) * 1.5); border-radius: var(--radius); }", explanation: "Le layout et les composants utilisent un petit système partagé et adaptable." },
    { title: "Valeurs sans système", code: ".card1 { padding: 13px; }\n.card2 { padding: 27px; }\n.card3 { padding: 19px; }", explanation: "Chaque carte prend une décision isolée, ce qui produit une interface incohérente." },
    ["Définis d'abord les variables essentielles.", "Construis la grille et les cartes sans animation.", "Ajoute les états interactifs puis vérifie mobile, clavier et reduced-motion."],
    "Personnalise entièrement la landing, ajoute une section témoignages et documente cinq décisions de design avec leur raison.",
    ["Valide d'abord le layout principal.", "Réutilise les mêmes espacements et rayons.", "Teste avec une largeur étroite et des textes plus longs.", "Le mouvement doit avoir une alternative réduite."],
    ["La grille auto-fit adapte les colonnes.", "Les cartes partagent espace, forme et ombre.", "Les transitions ciblent seulement les propriétés utiles.", "La revue finale vérifie contenu, écrans et préférences."],
    "Le projet est réussi lorsqu'il reste cohérent, lisible et utilisable face aux variations de contenu, d'écran et de préférences.",
    "Après validation, JavaScript ajoutera des comportements et des données à cette interface robuste."
  )
};

export function getCssPedagogy(id) {
  return cssPedagogy[id] ? { fr: cssPedagogy[id] } : null;
}
