const fr = (why, objectives, prerequisites, vocabulary, good, bad, guided, autonomous, hints, correction, summary, next) => ({
  why,
  objectives,
  prerequisites,
  vocabulary,
  comparison: { good, bad },
  guided,
  autonomous,
  hints,
  correction,
  summary,
  next
});

export const htmlPedagogy = {
  "html-01-document-skeleton": fr(
    "Toutes les pages du web reposent sur ce squelette. Le maîtriser évite les problèmes d'affichage, d'accessibilité et de référencement dès la première ligne.",
    ["Reconnaître les zones obligatoires d'un document", "Distinguer les métadonnées du contenu visible", "Créer une page valide sans modèle"],
    ["Aucun prérequis technique"],
    [["doctype", "Déclaration qui active le mode HTML moderne."], ["racine", "Élément html qui contient tout le document."], ["métadonnée", "Information décrivant la page sans apparaître dans son contenu principal."]],
    { title: "Structure explicite", code: "<!doctype html>\n<html lang=\"fr\">\n  <head><meta charset=\"UTF-8\" /><title>Portfolio de Lina</title></head>\n  <body><h1>Portfolio de Lina</h1></body>\n</html>", explanation: "Chaque information est placée dans la zone qui correspond à son rôle." },
    { title: "Structure ambiguë", code: "<html>\n  <title>Page</title>\n  <h1>Bonjour</h1>\n</html>", explanation: "Il manque le doctype, la langue, l'encodage et la séparation entre head et body." },
    ["Ajoute d'abord le doctype et l'attribut lang.", "Complète ensuite head avec charset et title.", "Termine par un h1 visible dans body."],
    "Crée depuis une page vide le squelette d'un portfolio personnel avec un title précis et un h1 différent du title.",
    ["Le doctype est la toute première ligne.", "lang est un attribut de html.", "charset et title vivent dans head.", "Le h1 visible vit dans body."],
    ["Le navigateur reçoit d'abord la déclaration de document.", "html englobe head et body.", "head configure la page ; body porte son contenu.", "title nomme l'onglet alors que h1 nomme le contenu principal."],
    "Une page fiable commence par une structure explicite : doctype, langue, encodage, titre d'onglet et contenu visible.",
    "La prochaine leçon organise le contenu visible avec une hiérarchie de titres et de paragraphes."
  ),
  "html-02-text-content": fr(
    "Un lecteur doit pouvoir comprendre une page en parcourant ses titres et paragraphes. Une bonne hiérarchie rend le contenu lisible pour tous.",
    ["Construire une hiérarchie de titres logique", "Différencier importance et emphase", "Découper un texte en paragraphes utiles"],
    ["Connaître head et body"],
    [["h1–h6", "Niveaux de titres qui structurent le plan du document."], ["strong", "Importance forte dans le sens du texte."], ["em", "Emphase qui modifie le sens ou le ton."]],
    { title: "Plan lisible", code: "<h1>Guide du jardinage</h1>\n<h2>Choisir ses plantes</h2>\n<p><strong>Commence petit</strong> et observe la lumière.</p>", explanation: "Le h2 dépend clairement du sujet principal annoncé par h1." },
    { title: "Titres choisis pour leur taille", code: "<h4>Guide du jardinage</h4>\n<h1>Choisir ses plantes</h1>\n<b>Commence petit</b>", explanation: "Les niveaux sont inversés et b ne communique pas l'importance sémantique de strong." },
    ["Écris le sujet général dans un seul h1.", "Ajoute un h2 pour la première grande partie.", "Sépare les idées en paragraphes puis marque seulement les mots réellement importants."],
    "Rédige une courte fiche de recette avec un h1, deux sections h2, trois paragraphes, une information strong et une emphase em.",
    ["Commence par écrire uniquement les titres.", "Un paragraphe développe une idée principale.", "strong répond à « ceci est important » ; em répond à « insiste sur ce mot »."],
    ["Le h1 annonce le sujet principal.", "Les h2 organisent les grandes parties.", "Les paragraphes rendent les idées distinctes.", "strong et em ajoutent du sens, pas seulement du style."],
    "La hiérarchie des titres forme le sommaire implicite de la page.",
    "La prochaine leçon ajoute du contenu que l'utilisateur peut ouvrir et fermer sans JavaScript."
  ),
  "html-02-details-summary": fr(
    "Les composants natifs réduisent le JavaScript à écrire et restent utilisables au clavier. details et summary créent une divulgation accessible prête à l'emploi.",
    ["Créer un bloc repliable natif", "Écrire un intitulé summary compréhensible", "Choisir quand masquer un contenu secondaire"],
    ["Savoir structurer titres et paragraphes"],
    [["details", "Conteneur qui peut être ouvert ou fermé."], ["summary", "Intitulé interactif toujours visible."], ["attribut open", "Affiche un details ouvert par défaut."]],
    { title: "Question explicite", code: "<details>\n  <summary>Comment réinitialiser mon mot de passe ?</summary>\n  <p>Utilise le lien reçu par email.</p>\n</details>", explanation: "Le summary annonce précisément le contenu qui sera révélé." },
    { title: "Intitulé vague", code: "<div onclick=\"toggle()\">Clique ici</div>\n<div>Réponse cachée</div>", explanation: "Cette solution exige du JavaScript et ne communique pas naturellement son état." },
    ["Ajoute un details dans la section FAQ.", "Place la question dans summary.", "Place la réponse juste après dans un paragraphe."],
    "Crée une FAQ de trois questions, dont la première est ouverte par défaut.",
    ["summary doit être le premier enfant utile de details.", "Ajoute open sur details pour l'ouvrir.", "Chaque réponse doit rester compréhensible seule."],
    ["details gère automatiquement l'ouverture.", "summary est le contrôle interactif.", "Le contenu secondaire reste disponible sans surcharger la page."],
    "Utilise un composant HTML natif avant de recréer le même comportement en JavaScript.",
    "La prochaine leçon apprend à documenter le code et à afficher les caractères réservés."
  ),
  "html-02-comments-entities": fr(
    "Certains caractères ont un rôle dans la syntaxe HTML. Les entités permettent de les afficher comme du texte, tandis que les commentaires aident l'équipe à comprendre une décision.",
    ["Écrire un commentaire utile", "Afficher des caractères réservés", "Éviter de placer des informations sensibles dans les commentaires"],
    ["Comprendre les balises HTML"],
    [["commentaire", "Texte ignoré par le rendu mais visible dans le code source."], ["entité HTML", "Écriture spéciale représentant un caractère."], ["caractère réservé", "Symbole interprété par le parseur HTML."]],
    { title: "Commentaire utile", code: "<!-- Navigation secondaire utilisée sur les pages de cours -->\n<p>Écris &lt;h1&gt; pour créer un titre.</p>", explanation: "Le commentaire explique une intention et les chevrons sont affichés sans devenir une balise." },
    { title: "Secret exposé", code: "<!-- mot-de-passe-admin: secret123 -->", explanation: "Un commentaire reste visible dans le code source téléchargé par l'utilisateur." },
    ["Ajoute un commentaire qui explique la section.", "Remplace le chevron ouvrant par &lt;.", "Utilise &amp; pour afficher une esperluette."],
    "Écris un petit glossaire affichant littéralement <header>, <main>, & et ©.",
    ["Un commentaire utilise <!-- et -->.", "Une entité commence par & et finit par ;.", "Le navigateur affiche l'entité mais interprète une vraie balise."],
    ["Les commentaires documentent une intention, pas une évidence.", "Les entités protègent les caractères réservés.", "Aucun secret ne doit être envoyé dans le HTML."],
    "Le code source fait partie du produit : documente-le clairement et n'y place jamais de secret.",
    "Le module suivant relie les pages et organise la navigation."
  ),
  "html-03-links-navigation": fr(
    "Le web existe grâce aux liens. Un lien bien nommé permet de comprendre la destination avant de l'ouvrir et rend la navigation efficace au clavier ou avec un lecteur d'écran.",
    ["Créer des liens internes et externes", "Écrire des intitulés explicites", "Associer une ancre à un identifiant unique"],
    ["Connaître les attributs HTML", "Savoir créer des sections"],
    [["href", "Destination d'un lien."], ["ancre", "Lien pointant vers une position dans la page."], ["URL absolue", "Adresse complète incluant le protocole et le domaine."]],
    { title: "Destination annoncée", code: "<a href=\"#contact\">Contacter l'équipe</a>\n<a href=\"https://developer.mozilla.org/\">Consulter MDN</a>", explanation: "Chaque intitulé reste compréhensible hors contexte." },
    { title: "Lien vague", code: "<a href=\"#contact\">Clique ici</a>", explanation: "Une liste de liens « clique ici » ne permet pas de distinguer les destinations." },
    ["Ajoute id=\"contact\" à la section cible.", "Crée un lien dont href vaut #contact.", "Ajoute un second lien avec une URL complète et un texte descriptif."],
    "Crée une navigation vers trois sections de la page et un lien externe vers une ressource de référence.",
    ["Une ancre commence par #.", "La valeur après # doit correspondre exactement à un id.", "Décris l'action ou la destination dans le texte du lien."],
    ["href porte la destination.", "Les ancres relient des zones internes.", "Le texte du lien doit avoir du sens sans la phrase autour."],
    "Un bon lien répond immédiatement à la question : où vais-je arriver ?",
    "La prochaine leçon ajoute des images porteuses de sens."
  ),
  "html-04-images-media": fr(
    "Une image peut informer, décorer ou compléter un texte. Son alternative textuelle doit transmettre la même information essentielle aux personnes qui ne la voient pas.",
    ["Décider si une image est informative ou décorative", "Écrire un alt adapté au contexte", "Associer une légende avec figure et figcaption"],
    ["Savoir organiser une section"],
    [["alt", "Alternative textuelle d'une image."], ["figure", "Contenu autonome illustrant le document."], ["figcaption", "Légende associée à une figure."]],
    { title: "Alternative contextuelle", code: "<figure>\n  <img src=\"lina.jpg\" alt=\"Lina présente son prototype devant trois collègues\" />\n  <figcaption>Revue du prototype</figcaption>\n</figure>", explanation: "Le alt décrit l'information visuelle ; la légende explique son contexte." },
    { title: "Alt inutile", code: "<img src=\"lina.jpg\" alt=\"image photo jpg\" />", explanation: "Le texte ne transmet aucune information utile." },
    ["Place img dans figure.", "Décris dans alt ce qui est utile pour comprendre la page.", "Ajoute figcaption pour expliquer le contexte."],
    "Ajoute deux figures à un article : une image informative et une image décorative avec alt vide.",
    ["Ne commence pas par « image de ».", "Une image décorative utilise alt=\"\".", "La légende ne doit pas simplement répéter le alt."],
    ["alt remplace l'information visuelle.", "figure regroupe une illustration autonome.", "figcaption donne un contexte visible à tous."],
    "Le bon texte alternatif dépend de la raison pour laquelle l'image est présente.",
    "La prochaine leçon structure des collections et des étapes."
  ),
  "html-05-lists": fr(
    "Les listes rendent les collections et procédures immédiatement compréhensibles. Elles communiquent aussi leur structure aux technologies d'assistance.",
    ["Choisir entre liste ordonnée et non ordonnée", "Créer des éléments li valides", "Éviter les fausses listes faites avec des paragraphes"],
    ["Savoir écrire titres et paragraphes"],
    [["ul", "Liste dont l'ordre ne change pas le sens."], ["ol", "Liste dont l'ordre ou le rang est important."], ["li", "Élément appartenant à une liste."]],
    { title: "Type adapté au sens", code: "<ul><li>HTML</li><li>CSS</li></ul>\n<ol><li>Écrire</li><li>Tester</li><li>Publier</li></ol>", explanation: "Les compétences n'ont pas d'ordre, tandis que la publication suit des étapes." },
    { title: "Fausse liste", code: "<p>- HTML</p><p>- CSS</p>", explanation: "Visuellement proche, cette structure n'est pas annoncée comme une liste." },
    ["Écris un titre pour chaque collection.", "Utilise ul pour les compétences.", "Utilise ol pour les étapes et place chaque valeur dans li."],
    "Crée une liste de courses groupée par catégories et une procédure numérotée de préparation.",
    ["Demande-toi si changer l'ordre change le sens.", "li doit être enfant direct de ul ou ol.", "Une liste peut contenir des liens ou paragraphes complexes."],
    ["ul exprime un groupe.", "ol exprime une séquence ou un classement.", "li représente chaque membre."],
    "Le type de liste communique une relation, pas seulement des puces ou des numéros.",
    "La prochaine leçon construit un composant de contenu autonome."
  ),
  "html-05-card-metadata": fr(
    "Une carte de contenu rassemble un sujet autonome, ses métadonnées et une action. Une structure sémantique permet de la réutiliser dans un catalogue sans perdre son sens.",
    ["Utiliser article pour un contenu autonome", "Représenter une date avec time", "Stocker une donnée interne avec data-*"],
    ["Connaître titres, paragraphes et liens"],
    [["article", "Contenu autonome pouvant être distribué séparément."], ["time", "Date ou durée lisible par les machines."], ["data-*", "Attribut personnalisé destiné au code de l'application."]],
    { title: "Carte autonome", code: "<article data-level=\"starter\">\n  <h2>HTML Foundations</h2>\n  <time datetime=\"2026-05-05\">5 mai 2026</time>\n  <a href=\"#learn\">Commencer HTML Foundations</a>\n</article>", explanation: "La carte reste compréhensible lorsqu'elle est extraite de la page." },
    { title: "Métadonnées sans sens", code: "<div><b>Cours</b><span>05/05</span><a href=\"#\">Voir</a></div>", explanation: "La date n'est pas interprétable et le lien ne décrit pas sa destination." },
    ["Crée un article avec un h2 précis.", "Ajoute time avec datetime.", "Ajoute data-level et un lien décrivant le cours."],
    "Construis trois cartes de ressources avec titre, date de publication, niveau et lien explicite.",
    ["article doit avoir un sujet identifiable.", "datetime utilise une valeur normalisée.", "data-* ne remplace pas un attribut HTML existant."],
    ["article délimite un contenu autonome.", "time relie texte humain et valeur machine.", "data-* expose une donnée aux scripts ou styles."],
    "Une carte bien structurée reste utile dans une liste, un flux ou une page isolée.",
    "La prochaine leçon intègre des médias accessibles."
  ),
  "html-05-audio-video": fr(
    "Une vidéo sans contrôles ou sous-titres exclut des utilisateurs. HTML fournit les éléments nécessaires pour proposer plusieurs formats et une solution de repli.",
    ["Créer un média pilotable", "Fournir une source typée", "Ajouter des sous-titres et un contenu de repli"],
    ["Comprendre les attributs HTML"],
    [["controls", "Affiche les commandes natives du lecteur."], ["source", "Fichier média et son type."], ["track", "Piste textuelle comme des sous-titres."], ["fallback", "Contenu utilisé lorsque la fonctionnalité échoue."]],
    { title: "Vidéo utilisable", code: "<video controls>\n  <source src=\"intro.mp4\" type=\"video/mp4\" />\n  <track kind=\"captions\" src=\"intro-fr.vtt\" srclang=\"fr\" />\n  <p>Transcription de la présentation.</p>\n</video>", explanation: "L'utilisateur contrôle la lecture et dispose d'une piste textuelle." },
    { title: "Lecture imposée", code: "<video autoplay src=\"intro.mp4\"></video>", explanation: "La lecture automatique sans contrôle gêne de nombreux utilisateurs." },
    ["Ajoute video avec controls.", "Ajoute source avec un type MIME.", "Ajoute track captions puis un paragraphe de repli."],
    "Intègre une vidéo et un audio de cours, chacun avec commandes et alternative textuelle.",
    ["controls doit être placé sur video ou audio.", "kind=\"captions\" identifie les sous-titres.", "Le fallback se place entre les balises du média."],
    ["Les contrôles rendent le média opérable.", "source décrit les fichiers disponibles.", "track et le repli rendent l'information accessible."],
    "Un média n'est complet que si son contenu reste accessible sans image ou sans son.",
    "Le mini-projet suivant assemble navigation, texte, listes et média dans une page profil."
  ),
  "html-05-mini-project-profile": fr(
    "Ce premier livrable vérifie que tu peux transformer plusieurs notions isolées en une page cohérente et navigable.",
    ["Planifier une page avant de coder", "Assembler les éléments appris", "Relire le résultat comme un utilisateur"],
    ["Avoir terminé les leçons précédentes du module"],
    [["mini-projet", "Livrable limité servant à consolider plusieurs notions."], ["portfolio", "Sélection de travaux démontrant des compétences."], ["cohérence", "Relation logique entre structure, contenu et navigation d'une page."]],
    { title: "Page organisée", code: "<header>...</header>\n<main>\n  <section id=\"about\">...</section>\n  <section id=\"skills\">...</section>\n</main>\n<footer>...</footer>", explanation: "Les grandes zones sont identifiées avant de remplir les détails." },
    { title: "Accumulation sans plan", code: "<div>Nom image texte HTML CSS contact</div>", explanation: "Le contenu existe mais ses relations sont impossibles à comprendre." },
    ["Dessine les grandes zones : en-tête, contenu, pied de page.", "Ajoute les identifiants et liens de navigation.", "Complète ensuite biographie, figure, compétences et contact."],
    "Personnalise le profil avec ton propre sujet et ajoute une section projets contenant deux articles.",
    ["Commence par les éléments testés.", "Utilise un seul h1.", "Teste chaque lien interne après avoir créé sa cible."],
    ["Une page se planifie par zones.", "Chaque section possède un titre.", "Les liens, images et listes doivent rester explicites."],
    "Le mini-projet valide les fondations du contenu et de la navigation.",
    "Le module suivant présente les données et collecte des informations avec des formulaires."
  ),
  "html-06-tables": fr(
    "Un tableau sert à comparer des données ayant des relations entre lignes et colonnes. Il ne doit jamais servir à construire la mise en page.",
    ["Décider quand utiliser un tableau", "Associer en-têtes et cellules", "Ajouter un titre avec caption"],
    ["Savoir structurer du contenu"],
    [["table", "Structure de données en lignes et colonnes."], ["caption", "Titre ou résumé du tableau."], ["th", "Cellule d'en-tête."], ["scope", "Direction des cellules décrites par un en-tête."]],
    { title: "Données reliées", code: "<table>\n  <caption>Planning</caption>\n  <tr><th scope=\"col\">Jour</th><th scope=\"col\">Sujet</th></tr>\n  <tr><td>Lundi</td><td>HTML</td></tr>\n</table>", explanation: "caption donne le contexte et scope relie les en-têtes aux valeurs." },
    { title: "Tableau de mise en page", code: "<table><tr><td>Menu</td><td>Contenu</td></tr></table>", explanation: "Cette utilisation crée une structure trompeuse pour les technologies d'assistance." },
    ["Écris caption.", "Crée la ligne d'en-têtes avec th scope=\"col\".", "Ajoute au moins deux lignes de données avec td."],
    "Construis un tableau de comparaison de trois formations avec durée, niveau et projet final.",
    ["Chaque colonne a besoin d'un en-tête.", "caption explique le sujet global.", "Utilise CSS, pas table, pour une mise en page."],
    ["Un tableau exprime des relations de données.", "caption fournit le contexte.", "scope rend les associations explicites."],
    "Un tableau accessible permet de comprendre une cellule même sans voir sa position.",
    "La prochaine leçon crée le premier formulaire."
  ),
  "html-07-forms-basics": fr(
    "Un formulaire transforme une intention utilisateur en données. Sa qualité dépend d'abord de noms clairs, de champs adaptés et d'une action explicite.",
    ["Créer un formulaire minimal valide", "Relier label et input", "Choisir un type de champ adapté"],
    ["Connaître les attributs et les boutons"],
    [["form", "Zone qui regroupe des contrôles envoyant des données."], ["label", "Nom visible et accessible d'un contrôle."], ["input", "Contrôle de saisie."], ["name", "Clé utilisée lors de l'envoi de la valeur."]],
    { title: "Champ correctement nommé", code: "<label for=\"email\">Email professionnel</label>\n<input id=\"email\" name=\"email\" type=\"email\" required />", explanation: "for et id relient le texte au contrôle ; name prépare l'envoi." },
    { title: "Placeholder seul", code: "<input placeholder=\"Email\" />", explanation: "Le nom disparaît pendant la saisie et le type n'aide pas à valider l'adresse." },
    ["Ajoute label avec for=\"email\".", "Ajoute input avec l'id correspondant, name et type email.", "Ajoute un bouton type submit explicite."],
    "Crée un formulaire d'inscription avec nom, email et bouton, puis vérifie la navigation au clavier.",
    ["Le for du label égale l'id du champ.", "type=\"email\" améliore clavier et validation.", "Le bouton doit annoncer l'action."],
    ["Chaque champ a un label persistant.", "id relie le champ localement ; name identifie sa donnée envoyée.", "Le type doit correspondre à la valeur attendue."],
    "Un formulaire accessible commence par des contrôles natifs correctement nommés.",
    "La prochaine leçon organise la page avec des zones sémantiques."
  ),
  "html-09-semantic-layout": fr(
    "Les landmarks sémantiques permettent de parcourir rapidement une page et rendent son architecture explicite sans dépendre du CSS.",
    ["Choisir entre header, nav, main, section et footer", "Limiter la page à un main principal", "Remplacer les div génériques utiles"],
    ["Connaître titres, liens et sections"],
    [["landmark", "Grande région de page utilisable comme repère."], ["main", "Contenu principal unique du document."], ["section", "Partie thématique généralement nommée par un titre."]],
    { title: "Rôles explicites", code: "<header>...</header>\n<nav>...</nav>\n<main><section><h2>Sujet</h2></section></main>\n<footer>...</footer>", explanation: "Chaque grande zone expose directement son rôle." },
    { title: "Div partout", code: "<div class=\"header\"></div><div class=\"main\"></div>", explanation: "Les classes peuvent aider le CSS mais ne donnent aucun rôle natif." },
    ["Identifie les quatre grandes zones.", "Remplace-les par les éléments sémantiques adaptés.", "Ajoute un titre à chaque section thématique."],
    "Structure une page d'article avec en-tête, navigation, contenu principal, aside complémentaire et pied de page.",
    ["Il ne doit y avoir qu'un main principal.", "header et footer peuvent exister dans une page ou un article.", "Une section a généralement besoin d'un titre."],
    ["Les landmarks accélèrent la navigation.", "main contient le sujet principal.", "section regroupe un thème identifiable."],
    "Une structure sémantique est une documentation intégrée au document.",
    "La prochaine leçon organise des groupes de contrôles de formulaire."
  ),
  "html-09-fieldset-groups": fr(
    "Quand plusieurs contrôles répondent à une même question, leur relation doit être annoncée. fieldset et legend fournissent ce contexte.",
    ["Regrouper des contrôles liés", "Nommer un groupe avec legend", "Créer un groupe radio fonctionnel"],
    ["Savoir créer labels et inputs"],
    [["fieldset", "Groupe de contrôles liés."], ["legend", "Intitulé du groupe."], ["radio", "Choix exclusif parmi plusieurs options partageant le même name."]],
    { title: "Question annoncée", code: "<fieldset>\n  <legend>Rythme souhaité</legend>\n  <label><input type=\"radio\" name=\"pace\" value=\"calm\" /> Calme</label>\n</fieldset>", explanation: "La légende fournit la question commune et name relie les options." },
    { title: "Radios indépendants", code: "<input type=\"radio\" name=\"calm\" /> Calme\n<input type=\"radio\" name=\"fast\" /> Rapide", explanation: "Des names différents autorisent plusieurs choix alors que la question attend une seule réponse." },
    ["Crée fieldset dans form.", "Ajoute legend avant les contrôles.", "Donne le même name aux deux radios et une value différente."],
    "Crée deux fieldsets : un choix radio de niveau et un groupe de cases à cocher pour les sujets préférés.",
    ["legend nomme le groupe, pas un champ individuel.", "Les radios exclusifs partagent name.", "Chaque option garde un label."],
    ["fieldset crée une relation.", "legend explique la question commune.", "name contrôle le comportement du groupe radio."],
    "Un groupe accessible transmet la question même lorsque l'utilisateur parcourt directement ses options.",
    "La prochaine leçon ajoute des contraintes de saisie natives."
  ),
  "html-09-native-validation": fr(
    "La validation native empêche des erreurs simples avant l'envoi et donne un retour immédiat sans JavaScript, à condition d'expliquer les règles.",
    ["Utiliser required et les contraintes de longueur", "Écrire un pattern adapté", "Associer une aide avec aria-describedby"],
    ["Savoir créer un formulaire accessible"],
    [["required", "Indique qu'une valeur est obligatoire."], ["minlength / maxlength", "Bornes de longueur acceptées."], ["pattern", "Expression décrivant un format autorisé."], ["aria-describedby", "Relie un contrôle à un texte d'aide."]],
    { title: "Contraintes annoncées", code: "<input id=\"username\" required minlength=\"3\" maxlength=\"20\" pattern=\"[a-z0-9-]+\" aria-describedby=\"help\" />\n<p id=\"help\">3 à 20 caractères minuscules.</p>", explanation: "Les règles sont appliquées et expliquées avant l'erreur." },
    { title: "Règles cachées", code: "<input id=\"username\" pattern=\"[a-z0-9-]+\" />", explanation: "Le navigateur peut refuser la valeur sans que l'utilisateur sache ce qui est attendu." },
    ["Ajoute required et les bornes de longueur.", "Ajoute le pattern.", "Écris un texte d'aide puis relie-le avec aria-describedby."],
    "Crée un formulaire de création de mot de passe avec longueur minimale, confirmation textuelle des règles et champ obligatoire.",
    ["pattern valide le format, pas le sens métier.", "Le texte d'aide possède un id.", "aria-describedby reçoit cet id sans #."],
    ["Les contraintes natives réduisent les erreurs simples.", "Les règles doivent être visibles avant la validation.", "Une validation serveur reste toujours nécessaire."],
    "Une bonne validation aide à réussir au lieu de seulement signaler l'échec.",
    "Le module suivant approfondit l'accessibilité et prépare le projet final."
  ),
  "html-08-form-controls-validation": fr(
    "Un formulaire réel combine plusieurs types de contrôles. Chaque type doit correspondre à la décision demandée et rester clairement nommé.",
    ["Choisir entre input, select et checkbox", "Rendre les contrôles obligatoires de façon cohérente", "Construire un formulaire complet"],
    ["Maîtriser labels, groupes et validation native"],
    [["select", "Liste de choix prédéfinis."], ["option", "Choix disponible dans un select."], ["checkbox", "Choix indépendant activé ou désactivé."], ["consentement", "Accord explicite donné par l'utilisateur."]],
    { title: "Contrôles adaptés", code: "<label for=\"level\">Niveau</label>\n<select id=\"level\" name=\"level\"><option>Débutant</option></select>\n<label><input type=\"checkbox\" required /> J'accepte les conditions</label>", explanation: "Le niveau vient d'une liste et le consentement reste un choix explicite." },
    { title: "Tout en texte libre", code: "<input placeholder=\"Niveau et consentement\" />", explanation: "Le champ ne distingue pas les données et ne permet pas un consentement explicite." },
    ["Ajoute l'email requis.", "Ajoute select et ses options.", "Ajoute la checkbox dans son label puis le bouton submit."],
    "Crée un formulaire de préférences comprenant email, niveau, fréquence, sujets et consentement.",
    ["select convient aux choix limités.", "Une checkbox représente un oui/non indépendant.", "Le consentement obligatoire doit être explicite."],
    ["Le type de contrôle traduit la nature de la décision.", "Chaque valeur envoyée possède un name.", "Les contraintes importantes sont visibles."],
    "Un formulaire complet reste simple lorsque chaque contrôle répond à une seule question.",
    "La prochaine leçon annonce les changements dynamiques aux technologies d'assistance."
  ),
  "html-09-aria-status": fr(
    "Quand une action modifie la page sans rechargement, certains utilisateurs ne voient pas le changement. Une région de statut annonce le résultat sans déplacer le focus.",
    ["Comprendre une région live", "Choisir role=status et aria-live=polite", "Écrire un message utile et concis"],
    ["Connaître formulaires et retours utilisateur"],
    [["région live", "Zone dont les changements peuvent être annoncés automatiquement."], ["role=status", "Rôle destiné aux messages de résultat non urgents."], ["aria-live=polite", "Annonce lorsque le lecteur d'écran a terminé son message courant."]],
    { title: "Retour annoncé", code: "<p role=\"status\" aria-live=\"polite\">Exercice sauvegardé.</p>", explanation: "Le message est annoncé sans interrompre brutalement ni déplacer le focus." },
    { title: "Retour uniquement visuel", code: "<p class=\"green\">OK</p>", explanation: "La couleur et le mot vague ne décrivent pas clairement ce qui s'est passé." },
    ["Place un paragraphe après le bouton.", "Ajoute role=\"status\".", "Ajoute aria-live=\"polite\" et un message précis."],
    "Ajoute des régions de statut à un formulaire pour annoncer sauvegarde réussie et erreur de validation.",
    ["Un statut n'a pas besoin de recevoir le focus.", "polite convient aux informations non urgentes.", "Le message nomme l'action terminée."],
    ["Les changements dynamiques doivent être perceptibles.", "role=status convient aux confirmations.", "Le texte reste plus important que la couleur."],
    "Une interface accessible communique chaque changement important par plusieurs moyens.",
    "Le quiz suivant vérifie les principes essentiels d'accessibilité."
  ),
  "html-10-accessibility-quiz": fr(
    "L'accessibilité n'est pas une liste d'attributs : elle consiste à transmettre le même sens et permettre les mêmes actions à des utilisateurs différents.",
    ["Justifier le rôle d'un label", "Distinguer nom accessible et aide visuelle", "Choisir une solution native"],
    ["Avoir terminé les leçons de formulaires"],
    [["nom accessible", "Texte utilisé par les technologies d'assistance pour identifier un contrôle."], ["placeholder", "Exemple temporaire affiché dans un champ vide."], ["technologie d'assistance", "Outil aidant une personne à percevoir ou utiliser une interface."]],
    { title: "Nom persistant", code: "<label for=\"email\">Adresse email</label>\n<input id=\"email\" type=\"email\" />", explanation: "Le nom reste visible, cliquable et annoncé." },
    { title: "Aide temporaire", code: "<input placeholder=\"Adresse email\" />", explanation: "Le placeholder disparaît pendant la saisie et ne remplace pas un label." },
    ["Lis la question comme si tu utilisais uniquement le clavier.", "Élimine les réponses purement visuelles.", "Choisis celle qui conserve un nom persistant."],
    "Repère sur une page réelle trois contrôles et vérifie que chacun possède un nom accessible.",
    ["Un placeholder est une aide, pas un nom.", "La couleur ne donne pas de nom au champ.", "for et id créent une relation explicite."],
    ["L'accessibilité transmet du sens et des actions.", "Les éléments natifs offrent souvent la meilleure base.", "Une solution doit fonctionner au-delà de l'apparence."],
    "Le quiz confirme les principes avant l'optimisation SEO et l'audit final.",
    "La prochaine leçon prépare une page compréhensible par les moteurs de recherche."
  ),
  "html-11-seo-best-practices": fr(
    "Le SEO technique commence par aider une machine et un humain à comprendre rapidement le sujet de la page.",
    ["Écrire un title précis", "Rédiger une meta description utile", "Conserver un sujet principal clair avec h1"],
    ["Comprendre head et la hiérarchie des titres"],
    [["SEO", "Optimisation visant à rendre un contenu compréhensible et trouvable."], ["meta description", "Résumé proposé aux moteurs de recherche."], ["intention de recherche", "Besoin auquel la page tente de répondre."]],
    { title: "Sujet précis", code: "<title>Atelier HTML débutant | PulsaTeach</title>\n<meta name=\"description\" content=\"Apprends à structurer une première page HTML accessible.\" />\n<h1>Atelier HTML débutant</h1>", explanation: "Le titre, le résumé et le h1 décrivent le même sujet avec des rôles différents." },
    { title: "Métadonnées génériques", code: "<title>Page</title><meta name=\"description\" content=\"Bienvenue\" />", explanation: "Ces textes ne permettent pas de distinguer la page dans les résultats." },
    ["Décris le sujet et la valeur dans title.", "Résume le contenu dans meta description.", "Écris un h1 cohérent mais pas nécessairement identique."],
    "Optimise les métadonnées d'une page de recette puis celles d'une page de formation.",
    ["Le title doit rester spécifique.", "La description explique ce que l'utilisateur trouvera.", "Un seul sujet principal évite l'ambiguïté."],
    ["Le SEO commence par une structure claire.", "title identifie l'onglet et le résultat.", "La description résume la promesse de la page."],
    "Une page trouvable répond clairement à une intention précise.",
    "La prochaine leçon améliore la navigation clavier avec des landmarks et un lien d'évitement."
  ),
  "html-11-landmarks-skip-link": fr(
    "Les utilisateurs clavier parcourent parfois chaque lien de navigation avant d'atteindre le contenu. Un lien d'évitement leur permet d'aller directement à l'essentiel.",
    ["Créer un lien d'évitement fonctionnel", "Nommer une navigation", "Associer le lien à la région main"],
    ["Connaître les liens internes et landmarks"],
    [["lien d'évitement", "Premier lien permettant de sauter les éléments répétés."], ["aria-label", "Nom accessible ajouté lorsqu'aucun texte visible ne nomme une région."], ["destination d'ancre", "Élément identifié auquel un lien interne déplace la navigation."]],
    { title: "Raccourci fonctionnel", code: "<a href=\"#main-content\">Aller au contenu principal</a>\n<nav aria-label=\"Navigation principale\">...</nav>\n<main id=\"main-content\">...</main>", explanation: "Le lien cible réellement main et la navigation possède un nom." },
    { title: "Lien sans cible", code: "<a href=\"#content\">Passer</a>\n<main>...</main>", explanation: "L'id content n'existe pas, donc le raccourci ne fonctionne pas." },
    ["Place le lien avant la navigation.", "Ajoute id=\"main-content\" à main.", "Ajoute aria-label à nav si son nom n'est pas évident."],
    "Ajoute un lien d'évitement à une page comportant deux navigations et nomme chacune distinctement.",
    ["Le href doit correspondre exactement à un id.", "Le texte du lien décrit sa destination.", "Deux navigations similaires ont besoin de noms distincts."],
    ["Le lien d'évitement accélère la navigation clavier.", "Les landmarks servent de repères.", "Chaque destination doit exister et être clairement nommée."],
    "Une page efficace offre plusieurs chemins pour atteindre son contenu.",
    "Le projet d'audit suivant demande de détecter et corriger plusieurs problèmes."
  ),
  "html-11-accessibility-audit": fr(
    "Un audit transforme des règles isolées en capacité de diagnostic. Il faut repérer l'impact utilisateur, choisir la correction la plus simple puis vérifier qu'elle fonctionne.",
    ["Analyser une page existante", "Prioriser les problèmes bloquants", "Corriger avec des éléments natifs"],
    ["Avoir terminé les leçons HTML et accessibilité"],
    [["audit", "Examen systématique fondé sur des critères."], ["impact utilisateur", "Conséquence concrète d'un problème sur une personne."], ["remédiation", "Correction appliquée à un problème identifié."]],
    { title: "Correction par le sens", code: "<header><h1>Mon service</h1></header>\n<main><form><label for=\"email\">Email</label><input id=\"email\" type=\"email\" /><button>Envoyer</button></form></main>", explanation: "Les corrections utilisent les éléments natifs adaptés plutôt que des attributs ajoutés au hasard." },
    { title: "Patch superficiel", code: "<div role=\"heading\">Mon service</div><div role=\"button\">Envoyer</div>", explanation: "Les rôles ne recréent pas automatiquement tous les comportements des éléments natifs." },
    ["Liste d'abord les problèmes sans modifier le code.", "Corrige structure, noms et contrôles natifs.", "Relis au clavier et vérifie les tests."],
    "Audite une page de ton choix avec une grille : problème, utilisateur affecté, correction, vérification.",
    ["Commence par les blocages d'action.", "Préférer h1, button et label natifs.", "Une correction doit être testée, pas seulement écrite."],
    ["Un audit relie problème et impact.", "Le HTML natif simplifie la remédiation.", "La vérification confirme que la correction fonctionne."],
    "Savoir corriger une page existante est aussi important que savoir en créer une.",
    "Le projet final rassemble toutes les compétences du parcours."
  ),
  "html-12-final-project": fr(
    "PulsaConf est le livrable final : une page événementielle complète, navigable, accessible et structurée comme un vrai projet de portfolio.",
    ["Transformer un cahier des charges en architecture", "Assembler toutes les compétences HTML", "Effectuer une revue finale autonome"],
    ["Avoir terminé les modules HTML et l'audit"],
    [["cahier des charges", "Liste des besoins et contraintes du projet."], ["critère d'acceptation", "Condition vérifiable nécessaire pour valider le livrable."], ["revue finale", "Contrôle complet avant livraison."]],
    { title: "Construction par zones", code: "<header>...</header>\n<main>\n  <section id=\"about\">...</section>\n  <section id=\"schedule\">...</section>\n  <section id=\"register\">...</section>\n</main>\n<footer>...</footer>", explanation: "Le projet est découpé en zones testables avant d'ajouter les détails." },
    { title: "Construction en un bloc", code: "<div>titre menu programme image formulaire copyright</div>", explanation: "Sans architecture, les erreurs deviennent difficiles à isoler et le résultat est peu accessible." },
    ["Écris la liste des sections et leurs identifiants.", "Construis la navigation et les titres.", "Ajoute tableau, média et formulaire.", "Passe enfin l'audit accessibilité et SEO."],
    "Personnalise PulsaConf avec un vrai thème, plusieurs intervenants et une seconde page liée depuis la navigation.",
    ["Valide une zone à la fois.", "Réutilise les structures des mini-projets.", "Relis chaque critère avant de consulter la solution."],
    ["Le projet final doit fonctionner comme un document complet.", "Chaque zone possède un rôle et un titre.", "La qualité se vérifie avec les tests, le clavier et une relecture humaine."],
    "PulsaConf démontre que tu sais produire une page HTML autonome et présentable.",
    "Après validation, poursuis avec CSS pour transformer cette structure solide en interface responsive."
  )
};

export function getHtmlPedagogy(id) {
  return htmlPedagogy[id] ? { fr: htmlPedagogy[id] } : null;
}
