const lesson = ({ why, objectives, prerequisites, vocabulary, good, bad, guided, autonomous, hints, correction, summary, next }) => ({
  why, objectives, prerequisites, vocabulary, comparison: { good, bad }, guided, autonomous, hints, correction, summary, next
});

const item = (why, objectives, vocabulary, goodCode, goodExplanation, badCode, badExplanation, guided, autonomous, hints, correction, summary, next, prerequisites = ["Savoir lire quelques lignes de JavaScript"]) => lesson({
  why,
  objectives,
  prerequisites,
  vocabulary,
  good: { title: "Approche claire", code: goodCode, explanation: goodExplanation },
  bad: { title: "Approche fragile", code: badCode, explanation: badExplanation },
  guided,
  autonomous,
  hints,
  correction,
  summary,
  next
});

export const jsPedagogy = {
  "js-01-variables": item(
    "Un programme mémorise des informations pour les réutiliser et produire de nouvelles valeurs. Les variables donnent un nom compréhensible à ces informations.",
    ["Déclarer une constante", "Choisir un nom explicite", "Calculer une valeur à partir de données existantes"],
    [["valeur", "Information manipulée par le programme."], ["constante", "Nom associé une seule fois à une valeur."], ["expression", "Code qui produit une valeur."]],
    "const price = 12;\nconst quantity = 3;\nconst total = price * quantity;", "Chaque nom décrit son rôle et total exprime clairement le calcul.",
    "const a = 12;\nconst b = 3;\nconst c = 36;", "Les noms cachent le sens et la valeur finale est répétée au lieu d'être calculée.",
    ["Déclare price puis quantity.", "Crée total avec une multiplication.", "Modifie quantity et observe comment total reste cohérent."],
    "Calcule le prix TTC d'un panier à partir d'un sous-total et d'un taux de taxe.",
    ["Une déclaration commence par const.", "Le nom se place avant =.", "Réutilise price et quantity au lieu d'écrire directement 36."],
    ["price mémorise le prix unitaire.", "quantity mémorise le nombre d'articles.", "L'expression price * quantity produit le total.", "const total nomme le résultat."],
    "Une variable bien nommée rend le calcul lisible et évite de répéter des valeurs.",
    "La prochaine leçon prend une décision à partir d'une valeur.",
    ["Aucun prérequis JavaScript"]
  ),
  "js-01-conditionals": item(
    "Un programme utile ne répond pas toujours de la même façon : il choisit un chemin selon les données reçues.",
    ["Comparer une valeur", "Retourner un booléen", "Écrire une condition lisible dans une fonction"],
    [["condition", "Expression évaluée comme vraie ou fausse."], ["booléen", "Valeur true ou false."], ["opérateur >=", "Compare si la valeur de gauche est supérieure ou égale."]],
    "function canStart(age) {\n  return age >= 13;\n}", "La comparaison produit déjà le booléen attendu.",
    "function canStart(age) {\n  if (age >= 13) return true;\n  else return false;\n}", "Le résultat est correct mais la structure répète inutilement ce que produit la comparaison.",
    ["Teste mentalement 12, 13 et 14.", "Écris la comparaison age >= 13.", "Retourne directement son résultat."],
    "Crée isFreeShipping(total) qui retourne true à partir de 50 euros.",
    ["Le seuil est inclus, donc utilise >=.", "Une comparaison produit true ou false.", "return renvoie la valeur à l'appelant."],
    ["age est le paramètre reçu.", ">= compare l'âge au seuil inclus.", "La comparaison produit un booléen.", "return termine la fonction avec ce résultat."],
    "Une condition transforme une règle métier en décision vérifiable.",
    "La prochaine leçon construit un texte à partir de plusieurs valeurs."
  ),
  "js-01-strings-template": item(
    "Les interfaces affichent constamment des messages construits avec des données : nom, progression, prix ou statut.",
    ["Créer une chaîne", "Insérer des variables dans un template literal", "Produire un message naturel"],
    [["chaîne", "Suite de caractères représentant du texte."], ["template literal", "Chaîne entre accents graves autorisant des expressions."], ["interpolation", "Insertion d'une valeur avec ${...}."]],
    "const message = `${name} possède ${xp} XP.`;", "Le texte et les valeurs restent lisibles dans l'ordre final.",
    "const message = name + ' possède ' + xp + ' XP.';", "La concaténation fonctionne mais devient rapidement difficile à lire.",
    ["Repère name et xp.", "Ouvre une chaîne avec des accents graves.", "Insère chaque variable avec ${...}."],
    "Crée un résumé de commande contenant le produit, la quantité et le total.",
    ["Le template literal utilise ` et non une apostrophe.", "Chaque interpolation commence par ${.", "Ajoute la ponctuation destinée à l'utilisateur."],
    ["Les accents graves ouvrent le template.", "${name} insère le nom.", "${xp} insère le nombre.", "Le reste constitue le texte fixe."],
    "Les template literals gardent les messages dynamiques proches de leur rendu final.",
    "La prochaine leçon utilise la console pour observer l'exécution."
  ),
  "js-01-errors-console": item(
    "Déboguer consiste d'abord à observer ce que fait réellement le programme. La console permet de suivre les valeurs et de distinguer information et avertissement.",
    ["Afficher une information utile", "Produire un avertissement", "Éviter les logs sans contexte"],
    [["console", "Outil de développement affichant messages et erreurs."], ["log", "Message informatif."], ["warn", "Message signalant une situation à surveiller."]],
    "console.log('Leçon chargée :', lesson);\nconsole.warn('Progression non sauvegardée');", "Chaque message donne un contexte et utilise le niveau adapté.",
    "console.log(lesson);\nconsole.log('ici');", "Ces logs deviennent difficiles à reconnaître dans une vraie application.",
    ["Affiche lesson avec un libellé.", "Ajoute un avertissement expliquant un risque.", "Imagine le message parmi vingt autres logs."],
    "Instrumente un calcul de panier avec un log d'entrée, un résultat et un avertissement si le panier est vide.",
    ["Passe plusieurs arguments à console.log.", "Un avertissement doit expliquer la situation.", "Ne journalise jamais un secret."],
    ["console.log décrit le déroulement normal.", "Le libellé explique la valeur lesson.", "console.warn distingue une situation anormale.", "Les messages doivent aider à agir."],
    "Un bon log répond à : que s'est-il passé, avec quelle valeur, et pourquoi cela compte ?",
    "Le quiz suivant vérifie les types de valeurs fondamentales."
  ),
  "js-01-types-quiz": item(
    "Les opérations possibles dépendent du type d'une valeur. Distinguer texte, nombre et booléen évite des résultats surprenants.",
    ["Identifier les types primitifs courants", "Relier true et false au type boolean", "Justifier une réponse"],
    [["type", "Catégorie d'une valeur."], ["boolean", "Type contenant true ou false."], ["typeof", "Opérateur qui indique le type d'une valeur."]],
    "typeof true; // 'boolean'", "L'opérateur confirme que true représente un état logique.",
    "typeof 'true'; // 'string'", "Les guillemets transforment le mot en texte, ce n'est plus le booléen true.",
    ["Observe la présence éventuelle de guillemets.", "Demande-toi si la valeur représente du texte, une quantité ou un état.", "Vérifie avec typeof."],
    "Classe dix valeurs réelles d'une fiche utilisateur selon leur type.",
    ["true sans guillemets est un booléen.", "'true' avec guillemets est une chaîne.", "Un type décrit les opérations valides."],
    ["true est l'une des deux valeurs booléennes.", "Un booléen sert aux décisions.", "Les guillemets auraient créé une chaîne.", "typeof true renvoie boolean."],
    "Comprendre le type permet de prévoir le comportement d'une opération.",
    "Le module suivant organise la logique dans des fonctions réutilisables.",
    ["Avoir terminé les bases du langage"]
  ),
  "js-02-functions": item(
    "Une fonction rassemble une règle sous un nom afin de pouvoir l'utiliser, la tester et la modifier sans la recopier.",
    ["Déclarer une fonction", "Organiser plusieurs retours", "Transformer un score en niveau"],
    [["fonction", "Bloc de logique nommé et réutilisable."], ["appel", "Exécution d'une fonction."], ["return", "Valeur renvoyée par une fonction."]],
    "function getLevel(score) {\n  if (score < 100) return 'Starter';\n  if (score < 500) return 'Builder';\n  return 'Pre-junior';\n}", "Les cas sont évalués du seuil le plus bas au cas restant.",
    "let level;\nif (score < 100) level = 'Starter';", "La logique dépend d'une variable extérieure et n'est pas facilement réutilisable.",
    ["Écris la signature getLevel(score).", "Traite Starter puis Builder.", "Retourne le dernier niveau sans condition supplémentaire."],
    "Crée shippingCost(total) avec trois tarifs puis teste les valeurs aux limites.",
    ["Commence par les cas les plus faciles à exclure.", "return termine immédiatement l'appel.", "Teste exactement 99, 100, 499 et 500."],
    ["La fonction reçoit score.", "Le premier if traite les scores sous 100.", "Le second traite les scores restants sous 500.", "Le dernier return couvre tous les autres."],
    "Une fonction bien découpée donne un nom à une règle et rend ses cas limites testables.",
    "La prochaine leçon transmet plusieurs informations à une fonction."
  ),
  "js-02-parameters": item(
    "Les paramètres rendent une fonction adaptable : la même logique peut produire un résultat différent selon les données reçues.",
    ["Distinguer paramètre et argument", "Utiliser deux paramètres", "Retourner un résultat sans dépendance extérieure"],
    [["paramètre", "Nom déclaré dans la fonction."], ["argument", "Valeur fournie lors d'un appel."], ["fonction pure", "Fonction dont le résultat dépend uniquement de ses entrées."]],
    "function makeBadge(name, xp) {\n  return `${name} · ${xp} XP`;\n}", "La fonction décrit clairement ses deux besoins et retourne son résultat.",
    "let name = 'Maya';\nfunction makeBadge() { return `${name} XP`; }", "La fonction dépend d'une variable extérieure cachée et oublie l'XP.",
    ["Place name et xp entre les parenthèses.", "Construis le texte avec un template literal.", "Teste avec deux appels différents."],
    "Crée formatPrice(amount, currency) et utilise-la pour trois devises.",
    ["Les paramètres se séparent par une virgule.", "Ils sont disponibles seulement dans la fonction.", "Un appel fournit les arguments dans le même ordre."],
    ["name et xp sont les entrées explicites.", "Le template construit le badge.", "return fournit le texte à l'appelant.", "La fonction fonctionne avec n'importe quelles valeurs adaptées."],
    "Des paramètres explicites rendent une fonction plus réutilisable et plus facile à tester.",
    "La prochaine leçon prévoit une valeur lorsque l'argument manque."
  ),
  "js-02-default-parameters": item(
    "Une fonction peut recevoir une donnée absente. Une valeur par défaut définit un comportement clair plutôt que d'afficher undefined.",
    ["Déclarer un paramètre par défaut", "Comprendre quand il est utilisé", "Conserver un résultat valide sans argument"],
    [["valeur par défaut", "Valeur utilisée lorsque l'argument vaut undefined."], ["undefined", "Absence de valeur définie."], ["fallback", "Valeur de repli."]],
    "function greet(name = 'apprenant') {\n  return `Bonjour ${name}`;\n}", "L'appel greet() produit toujours un message compréhensible.",
    "function greet(name) {\n  return `Bonjour ${name}`;\n}", "Sans argument, le résultat devient Bonjour undefined.",
    ["Ajoute = 'apprenant' après name.", "Appelle greet() sans argument.", "Appelle ensuite greet('Maya') et compare."],
    "Crée paginationLabel(page = 1, total = 1) qui reste valide sans argument.",
    ["La valeur se déclare dans la signature.", "Elle s'applique pour undefined, pas forcément pour null.", "Choisis un repli utile pour l'utilisateur."],
    ["name reçoit apprenant si aucun argument n'est fourni.", "Le template utilise toujours une chaîne valide.", "Un argument explicite remplace le défaut.", "Le comportement de repli est visible dans la signature."],
    "Un paramètre par défaut documente et sécurise le cas où une entrée manque.",
    "La prochaine leçon place un comportement directement sur un objet."
  ),
  "js-02-object-method": item(
    "Un objet peut regrouper l'état d'une entité et les actions qui le modifient. Une méthode garde le comportement proche des données concernées.",
    ["Lire un objet", "Ajouter une méthode", "Utiliser this pour modifier l'objet courant"],
    [["objet", "Collection de propriétés associées."], ["méthode", "Fonction stockée dans un objet."], ["this", "Référence à l'objet utilisé pour appeler la méthode."]],
    "const lesson = {\n  title: 'Fonctions',\n  done: false,\n  complete() { this.done = true; }\n};", "La méthode modifie explicitement l'état de la leçon qui la reçoit.",
    "function complete() { lesson.done = true; }", "La fonction dépend du nom précis lesson et ne peut pas servir à un autre objet.",
    ["Ajoute une virgule après done.", "Déclare complete() dans l'objet.", "Passe this.done à true puis appelle lesson.complete()."],
    "Crée un objet cart avec items et une méthode add(item).",
    ["Une méthode partage la syntaxe d'une propriété.", "this désigne l'objet avant le point lors de l'appel.", "Vérifie l'état avant et après l'appel."],
    ["lesson regroupe titre et état.", "complete est une méthode.", "this.done cible la propriété de l'objet courant.", "L'affectation true mémorise la complétion."],
    "Un objet devient plus cohérent lorsque ses données et ses actions évoluent ensemble.",
    "Le module suivant transforme des collections de données."
  ),
  "js-03-arrays": item(
    "Les applications affichent souvent une partie d'un catalogue. filter crée une nouvelle liste contenant uniquement les éléments qui respectent une condition.",
    ["Comprendre un tableau", "Utiliser filter", "Écrire un prédicat lisible"],
    [["tableau", "Collection ordonnée de valeurs."], ["filter", "Méthode créant un tableau avec les éléments retenus."], ["prédicat", "Fonction qui retourne true ou false."]],
    "const htmlCourses = courses.filter(course => course.track === 'html');", "Le prédicat décrit exactement la condition de conservation.",
    "const htmlCourses = [];\nfor (const course of courses) { if (course.track === 'html') htmlCourses.push(course); }", "La boucle fonctionne mais mélange parcours, condition et mutation pour un besoin simple.",
    ["Appelle .filter sur courses.", "Nomme l'élément courant course.", "Retourne la comparaison de track avec html."],
    "Filtre une liste de produits disponibles sous 50 euros.",
    ["filter retourne un nouveau tableau.", "Le tableau source n'est pas modifié.", "Le prédicat doit produire un booléen."],
    ["courses est la collection source.", "filter examine chaque course.", "La comparaison retient seulement track html.", "htmlCourses reçoit la nouvelle collection."],
    "filter répond à la question : quels éléments faut-il conserver ?",
    "La prochaine leçon transforme chaque élément d'une collection."
  ),
  "js-03-map": item(
    "Une interface a souvent besoin d'une autre représentation des mêmes données. map transforme chaque élément et conserve le même nombre d'éléments.",
    ["Utiliser map", "Extraire une propriété", "Distinguer transformation et filtrage"],
    [["map", "Méthode créant une valeur transformée pour chaque élément."], ["projection", "Nouvelle représentation d'une donnée."], ["callback", "Fonction fournie à une autre fonction."]],
    "const titles = courses.map(course => course.title);", "Chaque objet cours devient son titre et l'ordre est conservé.",
    "const titles = courses.filter(course => course.title);", "filter conserverait les objets ayant un titre au lieu d'extraire leurs titres.",
    ["Appelle .map sur courses.", "Reçois course dans la callback.", "Retourne course.title."],
    "Transforme une liste de profils en libellés contenant nom et rôle.",
    ["map conserve la longueur du tableau.", "La callback retourne la nouvelle valeur.", "Utilise filter seulement pour retirer des éléments."],
    ["courses fournit les objets.", "map appelle la callback pour chacun.", "course.title devient la valeur produite.", "titles contient uniquement les chaînes."],
    "map répond à la question : à quoi doit ressembler chaque élément ?",
    "La prochaine leçon combine toute une collection en un seul résultat."
  ),
  "js-03-reduce-xp": item(
    "Additionner, regrouper ou construire un résumé demande de combiner toute une collection. reduce transporte un résultat intermédiaire d'un élément au suivant.",
    ["Comprendre l'accumulateur", "Définir une valeur initiale", "Additionner les XP"],
    [["reduce", "Méthode combinant une collection en une valeur."], ["accumulateur", "Résultat intermédiaire mis à jour."], ["valeur initiale", "Premier état de l'accumulateur."]],
    "const totalXp = lessons.reduce((sum, lesson) => sum + lesson.xp, 0);", "La valeur initiale 0 et le calcul d'addition sont explicites.",
    "let totalXp = 0;\nlessons.forEach(lesson => totalXp += lesson.xp);", "La variable extérieure est mutée par effet de bord.",
    ["Commence par reduce sur lessons.", "Nomme l'accumulateur sum.", "Ajoute lesson.xp et fournis 0 comme valeur initiale."],
    "Utilise reduce pour compter les leçons terminées puis pour regrouper les XP par module.",
    ["L'accumulateur est le premier paramètre.", "La callback doit retourner sa nouvelle valeur.", "Pour une somme, la valeur initiale naturelle est 0."],
    ["L'accumulateur commence à 0.", "Chaque lesson fournit xp.", "sum + lesson.xp devient le prochain accumulateur.", "Le résultat final est stocké dans totalXp."],
    "reduce répond à la question : comment combiner toute la collection en un résultat ?",
    "La prochaine leçon recherche un élément unique."
  ),
  "js-03-find": item(
    "Quand une application connaît l'identifiant d'une ressource, elle doit retrouver l'objet correspondant sans conserver le reste de la collection.",
    ["Utiliser find", "Comparer un identifiant", "Gérer l'absence de résultat"],
    [["find", "Méthode retournant le premier élément correspondant."], ["identifiant", "Valeur distinguant une ressource."], ["résultat absent", "Cas où find retourne undefined."]],
    "const cssCourse = courses.find(course => course.id === 'css');", "La recherche s'arrête dès que l'identifiant correspond.",
    "const cssCourse = courses.filter(course => course.id === 'css');", "filter retourne un tableau alors que le besoin porte sur un seul objet.",
    ["Appelle find sur courses.", "Compare course.id avec css.", "Teste ensuite un identifiant inexistant."],
    "Recherche un utilisateur par id et affiche un message clair lorsqu'il n'existe pas.",
    ["find retourne un élément, pas un tableau.", "Une absence produit undefined.", "Utilise une comparaison stricte ===."],
    ["find parcourt courses.", "La callback compare chaque id.", "Le premier objet correspondant est renvoyé.", "cssCourse peut être undefined si aucun résultat n'existe."],
    "find répond à la question : quel est le premier élément qui correspond ?",
    "La prochaine leçon vérifie si au moins un élément satisfait une règle."
  ),
  "js-03-some": item(
    "Certaines décisions dépendent de l'existence d'au moins un élément : afficher une alerte, activer une action ou montrer une progression.",
    ["Utiliser some", "Produire un booléen à partir d'une collection", "Éviter un comptage inutile"],
    [["some", "Méthode indiquant si au moins un élément satisfait le prédicat."], ["court-circuit", "Arrêt dès que le résultat est connu."], ["existence", "Présence d'au moins un cas correspondant."]],
    "const hasCompleted = lessons.some(lesson => lesson.done);", "Le nom et la méthode expriment directement la question booléenne.",
    "const hasCompleted = lessons.filter(lesson => lesson.done).length > 0;", "Cette approche construit inutilement un nouveau tableau.",
    ["Appelle some sur lessons.", "Retourne lesson.done.", "Teste une liste entièrement incomplète puis une liste mixte."],
    "Détermine si un panier contient au moins un produit indisponible.",
    ["some retourne toujours un booléen.", "Il s'arrête au premier true.", "Une propriété booléenne peut être retournée directement."],
    ["some examine les leçons.", "lesson.done constitue le prédicat.", "Le premier true suffit.", "hasCompleted reçoit le booléen final."],
    "some répond à la question : existe-t-il au moins un élément correspondant ?",
    "Le module suivant relie les données JavaScript à l'interface HTML."
  ),
  "js-04-dom-events": item(
    "Le DOM représente la page que JavaScript peut lire et modifier. Un événement relie une action utilisateur à une mise à jour visible.",
    ["Sélectionner deux éléments", "Écouter un clic", "Mettre à jour textContent"],
    [["DOM", "Représentation objet du document HTML."], ["événement", "Signal produit par une interaction."], ["listener", "Fonction exécutée lors d'un événement."], ["textContent", "Texte d'un élément."]],
    "const button = document.querySelector('#plus');\nconst output = document.querySelector('#count');\nbutton.addEventListener('click', () => {\n  output.textContent = Number(output.textContent) + 1;\n});", "Les éléments sont nommés, l'événement est explicite et la valeur est convertie avant le calcul.",
    "plus.onclick = () => count.innerHTML++;", "Le code dépend de variables globales implicites et utilise innerHTML sans besoin.",
    ["Sélectionne #plus et #count.", "Ajoute un listener click.", "Convertis le texte en nombre avant de l'incrémenter."],
    "Ajoute un bouton de remise à zéro et désactive-le lorsque le compteur vaut zéro.",
    ["querySelector reçoit un sélecteur CSS.", "addEventListener reçoit le nom de l'événement.", "textContent est une chaîne, même si elle affiche un nombre."],
    ["querySelector récupère les deux éléments.", "Le listener attend un clic.", "Number convertit le texte.", "textContent affiche la nouvelle valeur."],
    "Une interaction DOM suit le cycle sélectionner, écouter, calculer, rendre.",
    "La prochaine leçon modifie un état visuel avec une classe."
  ),
  "js-04-class-toggle": item(
    "JavaScript doit piloter l'état d'un composant tandis que CSS décide de son apparence. Modifier une classe maintient cette séparation.",
    ["Sélectionner un contrôle et une carte", "Basculer une classe", "Laisser le style à CSS"],
    [["classList", "API manipulant les classes d'un élément."], ["toggle", "Ajoute une classe absente ou retire une classe présente."], ["état visuel", "Apparence correspondant à un état du composant."]],
    "const card = document.querySelector('.card');\ntoggle.addEventListener('click', () => card.classList.toggle('active'));", "JavaScript exprime l'état active sans écrire directement des styles.",
    "card.style.background = card.style.background ? '' : 'yellow';", "Le comportement connaît des détails visuels et devient difficile à faire évoluer.",
    ["Sélectionne #toggle et .card.", "Écoute click.", "Appelle classList.toggle avec active."],
    "Crée un bouton qui ouvre et ferme un panneau tout en mettant à jour aria-expanded.",
    ["toggle reçoit le nom sans point.", "CSS doit contenir la règle .card.active.", "Un état interactif peut aussi nécessiter un attribut ARIA."],
    ["Le bouton déclenche l'action.", "classList cible la liste de classes.", "toggle inverse active.", "CSS peut maintenant définir librement le rendu."],
    "JavaScript gère l'état ; CSS traduit cet état visuellement.",
    "La prochaine leçon traite une saisie de formulaire sans recharger la page."
  ),
  "js-04-form-submit": item(
    "Un formulaire fournit un événement submit qui couvre clic sur le bouton et validation au clavier. L'intercepter permet de traiter les données dans l'application.",
    ["Écouter submit", "Empêcher le rechargement", "Lire et valider une valeur"],
    [["submit", "Événement d'envoi d'un formulaire."], ["preventDefault", "Empêche le comportement natif associé."], ["value", "Valeur actuelle d'un contrôle."]],
    "form.addEventListener('submit', event => {\n  event.preventDefault();\n  const title = task.value.trim();\n});", "L'événement s'applique au formulaire et la valeur est nettoyée avant utilisation.",
    "button.addEventListener('click', () => task.value);", "La touche Entrée peut être oubliée et le formulaire recharge encore la page.",
    ["Sélectionne le formulaire et le champ.", "Écoute submit sur le formulaire.", "Appelle preventDefault puis lis value."],
    "Ajoute une validation qui refuse un titre vide et affiche un message de statut.",
    ["Le listener appartient au formulaire.", "event est fourni à la callback.", "trim retire les espaces inutiles."],
    ["submit couvre les modes d'envoi natifs.", "preventDefault conserve l'état de la page.", "value lit la saisie.", "trim prépare une validation fiable."],
    "Traiter submit respecte le fonctionnement du formulaire tout en ajoutant la logique applicative.",
    "Le mini-projet suivant assemble état, actions et rendu."
  ),
  "js-04-mini-project-counter": item(
    "Le compteur introduit une architecture essentielle : un état unique, des actions qui le modifient et une fonction qui synchronise l'interface.",
    ["Séparer état et rendu", "Créer des actions prévisibles", "Rendre après chaque modification"],
    [["état", "Données représentant la situation actuelle."], ["rendu", "Mise à jour de l'interface depuis l'état."], ["action", "Fonction modifiant l'état."]],
    "let count = 0;\nfunction render() { output.textContent = count; }\nfunction increment() { count += 1; render(); }", "L'état est la source de vérité et render reflète toujours sa valeur.",
    "function increment() { output.textContent++; }", "L'interface devient elle-même la source de données et la logique se disperse.",
    ["Déclare count.", "Écris render sans modifier count.", "Écris increment et decrement puis appelle render après chaque changement."],
    "Ajoute des limites min/max, un bouton reset et un message lorsque la limite est atteinte.",
    ["Une seule variable porte l'état.", "Les actions modifient l'état avant le rendu.", "render ne doit pas décider de la prochaine valeur."],
    ["count mémorise la valeur.", "render projette count dans le DOM.", "increment et decrement changent uniquement l'état.", "Chaque action appelle ensuite render."],
    "Le cycle état, action, rendu sert de base aux interfaces JavaScript et aux frameworks modernes.",
    "Le module suivant conserve les données et communique avec un serveur."
  ),
  "js-05-storage": item(
    "Sans persistance, les préférences disparaissent au rechargement. localStorage conserve de petites chaînes dans le navigateur.",
    ["Écrire une valeur locale", "Choisir une clé stable", "Comprendre les limites du stockage local"],
    [["localStorage", "Stockage persistant propre à une origine web."], ["clé", "Nom utilisé pour retrouver une valeur."], ["setItem", "Méthode qui enregistre une chaîne."]],
    "localStorage.setItem('pulsa-theme', theme);", "La clé décrit précisément la donnée et la valeur vient de la variable.",
    "localStorage.setItem('x', 'happy');", "La clé est opaque et la valeur est dupliquée.",
    ["Repère la clé et la valeur demandées.", "Appelle localStorage.setItem.", "Recharge puis lis la valeur avec getItem dans la console."],
    "Sauvegarde et restaure le dernier module visité.",
    ["setItem reçoit clé puis valeur.", "localStorage stocke des chaînes.", "Ne stocke jamais de secret ou de donnée sensible."],
    ["localStorage désigne le stockage du navigateur.", "setItem écrit la donnée.", "pulsa-theme est la clé stable.", "theme fournit la valeur actuelle."],
    "localStorage convient aux petites préférences non sensibles qui doivent survivre au rechargement.",
    "La prochaine leçon convertit des objets en chaînes JSON."
  ),
  "js-05-json-settings": item(
    "Le stockage et les échanges réseau transportent souvent du texte. JSON convertit une structure JavaScript en chaîne puis la reconstruit.",
    ["Sérialiser un objet", "Lire une chaîne JSON", "Distinguer objet et représentation textuelle"],
    [["JSON", "Format texte représentant des données structurées."], ["sérialisation", "Conversion d'une valeur en texte stockable."], ["parse", "Reconstruction d'une valeur depuis du JSON."]],
    "const json = JSON.stringify(settings);\nconst parsedSettings = JSON.parse(json);", "Les deux étapes et les deux représentations sont clairement séparées.",
    "localStorage.setItem('settings', settings);", "L'objet serait converti en chaîne peu utile [object Object].",
    ["Sérialise settings dans une variable json.", "Parse json dans parsedSettings.", "Compare les types avant et après chaque opération."],
    "Sauvegarde une liste de favoris dans localStorage puis restaure-la au chargement.",
    ["stringify va de JavaScript vers le texte.", "parse va du texte vers JavaScript.", "Un JSON invalide peut faire échouer parse."],
    ["settings est l'objet initial.", "stringify produit une chaîne.", "parse lit cette chaîne.", "parsedSettings retrouve une structure manipulable."],
    "JSON est le pont courant entre structures JavaScript et stockage textuel.",
    "La prochaine leçon charge des données depuis une API."
  ),
  "js-06-fetch": item(
    "Une application front-end obtient souvent ses données depuis un serveur. fetch démarre la requête et async/await rend les étapes lisibles.",
    ["Déclarer une fonction async", "Attendre une réponse", "Lire le corps JSON"],
    [["API", "Interface permettant à des logiciels d'échanger."], ["fetch", "Fonction lançant une requête HTTP."], ["Promise", "Objet représentant un résultat futur."], ["await", "Attend le résultat d'une Promise dans une fonction async."]],
    "async function loadCourses() {\n  const response = await fetch('/api/courses');\n  const courses = await response.json();\n  return courses;\n}", "La requête, la lecture du corps et le retour sont des étapes distinctes.",
    "const courses = fetch('/api/courses').json();", "fetch retourne une Promise, pas directement une réponse utilisable.",
    ["Ajoute async devant function.", "Attends fetch dans response.", "Attends response.json puis retourne les données."],
    "Charge un profil et affiche successivement les états chargement, succès et absence de données.",
    ["await s'utilise dans une fonction async.", "response représente la réponse HTTP.", "response.json() est elle aussi asynchrone."],
    ["async autorise await.", "fetch lance la requête.", "Le premier await obtient response.", "Le second lit le JSON.", "return fournit les données."],
    "Un chargement réseau est une suite d'étapes asynchrones qui doivent rester visibles dans le code et l'interface.",
    "La prochaine leçon gère les réponses en erreur et les pannes réseau."
  ),
  "js-06-fetch-errors": item(
    "Une requête peut échouer sans que le code soit mauvais : réseau coupé, serveur indisponible ou réponse 404. Une interface robuste prévoit ces résultats.",
    ["Utiliser try/catch", "Vérifier response.ok", "Produire une erreur utile"],
    [["try/catch", "Structure capturant une erreur d'exécution."], ["response.ok", "Booléen vrai pour une réponse HTTP réussie."], ["throw", "Interrompt le flux en produisant une erreur."]],
    "async function loadProfile() {\n  try {\n    const response = await fetch('/api/profile');\n    if (!response.ok) throw new Error(`HTTP ${response.status}`);\n    return await response.json();\n  } catch (error) {\n    console.error('Profil indisponible', error);\n  }\n}", "Les erreurs réseau et HTTP rejoignent un chemin de traitement explicite.",
    "const response = await fetch('/api/profile');\nreturn response.json();", "Une réponse 404 serait traitée comme un succès et aucune panne n'est expliquée.",
    ["Place fetch dans try.", "Teste !response.ok.", "Lance une Error puis traite-la dans catch."],
    "Ajoute une stratégie de nouvelle tentative limitée et un message utilisateur actionnable.",
    ["fetch ne rejette pas automatiquement les réponses 404 ou 500.", "throw envoie l'exécution vers catch.", "Le message utilisateur ne doit pas exposer les détails techniques."],
    ["try contient l'opération risquée.", "response.ok valide le statut HTTP.", "throw transforme un mauvais statut en erreur.", "catch centralise le repli.", "Le log conserve le diagnostic."],
    "Une requête robuste distingue chargement, succès, absence de données et erreur.",
    "Le projet final assemble état, rendu, formulaires et persistance."
  ),
  "js-07-final-project": item(
    "Le dashboard final rassemble les concepts du parcours dans une petite application persistante : données, actions, rendu et sauvegarde.",
    ["Concevoir un état central", "Ajouter une tâche de façon prévisible", "Sauvegarder après chaque modification", "Préparer un rendu maintenable"],
    [["source de vérité", "Emplacement de référence contenant l'état actuel."], ["persistance", "Conservation des données entre deux sessions."], ["architecture", "Organisation des responsabilités du programme."]],
    "const state = { tasks: [] };\nfunction addTask(title) {\n  state.tasks.push({ title, done: false });\n  save();\n  render();\n}", "L'action modifie l'état puis déclenche explicitement persistance et rendu.",
    "function addTask(title) {\n  document.body.innerHTML += title;\n  localStorage.setItem('task', title);\n}", "Le DOM et le stockage deviennent des sources partielles et aucune liste cohérente n'existe.",
    ["Définis d'abord la forme de state.", "Écris render à partir de state.tasks.", "Écris addTask puis sauvegarde tout state.", "Teste plusieurs ajouts et un rechargement."],
    "Ajoute complétion, suppression, filtre et restauration initiale, puis documente le flux de données.",
    ["Une seule structure doit contenir les tâches.", "Chaque action modifie state avant d'appeler render.", "JSON.stringify prépare le stockage de l'objet complet.", "Teste le cas d'un stockage absent ou invalide."],
    ["state centralise les tâches.", "addTask crée un objet cohérent.", "push l'ajoute à la collection.", "localStorage persiste une représentation JSON.", "render synchronise l'interface."],
    "Le projet est réussi lorsque l'état explique toujours l'interface et survit au rechargement sans incohérence.",
    "Après ce projet, consolide le parcours en construisant une application personnelle avec API et gestion d'erreurs."
  )
};

export function getJsPedagogy(id) {
  return jsPedagogy[id] ? { fr: jsPedagogy[id] } : null;
}
